# Regression guard independent of legacy_2025_golden_output.rds
#
# The large 2025 fixture is an idempotence gate in v0.1 because its golden was
# generated by the package pipeline. This always-on guard pins a tiny
# hand-computed rate case so formula drift cannot be hidden by regenerating the
# large golden output.

.independent_guard_fixture <- function() {
  long <- tibble::tibble(
    site_id                       = "S01",
    drive_time_min                = 15L,
    ring_topology                 = "cumulative",
    variable                      = "B17001_002",
    estimate                      = 50,
    moe                           = 1.645 * sqrt(100),
    weight_sum                    = 0.8,
    n_tracts                      = 2L,
    n_tracts_num                  = NA_integer_,
    n_tracts_den                  = NA_integer_,
    provider                      = "osrm",
    profile                       = "car",
    osm_snapshot_date             = "2026-01-01",
    acs_year                      = 2023L,
    weight_method                 = "area",
    estimand_family               = "spatial_total",
    weight_basis                  = "coverage",
    moe_formula_requested         = "weighted_sum",
    moe_formula_effective         = "weighted_sum",
    moe_fallback                  = FALSE,
    moe_fallback_reason           = "n/a",
    failure_origin                = "none",
    weight_uncertainty_propagated = FALSE
  )

  carriers <- tibble::tibble(
    site_id         = rep("S01", 10L),
    drive_time_min  = rep(15L, 10L),
    variable        = c(
      "B17001_002", "B17001_001",   # poverty numerator / denominator
      "B22003_002", "B22003_001",   # SNAP
      "B19056_002", "B19056_001",   # SSI
      "B23025_005", "B23025_003",   # unemployment
      "B23025_002", "B23025_001"    # labor-force participation
    ),
    estimand_family = rep("spatial_total", 10L),
    est_total       = c(50, 200, 20, 100, 5, 80, 25, 200, 300, 600),
    var_total_raw   = c(100, 400, 50, 300, 30, 200, 50, 500, 700, 900),
    est_mean        = rep(NA_real_, 10L),
    var_mean_raw    = rep(NA_real_, 10L),
    weight_sum      = rep(0.8, 10L),
    n_tracts        = rep(2L, 10L)
  )

  attr(long, "cacs_aggregation_carriers") <- carriers
  attr(long, "cacs_schema_version") <- "1.0"
  attr(long, "cacs_confidence_level") <- 0.90
  long
}

test_that("independent regression guard pins poverty C2 ratio formula", {
  out <- suppressWarnings(cacs_derive_rates(.independent_guard_fixture()))
  poverty <- out[out$variable == "poverty_rate", ]

  testthat::expect_equal(nrow(poverty), 1L)
  testthat::expect_equal(poverty$estimate, 0.25, tolerance = 1e-12)
  testthat::expect_equal(
    poverty$moe,
    1.645 * sqrt(100 + 0.25^2 * 400) / 200,
    tolerance = 1e-9
  )
  testthat::expect_equal(
    poverty$moe_formula_effective,
    "general_ratio_conservative"
  )
  testthat::expect_equal(poverty$moe_fallback_reason, "n/a")
})

test_that("independent regression guard pins poverty C1 subset formula", {
  out <- suppressWarnings(
    cacs_derive_rates(
      .independent_guard_fixture(),
      formula_dispatch = "proportion_subset"
    )
  )
  poverty <- out[out$variable == "poverty_rate", ]

  testthat::expect_equal(nrow(poverty), 1L)
  testthat::expect_equal(poverty$estimate, 0.25, tolerance = 1e-12)
  testthat::expect_equal(
    poverty$moe,
    1.645 * sqrt(100 - 0.25^2 * 400) / 200,
    tolerance = 1e-9
  )
  testthat::expect_equal(poverty$moe_formula_effective, "proportion_subset")
  testthat::expect_false(poverty$moe_fallback)
})


# v0.2 BUG-001 (F3) Layer (a) regression-byte-identity guard.
#
# The independent guard fixture is synthetic-non-water by construction
# (single GEOID "01001000001" - Autauga County tract 1, not a 99xxxx
# water mask; no degenerate-area rows). The new `.drop_water_tracts()`
# helper introduced in v0.2 must therefore be a no-op on this fixture
# (kept_sf identical, no GEOIDs dropped) regardless of whether the
# default `drop_water_tracts = TRUE` would fire on a real Census pull.
#
# This test pins the contract that the v0.2 water-tract auto-filter
# default does not silently mutate any non-water input. It complements
# the prefetch-side byte-identity guarantees and isolates the helper
# from cacs_acs_prefetch()'s suppression-carry-through ordering.
test_that("v0.2 .drop_water_tracts() is a no-op on the independent regression fixture", {
  # Build a tiny single-tract sf mirroring the fixture's tract universe
  # (the rate guard above is tibble-only; here we need geometry for the
  # helper's st_area() criterion).
  ring <- rbind(
    c(-86.50, 32.45), c(-86.30, 32.45),
    c(-86.30, 32.60), c(-86.50, 32.60),
    c(-86.50, 32.45)
  )
  one_tract <- sf::st_sf(
    GEOID    = "01001000001",
    NAME     = "Census Tract 1, Autauga County, Alabama",
    variable = "B17001_002",
    estimate = 50,
    moe      = 1.645 * sqrt(100),
    geometry = sf::st_sfc(sf::st_multipolygon(list(list(ring))), crs = 4269)
  )

  res_on <- catchmentACS:::.drop_water_tracts(
    acs_sf            = one_tract,
    drop_water_tracts = TRUE,
    verbose           = FALSE
  )

  testthat::expect_identical(nrow(res_on$kept_sf), nrow(one_tract))
  testthat::expect_identical(res_on$kept_sf$GEOID, one_tract$GEOID)
  testthat::expect_identical(res_on$dropped_geoids, character(0))
  testthat::expect_identical(res_on$dropped_reasons, character(0))

  # Opt-out also returns the input untouched (defensive lock).
  res_off <- catchmentACS:::.drop_water_tracts(
    acs_sf            = one_tract,
    drop_water_tracts = FALSE,
    verbose           = FALSE
  )
  testthat::expect_identical(nrow(res_off$kept_sf), nrow(one_tract))
  testthat::expect_identical(res_off$dropped_geoids, character(0))
})
