<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Methodology: the pipeline as an estimator • catchmentACS</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="image/svg+xml" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<!-- katex math --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script><script src="../katex-auto.js"></script><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="methodology_files/libs/quarto-html/popper.min.js"></script><script src="methodology_files/libs/quarto-html/tippy.umd.min.js"></script><link href="methodology_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="methodology_files/libs/quarto-html/light-border.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Methodology: the pipeline as an estimator">
<meta property="og:image" content="https://joonho112.github.io/catchmentACS/logo.svg">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">catchmentACS</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.5.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-vignettes" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Vignettes</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-vignettes">
<li><h6 class="dropdown-header" data-toc-skip>--- Applied Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/getting-started.html">Getting started</a></li>
    <li><a class="dropdown-item" href="../articles/alabama-tutorial.html">Alabama tutorial</a></li>
    <li><a class="dropdown-item" href="../articles/providers.html">Providers</a></li>
    <li><a class="dropdown-item" href="../articles/visual-walkthrough.html">Visual walkthrough</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Method Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/methodology.html">Methodology</a></li>
    <li><a class="dropdown-item" href="../articles/theory-spatial-aggregation.html">Spatial aggregation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-moe-propagation.html">MOE propagation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-derived-rates.html">Derived rates</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Migration ---</h6></li>
    <li><a class="dropdown-item" href="../articles/porting-v01-to-v03.html">Porting from v0.1 to v0.3</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v03-to-v04.html">Porting from v0.3 to v0.4</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v04-to-v05.html">Porting from v0.4 to v0.5</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/joonho112/catchmentACS/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.svg" class="logo" alt=""><h1>Methodology: the pipeline as an estimator</h1>




      <small class="dont-index">Source: <a href="https://github.com/joonho112/catchmentACS/blob/HEAD/vignettes/methodology.qmd" class="external-link"><code>vignettes/methodology.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/joonho112/catchmentACS" class="external-link">catchmentACS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/" class="external-link">sf</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Force network-free, deterministic builds: no provider/Census calls, no cache.</span></span>
<span><span class="va">old_options</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span></span>
<span>  catchmentACS.progress <span class="op">=</span> <span class="st">"off"</span>,</span>
<span>  catchmentACS.rate_first_default <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span><span class="va">old_cache</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">getOption</a></span><span class="op">(</span><span class="st">"catchmentACS.cache_enabled"</span>, <span class="cn">NULL</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="va">old_options</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span>catchmentACS.cache_enabled <span class="op">=</span> <span class="va">old_cache</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/cacs_set_cache.html">cacs_set_cache</a></span><span class="op">(</span><span class="cn">FALSE</span>, scope <span class="op">=</span> <span class="st">"session"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>This article is the entry point to the package’s <strong>method track</strong>. It frames the whole <code>catchmentACS</code> pipeline as a single statistical <em>estimator</em>, fixes the <strong>notation</strong> that the deeper theory articles reuse, names the six estimand families the package is built around, and shows — in real numbers, on the bundled fixtures — why a count and an average are aggregated with <em>different</em> weights. Where the applied articles answer “how do I run this?”, this one answers “what, exactly, is being estimated, and by what formula?”</p>
<p>It is deliberately math-light and does <strong>not</strong> re-derive the math: each estimand family and each margin-of-error (MOE) formula has a full derivation in a dedicated theory article, and this overview states the result and points there. The three companion articles are <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code>, <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code>, and <code><a href="../articles/theory-derived-rates.html">vignette("theory-derived-rates", package = "catchmentACS")</a></code>. By the end you should be able to read any catchment estimate as <span class="math inline">\text{estimate} \pm \text{MOE}</span> and know which of six families produced it.</p>
<p>If you want to <em>run</em> the pipeline rather than read its math, start with <code><a href="../articles/getting-started.html">vignette("getting-started", package = "catchmentACS")</a></code> and <code><a href="../articles/alabama-tutorial.html">vignette("alabama-tutorial", package = "catchmentACS")</a></code>.</p>
<div>
<blockquote>
<p><strong>About the data in this article</strong></p>
<p>Every executable cell here is built entirely from the package’s bundled <code>inst/extdata</code> fixtures — the synthetic <code>legacy_2025_*</code> objects and the <code>sample_alabama_subset</code> ACS extract — so this article renders with <strong>no</strong> Census, OSRM, ORS, or other network calls. These fixtures preserve the production calling contract (sites, drive-time polygons, tract-level ACS variables) but are <strong>synthetic and illustrative</strong>: they are included only for examples, tests, and reproducible package checks. They are <strong>not</strong> live Alabama policy estimates and must not be cited as real ACS results. Any real analysis requires a fresh live run (see <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>).</p>
</blockquote>
</div>
<section class="level2"><h2 id="the-pipeline-is-an-estimator">The pipeline is an estimator<a class="anchor" aria-label="anchor" href="#the-pipeline-is-an-estimator"></a>
</h2>
<p>It helps to read the whole pipeline as one estimator. <code><a href="../reference/cacs_run.html">cacs_run()</a></code> looks like a data-processing wrapper, but statistically it is one estimator with five stages. Two stages reach data sources; the last three are deterministic computation on whatever those returned:</p>
<blockquote>
<p><code><a href="../reference/cacs_acs_prefetch.html">cacs_acs_prefetch()</a></code> (ACS download) → <code><a href="../reference/cacs_isochrone.html">cacs_isochrone()</a></code> (routing) → <code><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight()</a></code> → <code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code> → <code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code>.</p>
</blockquote>
<p>The estimand is a neighborhood characteristic <em>inside a drive-time catchment</em>. The ACS publishes its estimates on <strong>census tracts</strong>, which do not line up with catchments — a drive-time area slices through tract boundaries. So the estimator re-expresses tract-level published values as catchment-level values by <strong>area-weighted aggregation</strong>, then carries the published uncertainty through that aggregation. Concretely, for each site <span class="math inline">s</span>:</p>
<ol type="1">
<li>
<strong>Sites → catchments.</strong> Take the drive-time isochrone polygon <span class="math inline">I_s</span> (drawn fresh, or reused from precomputed polygons) and the ACS tract polygons <span class="math inline">T_j</span>.</li>
<li>
<strong>Catchments → tract overlaps.</strong> Cut the intersections <span class="math inline">I_s \cap T_j</span> on an equal-area projection, and from each intersection build a <em>weight</em> describing how much of tract <span class="math inline">j</span> the catchment captures.</li>
<li>
<strong>Overlaps → estimates.</strong> Aggregate each tract-level estimate <span class="math inline">Y_j</span> (or <span class="math inline">X_j</span>) to the catchment with the weight that matches the variable’s <em>estimand family</em>.</li>
<li>
<strong>Estimates → margins of error.</strong> Propagate the published tract-level MOEs through the same weights.</li>
<li>
<strong>Estimates → rates.</strong> Form the curated derived rates as ratios of aggregated numerators and denominators, each with its own propagated MOE.</li>
</ol>
<p>The single function <code><a href="../reference/cacs_run.html">cacs_run()</a></code> chains these stages; the five pipeline functions expose each one on its own. Two choices in steps 2–3 carry the entire statistical content of the package, and they are the reason the rest of this article exists: <strong>which weight</strong>, and <strong>which family</strong>. Get either wrong and the arithmetic still runs — it just estimates the wrong thing, silently.</p>
<section class="level3"><h3 id="shared-notation">Shared notation<a class="anchor" aria-label="anchor" href="#shared-notation"></a>
</h3>
<p>The whole method track uses the same symbols. Establishing them once here lets the three theory articles stay terse.</p>
<table class="table caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Symbol</th>
<th>Meaning</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><span class="math inline">I_s</span></td>
<td>the drive-time isochrone (catchment) polygon for site <span class="math inline">s</span> (a cumulative ring)</td>
</tr>
<tr class="even">
<td><span class="math inline">T_j</span></td>
<td>census tract <span class="math inline">j</span>
</td>
</tr>
<tr class="odd">
<td><span class="math inline">I_s \cap T_j</span></td>
<td>the part of tract <span class="math inline">j</span> that falls inside the catchment</td>
</tr>
<tr class="even">
<td><span class="math inline">\lvert\,\cdot\,\rvert</span></td>
<td>equal-area measure (area on EPSG:5070, in <span class="math inline">\text{m}^2</span>)</td>
</tr>
<tr class="odd">
<td><span class="math inline">Y_j</span></td>
<td>a tract-level <strong>count</strong> ACS estimate (extensive: persons, households)</td>
</tr>
<tr class="even">
<td><span class="math inline">X_j</span></td>
<td>a tract-level <strong>scalar / proxy</strong> ACS estimate (intensive: a median, a per-capita figure)</td>
</tr>
<tr class="odd">
<td><span class="math inline">A_j, B_j</span></td>
<td>a ratio’s numerator and denominator counts in tract <span class="math inline">j</span>
</td>
</tr>
<tr class="even">
<td><span class="math inline">M_j</span></td>
<td>the published 90% margin of error for the tract-level estimate</td>
</tr>
</tbody>
</table>
<p>Two weights do all the work. The <strong>coverage weight</strong> is the fraction of a tract’s <em>area</em> captured by the catchment,</p>
<p><span class="math display">
w^{cov}_{sj} = \frac{\lvert I_s \cap T_j \rvert}{\lvert T_j \rvert},
</span></p>
<p>and the <strong>normalized mean weight</strong> is the catchment’s intersection area for tract <span class="math inline">j</span> as a share of <em>all</em> its intersection area,</p>
<p><span class="math display">
w^{mean}_{sj} = \frac{\lvert I_s \cap T_j \rvert}{\sum_k \lvert I_s \cap T_k \rvert},
\qquad \sum_j w^{mean}_{sj} = 1,
</span></p>
<p>so the mean weights sum to one within a site and drive-time cell. From these, the three estimator forms are</p>
<p><span class="math display">
\widehat{Y}_s = \sum_j w^{cov}_{sj}\, Y_j,
\qquad
\widehat{\bar X}_s = \sum_j w^{mean}_{sj}\, X_j,
\qquad
\widehat{R}_s = \frac{\sum_j w^{cov}_{sj}\, A_j}{\sum_j w^{cov}_{sj}\, B_j}.
</span></p>
<p>A <strong>spatial total</strong> allocates counts into the catchment with the coverage weight; a <strong>scalar/proxy mean</strong> blends intensive values with the normalized mean weight; a <strong>derived rate</strong> aggregates the numerator and denominator <em>each as a coverage total</em>, then divides. Throughout, standard errors and margins of error are interconvertible through the Census multiplier at the 90% level,</p>
<p><span class="math display">
M = 1.645\, SE, \qquad SE = \frac{M}{1.645},
</span></p>
<p>and every margin of error in the pipeline is reported at that level: variances accumulate on the SE scale and convert back at the end.</p>
</section></section><section class="level2"><h2 id="the-six-estimand-families-at-a-glance">The six estimand families at a glance<a class="anchor" aria-label="anchor" href="#the-six-estimand-families-at-a-glance"></a>
</h2>
<p>A variable’s <em>estimand family</em> decides which weight aggregates it and which MOE path applies. This is the central methodological point of the package, and the spatial aggregation algorithm is built around it: a count and a median are aggregated by <strong>different</strong> weights, and using the wrong one is a silent statistical error, not a runtime failure.</p>
<table class="table caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead><tr class="header">
<th>Estimand family</th>
<th>Example variable</th>
<th>Point estimate</th>
<th>Weight</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>spatial_total</code></td>
<td>total population; persons in poverty (<code>B17001_002</code>)</td>
<td><span class="math inline">\widehat{Y}_s = \sum_j w^{cov}_{sj} Y_j</span></td>
<td>coverage <span class="math inline">w^{cov}_{sj}</span>
</td>
</tr>
<tr class="even">
<td><code>derived_rate</code></td>
<td>poverty rate; SNAP rate</td>
<td><span class="math inline">\widehat{R}_s = \dfrac{\sum_j w^{cov}_{sj} A_j}{\sum_j w^{cov}_{sj} B_j}</span></td>
<td>coverage (numerator and denominator separately)</td>
</tr>
<tr class="odd">
<td><code>area_weighted_scalar_proxy</code></td>
<td>per-capita income (<code>B19301_001</code>)</td>
<td><span class="math inline">\widehat{\bar X}_s = \sum_j w^{mean}_{sj} X_j</span></td>
<td>normalized mean <span class="math inline">w^{mean}_{sj}</span>
</td>
</tr>
<tr class="even">
<td>
<code>population_weighted_scalar_proxy</code> <em>(reserved)</em>
</td>
<td>scalar proxy under population weighting</td>
<td><span class="math inline">\widehat{\bar X}_s = \sum_j w^{mean}_{sj} X_j</span></td>
<td>population-normalized mean</td>
</tr>
<tr class="odd">
<td><code>median_proxy</code></td>
<td>tract median household income (<code>B19013_001</code>)</td>
<td>weighted blend of tract medians, <strong>not</strong> the true catchment median</td>
<td>normalized mean <span class="math inline">w^{mean}_{sj}</span>
</td>
</tr>
<tr class="even">
<td><code>metadata_only</code></td>
<td>provenance fields</td>
<td>no numeric aggregation</td>
<td>none</td>
</tr>
</tbody>
</table>
<p>Read the table by weight. An extensive <strong>count</strong> like <em>persons in poverty</em> must be <em>summed</em> into the catchment with the <strong>coverage weight</strong> — half a tract contributes half its people. An intensive <strong>scalar</strong> like <em>per-capita income</em> must be <em>averaged</em> with the <strong>normalized mean weight</strong> — half a tract does not contribute “half a dollar per person,” so the contributions average rather than accumulate. Derived rates are a special case: numerator and denominator are each aggregated as coverage-weighted totals, then divided, so the rate inherits the coverage path. The <code>median_proxy</code> family is labelled a <em>proxy</em> on purpose — a weighted blend of tract medians is not the true median of the pooled catchment population, and the package keeps that caveat attached to the estimate.</p>
<p>Add an intensive variable as if it were a count, or divide a count by a weight sum as if it were an average, and you get a number with no defensible interpretation. Nothing errors; the result is just wrong. The family classifier is what stops that from happening — and the next section shows the two paths diverging on actual fixture numbers.</p>
<p>Two families are scaffolding rather than active estimators in this release. In <code>weight_method = "area"</code> (the implemented path), the area forms of the weights above are active. <code>population_weighted_scalar_proxy</code> and the population mean weight are a reserved future surface; <code>weight_method = "population"</code> fails loud at the orchestrator boundary today. <code>metadata_only</code> rows carry provenance and receive no numeric aggregation. The classifier and the per-family aggregation are documented in the “Estimand families and weights” section of <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>.</p>
</section><section class="level2"><h2 id="a-worked-example-coverage-total-vs-mean-proxy">A worked example: coverage total vs mean proxy<a class="anchor" aria-label="anchor" href="#a-worked-example-coverage-total-vs-mean-proxy"></a>
</h2>
<p>This is the section to read slowly. We take <strong>one</strong> site and <strong>one</strong> ring from the fixtures, look at the weights the package builds, and then watch a count and an average go through their two different aggregation paths — so the abstract <span class="math inline">w^{cov}</span>-vs-<span class="math inline">w^{mean}</span> distinction lands as real numbers. The same contract scales to many sites and drive times.</p>
<p>We use the synthetic site <code>AL_SITE_03</code> at a 15-minute drive time, whose catchment intersects three tracts. First, intersect and keep the per-tract audit so we can see the geometry ingredients:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># These fixtures are exactly the shapes stages 1-2 would have returned, frozen.</span></span>
<span><span class="va">sites</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_sites.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">iso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_isochrones.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">acs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"sample_alabama_subset.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">site_id</span>    <span class="op">&lt;-</span> <span class="st">"AL_SITE_03"</span></span>
<span><span class="va">drive_time</span> <span class="op">&lt;-</span> <span class="fl">15L</span></span>
<span></span>
<span><span class="va">iso_one</span> <span class="op">&lt;-</span> <span class="va">iso</span><span class="op">[</span></span>
<span>  <span class="va">iso</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">site_id</span> <span class="op">&amp;</span> <span class="va">iso</span><span class="op">$</span><span class="va">drive_time_min</span> <span class="op">==</span> <span class="va">drive_time</span>, ,</span>
<span>  drop <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">]</span></span>
<span></span>
<span><span class="va">weighted</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight</a></span><span class="op">(</span></span>
<span>  iso_sf           <span class="op">=</span> <span class="va">iso_one</span>,</span>
<span>  acs_sf           <span class="op">=</span> <span class="va">acs</span>,</span>
<span>  weight_method    <span class="op">=</span> <span class="st">"area"</span>,</span>
<span>  keep_tract_audit <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  verbose          <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span></code></pre></div>
</div>
<p>The tract audit holds, for each tract the catchment touched, the intersection area and the tract area. From those two columns the package forms both weights. Computing them side by side makes the difference concrete:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">audit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted</span>, <span class="st">"cacs_tract_audit"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html" class="external-link">transmute</a></span><span class="op">(</span></span>
<span>    <span class="va">GEOID</span>,</span>
<span>    <span class="va">int_area_m2</span>,</span>
<span>    <span class="va">tract_area_m2</span>,</span>
<span>    w_cov  <span class="op">=</span> <span class="va">int_area_m2</span> <span class="op">/</span> <span class="va">tract_area_m2</span>,            <span class="co"># coverage weight</span></span>
<span>    w_mean <span class="op">=</span> <span class="va">int_area_m2</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">int_area_m2</span><span class="op">)</span>          <span class="co"># normalized mean weight</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html" class="external-link">desc</a></span><span class="op">(</span><span class="va">int_area_m2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">audit</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  GEOID       int_area_m2 tract_area_m2 w_cov w_mean
  &lt;chr&gt;             &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 01001000201    9543830.      9543830.  1.00  0.333
2 01133000101    9543830.      9543830.  1.00  0.333
3 01003000201    9543830.      9543830.  1.00  0.333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  sum_w_cov  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">audit</span><span class="op">$</span><span class="va">w_cov</span><span class="op">)</span>,    <span class="co"># NOT constrained to 1</span></span>
<span>  sum_w_mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">audit</span><span class="op">$</span><span class="va">w_mean</span><span class="op">)</span>    <span class="co"># constrained to 1 by construction</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sum_w_cov sum_w_mean
         3          1 </code></pre>
</div>
</div>
<p>Read the two sums. The coverage weights <span class="math inline">w^{cov}_{sj}</span> each measure <em>how much of that tract</em> the catchment captured, so they do <strong>not</strong> sum to one — here they sum to the effective number of tract-equivalents the catchment covers. The mean weights <span class="math inline">w^{mean}_{sj}</span> are renormalized to sum to exactly one. That single structural difference is what separates a <em>total</em> from an <em>average</em>.</p>
<p>Now send a count through the coverage path. <em>Persons in poverty</em> (<code>B17001_002</code>) is a <code>spatial_total</code>, so the package reports <span class="math inline">\widehat{Y}_s = \sum_j w^{cov}_{sj}\,Y_j</span> with <code>weight_basis = "coverage"</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">weighted</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">==</span> <span class="st">"B17001_002"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span>, <span class="va">weight_sum</span>, <span class="va">n_tracts</span>,</span>
<span>         <span class="va">estimand_family</span>, <span class="va">weight_basis</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  variable   estimate   moe weight_sum n_tracts estimand_family weight_basis
  &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;int&gt; &lt;chr&gt;           &lt;chr&gt;
1 B17001_002     2165  179.          3        3 spatial_total   coverage    </code></pre>
</div>
</div>
<p>The <code>weight_sum</code> column is exactly <span class="math inline">\sum_j w^{cov}_{sj}</span> — the same not-equal-to-one sum from the audit — and <code>estimate</code> is the coverage-weighted count of people in poverty across the three partial tracts. That is a total: it scales with how much area the catchment captures.</p>
<p>Now send an <em>average</em> through. <em>Per-capita income</em> (<code>B19301_001</code>) is an <code>area_weighted_scalar_proxy</code>: an intensive, per-person quantity that must be <em>blended</em>, not summed. Its estimator is the normalized-mean-weighted average <span class="math display">\widehat{\bar X}_s = \sum_j w^{mean}_{sj}\,X_j,</span> whose weights sum to one within a site and drive-time cell, so the result stays on the per-person scale and lies between the contributing tracts’ own values. (For the implementation see <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>; for the full derivation see <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code>.)</p>
<p>The teaching moment is what happens if you ignore the family and aggregate this intensive variable <em>as if it were a count</em>. Below we pull the three tracts’ published per-capita incomes and apply <strong>both</strong> weights by hand, so the contrast is self-contained and exact:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pc_income</span> <span class="op">&lt;-</span> <span class="va">acs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html" class="external-link">st_drop_geometry</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">GEOID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="va">audit</span><span class="op">$</span><span class="va">GEOID</span>, <span class="va">variable</span> <span class="op">==</span> <span class="st">"B19301_001"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span>, X <span class="op">=</span> <span class="va">estimate</span><span class="op">)</span></span>
<span></span>
<span><span class="va">demo</span> <span class="op">&lt;-</span> <span class="va">audit</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span>, <span class="va">w_cov</span>, <span class="va">w_mean</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">pc_income</span>, by <span class="op">=</span> <span class="st">"GEOID"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">demo</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  GEOID       w_cov w_mean     X
  &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 01001000201  1.00  0.333 22934
2 01133000101  1.00  0.333 20006
3 01003000201  1.00  0.333 37229</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  coverage_weighted_SUM <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">demo</span><span class="op">$</span><span class="va">w_cov</span>  <span class="op">*</span> <span class="va">demo</span><span class="op">$</span><span class="va">X</span><span class="op">)</span>,   <span class="co"># wrong estimand for an average</span></span>
<span>  mean_weighted_PROXY   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">demo</span><span class="op">$</span><span class="va">w_mean</span> <span class="op">*</span> <span class="va">demo</span><span class="op">$</span><span class="va">X</span><span class="op">)</span>    <span class="co"># correct: stays on the $/person scale</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>coverage_weighted_SUM   mean_weighted_PROXY
                80169                 26723 </code></pre>
</div>
</div>
<p>The two numbers tell the whole story. The <strong>coverage-weighted sum</strong> is <code>80169</code> — a dollar amount inflated past any single tract’s value, because summing an intensive quantity is meaningless. It is not an income anyone earns. The <strong>mean-weighted proxy</strong> is <code>26723</code>, which stays on the per-person scale, between the tracts’ own values, which is what a catchment “average per-capita income” should be. Both used identical geometry; only the <em>family-appropriate weight</em> differs. This is the silent estimand error the family classifier exists to prevent, and it is why <code>catchmentACS</code> refuses to apply one weight to everything.</p>
<p>The MOE column moved with the estimate in both family rows above. How it is computed is the subject of the next section, in brief.</p>
</section><section class="level2"><h2 id="margins-of-error-in-brief">Margins of error in brief<a class="anchor" aria-label="anchor" href="#margins-of-error-in-brief"></a>
</h2>
<p>ACS estimates ship with a published 90% margin of error, and that uncertainty must travel through the aggregation. <code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code> attaches an MOE to every row by dispatching on the estimand family. There are <strong>four</strong> MOE formula families; this article only names them and states the conversion.</p>
<ul>
<li>
<strong>Family A — weighted sum</strong> (for <code>spatial_total</code>): the root-sum-square of the coverage-weighted component MOEs.</li>
<li>
<strong>Family B — weighted mean</strong> (for the <code>*_scalar_proxy</code> and <code>median_proxy</code> families): the same root-sum-square form with the normalized mean weights, which sum to one and are treated as fixed.</li>
<li>
<strong>Family C1 — proportion subset</strong> (for a <code>derived_rate</code> whose numerator <span class="math inline">A</span> is a true subset of its denominator <span class="math inline">B</span>): the cross term is <em>subtracted</em>.</li>
<li>
<strong>Family C2 — general ratio, conservative</strong> (the package’s default for the curated derived rates): the cross term is <em>added</em>, so the variance is always non-negative.</li>
</ul>
<p>All four sit on the same conversion, <span class="math inline">M = 1.645\, SE</span>: each component MOE is divided by <span class="math inline">1.645</span> to a variance, the variances are combined, and the result is multiplied back by <span class="math inline">1.645</span>.</p>
<p>The one branch worth flagging here is the <strong>C1 → C2 fallback</strong>, and that it is never silent. When a Family C1 (<code>proportion_subset</code>) calculation yields a negative subset variance, the row is recomputed with the Family C2 (<code>general_ratio_conservative</code>) formula so a value is still produced, and the override is recorded per row: <code>moe_formula_effective</code> becomes <code>"general_ratio_conservative"</code>, <code>moe_fallback</code> is set to <code>TRUE</code>, and <code>moe_fallback_reason</code> records the cause. A single summary warning reports the counts at the end of a run.</p>
<p>We do <strong>not</strong> derive these formulas here — including why variances accumulate on the SE scale and why the conservative ratio is the default. The full Family A/B/C1/C2 algebra, the independence assumptions, and the numerical guards live in <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code>.</p>
</section><section class="level2"><h2 id="projection-and-the-within-tract-assumption">Projection and the within-tract assumption<a class="anchor" aria-label="anchor" href="#projection-and-the-within-tract-assumption"></a>
</h2>
<p>Two modeling choices underpin every number above.</p>
<p><strong>Equal-area measurement on EPSG:5070.</strong> The coverage weight <span class="math inline">w^{cov}_{sj} = \lvert I_s \cap T_j \rvert / \lvert T_j \rvert</span> is a ratio of two areas, so it is only meaningful if numerator and denominator are measured in the <em>same</em> equal-area metric. The package transforms validated inputs to <strong>EPSG:5070 (NAD83 / CONUS Albers Equal Area)</strong> once before measuring any area, so equal physical areas carry equal weight regardless of where in the catchment they fall. This is also why the current release is scoped to the contiguous United States plus DC, where Albers distortion is negligible.</p>
<p><strong>Uniform-within-tract allocation.</strong> Area weighting assumes the ACS characteristic is spread <em>uniformly</em> over each tract: a catchment that covers 30% of a tract’s area is credited with 30% of its count. This is exact for area but only approximate for people, and it is the standard areal-interpolation assumption that a future <code>weight_method = "population"</code> mode is designed to relax.</p>
<p>Both are stated only briefly here; the equal-area rationale and the uniform-within-tract assumption are argued in full in <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code>.</p>
</section><section class="level2"><h2 id="where-the-details-live">Where the details live<a class="anchor" aria-label="anchor" href="#where-the-details-live"></a>
</h2>
<p>This article is the map; the derivations are in the three method-track articles and the function reference, each reusing the notation fixed above.</p>
<ul>
<li>
<strong>Spatial aggregation</strong> — the coverage vs mean weight derivation, the per-site intersection algorithm, the full six-family aggregation table, EPSG:5070, and the within-tract assumption: <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>.</li>
<li>
<strong>MOE propagation</strong> — the four formula families (A weighted sum, B weighted mean, C1 proportion subset, C2 conservative general ratio), the SE ↔︎ MOE relation, the never-silent C1 → C2 fallback, and the numerical guards: <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code>.</li>
<li>
<strong>Derived rates</strong> — the five curated rates, their ACS numerator/denominator pairs, the baseline C1/C2 policy, and the carrier-lookup mechanics: <code><a href="../articles/theory-derived-rates.html">vignette("theory-derived-rates", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_derive_rates.html">?cacs_derive_rates</a></code>.</li>
</ul>
<p>For the record, each of the five curated rates maps to a fixed ACS numerator and denominator. <code>ssi_rate</code> is <code>B19056_002 / B19056_001</code> — households with Supplemental Security Income over the <code>B19056</code> household universe — and under the package’s baseline policy <code>poverty_rate</code> and <code>labor_force_participation</code> are C1-eligible (<code>proportion_subset</code>), while <code>snap_rate</code>, <code>ssi_rate</code>, and <code>unemp_rate</code> route to C2 (<code>general_ratio_conservative</code>). The full catalogue and dispatch rationale are in <code><a href="../articles/theory-derived-rates.html">vignette("theory-derived-rates", package = "catchmentACS")</a></code>.</p>
<p>For the applied, run-it path that produces reporting tables from these same fixtures, see <code><a href="../articles/getting-started.html">vignette("getting-started", package = "catchmentACS")</a></code>, <code><a href="../articles/alabama-tutorial.html">vignette("alabama-tutorial", package = "catchmentACS")</a></code>, and <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>.</p>
</section><section class="level2"><h2 id="limitations">Limitations<a class="anchor" aria-label="anchor" href="#limitations"></a>
</h2>
<p>The estimator’s scope is deliberately narrow in this release.</p>
<ul>
<li>
<strong>Area weighting only.</strong> <code>weight_method = "area"</code> is implemented; the population-weighted scalar-proxy family and <code>weight_method = "population"</code> are a reserved fail-loud future surface. The uniform-within-tract assumption is exact for area, approximate for population.</li>
<li>
<strong>Median is a proxy.</strong> A <code>median_proxy</code> value is a weighted blend of tract medians, not the true median of the pooled catchment population; it is labelled as a proxy throughout.</li>
<li>
<strong>Conservative ratio MOE by default.</strong> Derived-rate MOEs default to the Family C2 general-ratio form; the tighter C1 subset form is opt-in for the C1-eligible rates and falls back to C2 (never silently) when its variance goes negative.</li>
<li>
<strong>A fixed rate catalogue.</strong> The five curated rates are locked; arbitrary user-supplied ratios are deferred to a future release.</li>
<li>
<strong>CONUS + DC.</strong> EPSG:5070 is the authoritative equal-area default for the contiguous United States and DC; the data path is ACS 5-year tract data for one state at a time, and other regions await a future CRS policy.</li>
<li>
<strong>Fixtures.</strong> The bundled fixtures are synthetic and regression-oriented — useful for examples and package checks, not a substitute for a fresh live run when producing final analysis.</li>
</ul>
<p>The interpretive caution that frames all of the above: an isochrone’s polygon area is provider- and snapshot-sensitive, so for policy reporting the tract membership, the weighted estimates, their margins of error, and the recorded provenance are more informative audit surfaces than raw polygon area alone. And, as the callout at the top stresses, the fixtures used here are synthetic — the numbers above illustrate the <em>method</em>, not Alabama.</p>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="https://github.com/joonho112" class="external-link">JoonHo Lee</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
