<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Derived rates: definitions and ratio MOEs • catchmentACS</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="image/svg+xml" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<!-- katex math --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script><script src="../katex-auto.js"></script><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="theory-derived-rates_files/libs/quarto-html/popper.min.js"></script><script src="theory-derived-rates_files/libs/quarto-html/tippy.umd.min.js"></script><link href="theory-derived-rates_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="theory-derived-rates_files/libs/quarto-html/light-border.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Derived rates: definitions and ratio MOEs">
<meta property="og:image" content="https://joonho112.github.io/catchmentACS/logo.svg">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">catchmentACS</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.5.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-vignettes" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Vignettes</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-vignettes">
<li><h6 class="dropdown-header" data-toc-skip>--- Applied Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/getting-started.html">Getting started</a></li>
    <li><a class="dropdown-item" href="../articles/alabama-tutorial.html">Alabama tutorial</a></li>
    <li><a class="dropdown-item" href="../articles/providers.html">Providers</a></li>
    <li><a class="dropdown-item" href="../articles/visual-walkthrough.html">Visual walkthrough</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Method Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/methodology.html">Methodology</a></li>
    <li><a class="dropdown-item" href="../articles/theory-spatial-aggregation.html">Spatial aggregation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-moe-propagation.html">MOE propagation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-derived-rates.html">Derived rates</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Migration ---</h6></li>
    <li><a class="dropdown-item" href="../articles/porting-v01-to-v03.html">Porting from v0.1 to v0.3</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v03-to-v04.html">Porting from v0.3 to v0.4</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v04-to-v05.html">Porting from v0.4 to v0.5</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/joonho112/catchmentACS/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.svg" class="logo" alt=""><h1>Derived rates: definitions and ratio MOEs</h1>




      <small class="dont-index">Source: <a href="https://github.com/joonho112/catchmentACS/blob/HEAD/vignettes/theory-derived-rates.qmd" class="external-link"><code>vignettes/theory-derived-rates.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/joonho112/catchmentACS" class="external-link">catchmentACS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/" class="external-link">sf</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Force network-free, deterministic builds: no provider/Census calls, no cache.</span></span>
<span><span class="va">old_options</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span></span>
<span>  catchmentACS.progress <span class="op">=</span> <span class="st">"off"</span>,</span>
<span>  catchmentACS.rate_first_default <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span><span class="va">old_cache</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">getOption</a></span><span class="op">(</span><span class="st">"catchmentACS.cache_enabled"</span>, <span class="cn">NULL</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="va">old_options</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span>catchmentACS.cache_enabled <span class="op">=</span> <span class="va">old_cache</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/cacs_set_cache.html">cacs_set_cache</a></span><span class="op">(</span><span class="cn">FALSE</span>, scope <span class="op">=</span> <span class="st">"session"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>This article is the <strong>method-track</strong> companion to <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code> that fixes the <em>rates</em> layer of the estimator — the last of the three theory articles. The overview <em>states</em> that a derived rate is a ratio of two coverage-weighted totals and that some rates route to a tighter margin formula than others; this article makes the catalogue precise — the five sanctioned rates, their fixed ACS numerator and denominator codes, and the baseline policy that decides which margin-of-error (MOE) formula each one uses — and then does the thing the overview cannot: it <strong>reproduces a derived rate and its full MOE routing by hand</strong>, on a bundled fixture, so a methodologist can confirm that the rates the package reports are the ratios this page describes, computed by the formula this page assigns. The reference page <code><a href="../reference/cacs_derive_rates.html">?cacs_derive_rates</a></code> is the implementation anchor; this article supplies the rate catalogue and the routing logic behind its “Rate definitions” and <code>formula_dispatch</code> sections.</p>
<p>It is written for a methodologist or a reviewer who wants the rate model on the page: why a catchment rate is a <em>ratio of aggregates</em> rather than a weighted average of tract rates, which two of the five rates are eligible for the subset MOE formula and which three are not, why one rate whose numerator genuinely <em>is</em> a subset still routes to the conservative formula by policy, and exactly what the package records when the tighter formula is requested but its variance breaks down. We reuse the notation fixed in the overview without re-motivating it: the isochrone <span class="math inline">I_s</span>, the tract <span class="math inline">T_j</span>, the coverage weight <span class="math inline">w^{cov}_{sj}</span> (the fraction of tract <span class="math inline">T_j</span>’s area the catchment at site <span class="math inline">s</span> captured), and a rate’s tract-level numerator and denominator counts <span class="math inline">A_j, B_j</span>. The MOE algebra itself — the C1 subset formula, the C2 conservative formula, the <span class="math inline">M = 1.645\,SE</span> conversion, and the never-silent C1 → C2 fallback — is <strong>not</strong> re-derived here; it is the subject of <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code>, and this article <em>routes</em> rates into those formulas rather than restating them. The construction of <span class="math inline">w^{cov}_{sj}</span> is likewise derived in <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code>; this article takes both as given and concentrates on the rate definitions and the dispatch.</p>
<div>
<blockquote>
<p><strong>About the data in this article</strong></p>
<p>Every executable cell here is built entirely from the package’s bundled <code>inst/extdata</code> fixtures — the synthetic <code>legacy_2025_isochrones</code>, <code>legacy_2025_sites</code>, and <code>sample_alabama_subset</code> objects — so this article renders with <strong>no</strong> Census, OSRM, ORS, or other network calls. These fixtures preserve the production calling contract (sites, drive-time polygons, tract-level ACS variables) but are <strong>synthetic and illustrative</strong>: they are included only for examples, tests, and reproducible package checks. They are <strong>not</strong> live Alabama policy estimates and must not be cited as real ACS results. Any real analysis requires a fresh live run (see <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>).</p>
</blockquote>
</div>
<section class="level2"><h2 id="a-derived-rate-is-a-ratio-of-two-coverage-weighted-totals">A derived rate is a ratio of two coverage-weighted totals<a class="anchor" aria-label="anchor" href="#a-derived-rate-is-a-ratio-of-two-coverage-weighted-totals"></a>
</h2>
<p>A derived rate is not aggregated the way a count is. It is a <em>ratio</em> of two quantities, each of which is itself a coverage-weighted catchment total. By the time <code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code> runs, the spatial stage has already aggregated each ACS count to the catchment as a coverage-weighted total, and the MOE stage has attached a margin to each of those totals; a derived rate does <strong>not</strong> re-touch the geometry. It takes two of those already-aggregated totals — a numerator and a denominator — and divides. For a rate with tract-level numerator counts <span class="math inline">A_j</span> and denominator counts <span class="math inline">B_j</span>, the catchment rate at site <span class="math inline">s</span> is</p>
<p><span class="math display">
\widehat{R}_s
= \frac{\displaystyle\sum_j w^{cov}_{sj}\, A_j}{\displaystyle\sum_j w^{cov}_{sj}\, B_j}
= \frac{\widehat{A}_s}{\widehat{B}_s},
\qquad
\widehat{A}_s = \sum_j w^{cov}_{sj}\, A_j,
\quad
\widehat{B}_s = \sum_j w^{cov}_{sj}\, B_j,
</span></p>
<p>where <span class="math inline">\widehat{A}_s</span> and <span class="math inline">\widehat{B}_s</span> are exactly the Family-A spatial totals of the numerator and denominator ACS cells, each carrying the coverage weight <span class="math inline">w^{cov}_{sj}</span> derived in <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code>. The rate inherits the <em>coverage</em> path because both of its ingredients are extensive counts: half a tract contributes half its poor persons <strong>and</strong> half its population, and the halves cancel in the ratio only when each is allocated by the same area fraction.</p>
<p>The order of operations is the whole point, and it is the reason a rate is its own estimand family: the package <strong>aggregates the numerator and the denominator separately, each as its own <code>spatial_total</code>, and only then divides</strong>. It forms a ratio of two aggregates, <span class="math inline">(\sum_j w^{cov}_{sj} A_j) / (\sum_j w^{cov}_{sj} B_j)</span> — it does <strong>not</strong> form a per-tract rate <span class="math inline">A_j / B_j</span> and average those, <span class="math inline">\sum_j w_j (A_j / B_j)</span>. The two are not equal, and the ratio-of-aggregates form is the correct one: a tract that is barely clipped by the catchment should influence the catchment rate in proportion to how many of its people the catchment actually captures, which is what weighting the <em>counts</em> before dividing achieves. Averaging tract rates would instead give a sparsely-captured tract the same say as a fully-enclosed one, and would silently mis-estimate the catchment rate whenever the tracts differ in size or in their denominator. Aggregating two totals and dividing once is the areally correct estimator, and it is the same <span class="math inline">\widehat{R}_s</span> the overview lists for the <code>derived_rate</code> family.</p>
<p>Mechanically, this means both totals must survive intact until the division. The upstream stages preserve them: <code><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight()</a></code> accumulates each ACS code’s coverage-weighted total and its propagated variance into an attribute (the <em>aggregation carriers</em>), <code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code> carries that attribute forward while it computes per-variable margins, and <code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code> reads the numerator total <span class="math inline">\widehat{A}_s</span> and denominator total <span class="math inline">\widehat{B}_s</span> back out of it, divides to get the point estimate, and routes the <em>pair</em> of totals (with their variances) into a ratio-MOE formula. Because <span class="math inline">\widehat{A}_s</span> and <span class="math inline">\widehat{B}_s</span> are each random estimates carrying their own propagated variance, the rate’s MOE is a <em>ratio-variance</em> problem, and the package offers the two delta-method forms the Census Bureau’s handbook gives — the subset form (C1) and the conservative general-ratio form (C2). Which form a given rate uses is the subject of the routing policy below; the algebra of both forms is derived in <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code>. The “preserve both totals, then divide” rule is what makes the rate’s margin of error computable at all.</p>
</section><section class="level2"><h2 id="the-five-rate-catalogue">The five-rate catalogue<a class="anchor" aria-label="anchor" href="#the-five-rate-catalogue"></a>
</h2>
<p>The package computes exactly <strong>five</strong> curated rates. The set is fixed for this release: <code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code> accepts the rate list only if it is <em>identical</em> to the sanctioned catalogue, and any addition, deletion, or code substitution aborts. The catalogue is surfaced publicly as the package object <code>cacs_acs_default_rates</code> (see <code><a href="../reference/cacs_acs_default_rates.html">?cacs_acs_default_rates</a></code>) so the five <code>c(num, den)</code> pairs can be inspected without reaching into package internals. The motivation for the whitelist is reproducibility and auditability: a single frozen origin for every published rate, with the numerator/denominator pairing, the universe, and the subset relationship vetted once per rate rather than trusted from arbitrary user input. Arbitrary ratios are a separate, future surface (covered at the end of this article).</p>
<p>We read the catalogue straight off the shipped object so the table below is the catalogue the code uses, not a transcription of it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># The catalogue is a public object; each entry is a c(num, den) ACS-code pair.</span></span>
<span><span class="va">cacs_acs_default_rates</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$poverty_rate
         num          den
"B17001_002" "B17001_001"

$snap_rate
         num          den
"B22003_002" "B22003_001"

$ssi_rate
         num          den
"B19056_002" "B19056_001"

$unemp_rate
         num          den
"B23025_005" "B23025_003"

$labor_force_participation
         num          den
"B23025_002" "B23025_001" </code></pre>
</div>
</div>
<p>Each rate divides one ACS table cell (the numerator) by another (the denominator). The denominator is the rate’s <strong>universe</strong> — the population or household base the rate is “out of.” Reading the universe column is the quickest way to see what a rate actually measures, because a rate is only interpretable relative to its base.</p>
<table class="table caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead><tr class="header">
<th>Rate name</th>
<th>Numerator code</th>
<th>Denominator code</th>
<th>What it measures</th>
<th>Universe (denominator)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>poverty_rate</code></td>
<td><code>B17001_002</code></td>
<td><code>B17001_001</code></td>
<td>persons with income below the poverty level <span class="math inline">\div</span> persons for whom poverty status is determined</td>
<td>population for whom poverty status is determined (<code>B17001</code> total)</td>
</tr>
<tr class="even">
<td><code>snap_rate</code></td>
<td><code>B22003_002</code></td>
<td><code>B22003_001</code></td>
<td>households receiving SNAP / Food Stamps <span class="math inline">\div</span> all households</td>
<td>households (<code>B22003</code> total)</td>
</tr>
<tr class="odd">
<td><code>ssi_rate</code></td>
<td><code>B19056_002</code></td>
<td><code>B19056_001</code></td>
<td>households with Supplemental Security Income <span class="math inline">\div</span> all households</td>
<td>households (<code>B19056</code> total-household universe)</td>
</tr>
<tr class="even">
<td><code>unemp_rate</code></td>
<td><code>B23025_005</code></td>
<td><code>B23025_003</code></td>
<td>unemployed persons in the civilian labor force <span class="math inline">\div</span> civilian labor force</td>
<td>civilian labor force (<code>B23025_003</code>)</td>
</tr>
<tr class="odd">
<td><code>labor_force_participation</code></td>
<td><code>B23025_002</code></td>
<td><code>B23025_001</code></td>
<td>persons in the labor force <span class="math inline">\div</span> population 16 and over</td>
<td>population 16 years and over (<code>B23025_001</code>)</td>
</tr>
</tbody>
</table>
<p>Two features of this table do all the work in the next section. First, the <strong>universe</strong> column is not decoration: it is the denominator’s definition, and whether the numerator is a true subset <em>of that universe</em> is what determines MOE eligibility. Persons below poverty are a subset of the persons for whom poverty status is determined; persons in the labor force are a subset of the population 16 and over. Second, two rates (<code>unemp_rate</code>, <code>labor_force_participation</code>) share the <code>B23025</code> employment-status table but divide by <em>different</em> cells: the unemployment rate is out of the <strong>civilian labor force</strong> (<code>B23025_003</code>), while labor-force participation is out of the whole <strong>population 16 and over</strong> (<code>B23025_001</code>). They are different rates with different universes, and — as the next section shows — they are routed to different MOE formulas under the per-rate dispatch.</p>
</section><section class="level2"><h2 id="subset-structure-and-moe-routing">Subset structure and MOE routing<a class="anchor" aria-label="anchor" href="#subset-structure-and-moe-routing"></a>
</h2>
<p>Every rate above is a ratio, so its margin of error is a <em>ratio</em> margin — and the MOE companion derives that there are two ratio-variance formulas, differing by a single sign. This is the section to read slowly, because it is where a rate’s <em>definition</em> becomes a <em>formula choice</em>. We restate the two formulas only enough to name them as the routing target; the derivation, the guards, and the by-hand verification all live in <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code>.</p>
<ul>
<li>
<strong>Family C1 — <code>proportion_subset</code>.</strong> The Census Bureau’s proportion formula, which <em>subtracts</em> a cross term. It is valid <strong>only when the numerator <span class="math inline">\widehat{A}_s</span> is a true subset of the denominator <span class="math inline">\widehat{B}_s</span></strong> (every unit counted in the numerator is also counted in the denominator), because the subtraction credits the positive correlation a subset relationship guarantees. It is the <strong>tighter</strong> of the two estimates when it is valid; its fragility is that the subtracted bracket can go negative.</li>
<li>
<strong>Family C2 — <code>general_ratio_conservative</code>.</strong> The general-ratio formula, which <em>adds</em> the same cross term. It is valid for any ratio, is <strong>always non-negative</strong>, and is therefore the <strong>conservative</strong> (slightly wider) estimate. It is the package default.</li>
</ul>
<section class="level3"><h3 id="the-subset-relation-versus-the-routing-policy">The subset relation versus the routing policy<a class="anchor" aria-label="anchor" href="#the-subset-relation-versus-the-routing-policy"></a>
</h3>
<p>Whether a rate’s numerator is a mathematical <em>subset</em> of its denominator is a fact about ACS table structure. Whether the package <em>routes</em> that rate to the tighter C1 formula is a separate <strong>baseline policy</strong> decision. The two are not the same, and conflating them is the error this section exists to prevent. The package records the policy as a per-rate C1-eligibility flag and a per-rate default formula. The public table below mirrors that locked routing policy without requiring users to reach into unexported package internals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html" class="external-link">tibble</a></span><span class="op">(</span></span>
<span>  rate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"poverty_rate"</span>,</span>
<span>    <span class="st">"snap_rate"</span>,</span>
<span>    <span class="st">"ssi_rate"</span>,</span>
<span>    <span class="st">"unemp_rate"</span>,</span>
<span>    <span class="st">"labor_force_participation"</span></span>
<span>  <span class="op">)</span>,</span>
<span>  c1_eligible <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span>, <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>  default_formula <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"proportion_subset"</span>,</span>
<span>    <span class="st">"general_ratio_conservative"</span>,</span>
<span>    <span class="st">"general_ratio_conservative"</span>,</span>
<span>    <span class="st">"general_ratio_conservative"</span>,</span>
<span>    <span class="st">"proportion_subset"</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  rate                      c1_eligible default_formula
  &lt;chr&gt;                     &lt;lgl&gt;       &lt;chr&gt;
1 poverty_rate              TRUE        proportion_subset
2 snap_rate                 FALSE       general_ratio_conservative
3 ssi_rate                  FALSE       general_ratio_conservative
4 unemp_rate                FALSE       general_ratio_conservative
5 labor_force_participation TRUE        proportion_subset         </code></pre>
</div>
</div>
<p>Read the two columns together. The five rates fall into <strong>three</strong> routing classes, and it is worth naming each precisely because the middle one is easy to get wrong:</p>
<p><strong>C1-eligible (the subset proportions): <code>poverty_rate</code> and <code>labor_force_participation</code>.</strong> For both, the numerator is a textbook subset of the denominator’s universe — poor persons within the poverty-status universe, labor force within the 16-and-over population. These are the only two rates the package will compute with the tighter Family C1 formula, and they are the two whose <code>auto</code> default formula is <code>proportion_subset</code>.</p>
<p><strong>C2 by household structure: <code>snap_rate</code> and <code>ssi_rate</code>.</strong> Both are household rates — households receiving a benefit divided by all households. The package does not assert a subset <em>proportion</em> relationship for them at this baseline, so they route to the conservative Family C2 formula. Their numerator is genuinely a subset of “all households,” but the curated policy treats household-benefit rates as general ratios in this release; they are <strong>C2 by policy</strong>.</p>
<p><strong>Subset numerator, but C2 by policy: <code>unemp_rate</code>.</strong> This is the case to read carefully. The unemployment rate’s numerator, the unemployed (<code>B23025_005</code>), genuinely <strong>is</strong> a subset of its denominator, the civilian labor force (<code>B23025_003</code>) — every unemployed person is in the labor force. The subset relation holds. It is therefore <strong>not a “non-subset” rate</strong> — calling it that would misstate the ACS table structure. The baseline policy for this release nonetheless routes <code>unemp_rate</code> to the <strong>conservative</strong> Family C2 formula rather than to C1. So <code>unemp_rate</code> sits deliberately in its own class: <em>its numerator is a subset, but its baseline MOE formula is the conservative general ratio.</em> The correct description is “subset, but C2 by baseline policy,” <strong>not</strong> “non-subset.” A future-release transition of this rate to C1 is one of the package’s open questions, and the reference page flags it explicitly.</p>
</section><section class="level3"><h3 id="formula_dispatch-how-the-routing-is-selected">
<code>formula_dispatch</code>: how the routing is selected<a class="anchor" aria-label="anchor" href="#formula_dispatch-how-the-routing-is-selected"></a>
</h3>
<p><code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code> takes a <code>formula_dispatch</code> argument that selects how the five rates are assigned to formulas. It has three modes:</p>
<table class="table caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th><code>formula_dispatch</code></th>
<th>Effect on the five rates</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>
<code>"general_ratio_conservative"</code> <em>(default)</em>
</td>
<td>Broadcast Family C2 to <strong>every</strong> rate, including the two C1-eligible ones. Under it, no rate uses the subtracting formula, so no rate can produce a negative subset variance, and every published margin is the always-defined conservative one — the most conservative, fully reproducible setting.</td>
</tr>
<tr class="even">
<td><code>"proportion_subset"</code></td>
<td>Request Family C1 for the rates that are C1-eligible (<code>poverty_rate</code>, <code>labor_force_participation</code>); the three non-eligible rates (<code>snap_rate</code>, <code>ssi_rate</code>, <code>unemp_rate</code>) are <strong>downgraded to C2</strong> by policy, not silently — the downgrade is recorded in the run’s rate-provenance attribute.</td>
</tr>
<tr class="odd">
<td><code>"auto"</code></td>
<td>Per-rate dispatch from the catalogue: C1 for the two eligible rates, C2 for the other three. The “use each rate’s policy default” setting, and the mode that reproduces the catalogue’s intended formula for each rate in a single call.</td>
</tr>
</tbody>
</table>
<p>Note that <code>"proportion_subset"</code> and <code>"auto"</code> produce the <em>same</em> routing for the five curated rates, because the only rates <code>"proportion_subset"</code> upgrades to C1 are exactly the two the catalogue already marks C1 — and the three non-eligible rates are pinned to C2 under both. The difference between the two modes is in their <em>intent</em> for a future open catalogue, not in their effect on this release’s five rates.</p>
</section><section class="level3"><h3 id="the-c1-c2-fallback-routings-safety-valve">The C1 → C2 fallback (routing’s safety valve)<a class="anchor" aria-label="anchor" href="#the-c1-c2-fallback-routings-safety-valve"></a>
</h3>
<p>The dispatch above decides what each rate <em>requests</em>. Requesting C1 for an eligible rate is a <em>request</em>, not a guarantee, and there is one more layer below it — the reason C1 is safe to request at all. The Family C1 bracket <span class="math inline">\mathrm{Var}(A) - (A/B)^2\,\mathrm{Var}(B)</span> can come out <strong>negative</strong> on real aggregated inputs, in which case its square root is undefined. When that happens, the package does not emit a missing value or a silent C1 number: it <strong>recomputes that cell’s margin with the always-non-negative Family C2 formula</strong> and records the substitution on the row — <code>moe_formula_requested</code> stays <code>"proportion_subset"</code> (the request is preserved), <code>moe_formula_effective</code> becomes <code>"general_ratio_conservative"</code> (C2 produced the value), <code>moe_fallback</code> is set to <code>TRUE</code>, and <code>moe_fallback_reason</code> is <code>"negative_variance"</code>. The fallback is never silent, and a single end-of-run summary reports the counts.</p>
<p>We do <strong>not</strong> re-derive that fallback here — its mechanics, the status-column contract, and the other degenerate outcomes (zero denominator, missing input margin) are derived and verified in <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code> and documented in <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code>. What matters for <em>this</em> article is that the fallback is the reason a C1-eligible rate can still legitimately report a C2 margin: routing proposes C1, and the variance guard disposes. The numerical section below shows exactly this happening to one rate while a second C1-eligible rate stays on C1, in the same catchment.</p>
</section></section><section class="level2"><h2 id="ssi-rate-the-current-definition">SSI rate: the current definition<a class="anchor" aria-label="anchor" href="#ssi-rate-the-current-definition"></a>
</h2>
<p>The SSI rate deserves a one-line clarification because its universe is easy to misread. The current definition is</p>
<p><span class="math display">
\widehat{R}^{\text{ssi}}_s
= \frac{\widehat{A}_s\,(\texttt{B19056\_002})}{\widehat{B}_s\,(\texttt{B19056\_001})},
</span></p>
<p>that is, <strong>households with Supplemental Security Income (<code>B19056_002</code>) divided by the <code>B19056</code> total-household universe (<code>B19056_001</code>)</strong>. The base is <em>households</em>, not persons and not households-with-some-other-income — it is the full household count of the <code>B19056</code> table. We surface it explicitly only because the <code>B19056</code> table also publishes person-level and income-bracket cells that a reader might reach for; the curated catalogue fixes the household-over-household pairing so the rate’s universe is unambiguous. Because the numerator and denominator are household-defined cells rather than a person-level subset, the SSI rate routes to the conservative Family C2 formula by default (it is not C1-eligible). This is the definition the package computes for this release.</p>
</section><section class="level2"><h2 id="bivariate-tract-exposure-n_tracts_num-and-n_tracts_den">Bivariate tract exposure: <code>n_tracts_num</code> and <code>n_tracts_den</code>
<a class="anchor" aria-label="anchor" href="#bivariate-tract-exposure-n_tracts_num-and-n_tracts_den"></a>
</h2>
<p>A <code>spatial_total</code> row carries an <code>n_tracts</code> count — the number of tracts that contributed to that one aggregation. A rate row cannot use that single slot honestly, because a rate is built from <em>two</em> aggregations whose tract sets need not match. The numerator and denominator of a curated rate come from different ACS table cells, and the Census Bureau suppresses cells independently: a catchment can have a valid numerator contribution from a tract that has a suppressed denominator there, or the reverse. So a rate row carries <strong>two</strong> counts instead of one, populated independently:</p>
<ul>
<li>
<strong><code>n_tracts_num</code></strong> — the number of tracts that contributed a valid count to the rate’s <strong>numerator</strong> total <span class="math inline">\widehat{A}_s</span>.</li>
<li>
<strong><code>n_tracts_den</code></strong> — the number of tracts that contributed a valid count to the rate’s <strong>denominator</strong> total <span class="math inline">\widehat{B}_s</span>.</li>
</ul>
<p>These two counts are reported <strong>separately</strong> rather than collapsed to a single <code>min(num, den)</code> precisely so a reviewer can <em>see</em> an asymmetry directly. If <code>n_tracts_num</code> and <code>n_tracts_den</code> disagree for a rate, that is a visible signal that the numerator and denominator were aggregated over different tract sets — exactly the kind of suppression asymmetry that a collapsed count would hide.</p>
<p>The <code>n_tracts</code> column itself is <strong><code>NA_integer_</code> on every rate row</strong>. This is not a gap to be filled — it is the contract. <code>n_tracts</code> describes a single aggregation, and a rate is <em>derived</em> from two, not aggregated as one; the meaningful per-tract counts for a rate live in the two <code>_num</code> / <code>_den</code> slots, so the single slot is deliberately left empty. Symmetrically, every inherited <strong>source-variable</strong> row (the spatial totals and proxies passed through from the MOE stage) carries <code>n_tracts_num = NA_integer_</code> and <code>n_tracts_den = NA_integer_</code>, because those two columns are reserved for rates. In the carrier-missing edge case — when a rate’s numerator or denominator carrier is absent for a cell — both <code>_num</code> and <code>_den</code> collapse to <code>NA_integer_</code> as well, and the diagnostic surface for that condition is the row’s <code>failure_origin</code>, not the count columns. The full population contract is in the “Policy on n_tracts_num and n_tracts_den” section of <code><a href="../reference/cacs_derive_rates.html">?cacs_derive_rates</a></code>.</p>
</section><section class="level2"><h2 id="deferred-custom-and-multi-numerator-rates">Deferred: custom and multi-numerator rates<a class="anchor" aria-label="anchor" href="#deferred-custom-and-multi-numerator-rates"></a>
</h2>
<p>The five-rate catalogue is intentionally closed for this release, and two extensions are explicitly reserved for a future (v1.1) surface rather than smuggled into the current one.</p>
<ul>
<li>
<strong>Arbitrary user-supplied ratios</strong> are reserved for a separate function, <code>cacs_derive_rates_custom()</code>, that will accept user-defined numerator/ denominator pairs with an explicit per-rate formula assignment. Any ratio outside the five sanctioned pairs is rejected at the argument boundary today; keeping arbitrary ratios out of the curated path preserves the single-origin audit trail, so every rate the current function emits is one of the five vetted definitions.</li>
<li>
<strong>Multi-numerator rates</strong> — rates whose numerator is a <em>sum</em> of several ACS cells rather than a single cell — are also deferred. The canonical example is a true child poverty rate, which must sum several age-by-sex cells of the <code>B17001</code> table rather than divide a single cell. A single-cell shortcut for such a rate is a silent statistical error, so it is excluded from the curated catalogue rather than approximated.</li>
</ul>
<p>Both are noted here so a reader knows the current function’s scope is the <em>exact</em> five-rate catalogue, and that the path for anything beyond it already has a reserved home. The catalogue object carries this stability promise in its own documentation: see <code><a href="../reference/cacs_acs_default_rates.html">?cacs_acs_default_rates</a></code>.</p>
</section><section class="level2"><h2 id="numerical-verification-the-rates-match-the-package">Numerical verification: the rates match the package<a class="anchor" aria-label="anchor" href="#numerical-verification-the-rates-match-the-package"></a>
</h2>
<p>This is the section that earns a methodologist’s trust. We compute the five rates with the <em>real</em> pipeline on a bundled fixture, offline, and then do four things the prose above only asserts. We <strong>reproduce a C2 rate and its margin by hand</strong> and assert equality with the package to machine precision. We <strong>reproduce a C1-eligible rate whose subset formula succeeds</strong>, confirm its margin is the tighter subset value (not the conservative one), and match it by hand. On the same catchment we watch a <strong>second C1-eligible rate fall back to C2</strong> because its subset variance goes negative, and reproduce <em>that</em> margin by hand too. And we print the <strong><code>moe_formula_effective</code> for all five rates</strong> so the C1-vs-C2 routing is visible in one table. Finally we force the <strong>carrier-missing</strong> branch and show it surfaces as <code>failure_origin = "carrier"</code>, distinct from any MOE fallback. If the catalogue or the routing on this page were not the ones the code runs, one of these checks would fail.</p>
<p>We build the catchment from the fixtures with <code><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight()</a></code>, then run <code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code> and <code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code> — the exact pipeline path of a real run, on frozen inputs. We use the synthetic site <code>AL_SITE_03</code> at a 15-minute drive time, whose catchment intersects three tracts, because it happens to exercise all three routing outcomes at once:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># These fixtures are exactly the shapes pipeline stages 1-2 would have returned.</span></span>
<span><span class="va">iso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_isochrones.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">acs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"sample_alabama_subset.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">site_id</span>    <span class="op">&lt;-</span> <span class="st">"AL_SITE_03"</span></span>
<span><span class="va">drive_time</span> <span class="op">&lt;-</span> <span class="fl">15L</span></span>
<span></span>
<span><span class="va">iso_one</span> <span class="op">&lt;-</span> <span class="va">iso</span><span class="op">[</span></span>
<span>  <span class="va">iso</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">site_id</span> <span class="op">&amp;</span> <span class="va">iso</span><span class="op">$</span><span class="va">drive_time_min</span> <span class="op">==</span> <span class="va">drive_time</span>, ,</span>
<span>  drop <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">]</span></span>
<span></span>
<span><span class="co"># keep_tract_audit preserves the per-tract carriers we recompute the rate from.</span></span>
<span><span class="va">weighted</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight</a></span><span class="op">(</span></span>
<span>  iso_sf           <span class="op">=</span> <span class="va">iso_one</span>,</span>
<span>  acs_sf           <span class="op">=</span> <span class="va">acs</span>,</span>
<span>  weight_method    <span class="op">=</span> <span class="st">"area"</span>,</span>
<span>  keep_tract_audit <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  verbose          <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span><span class="va">propagated</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe</a></span><span class="op">(</span><span class="va">weighted</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># formula_dispatch = "auto" routes each rate to its catalogue default (C1 for</span></span>
<span><span class="co"># the two eligible rates, C2 for the other three).</span></span>
<span><span class="va">rates</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/warning.html" class="external-link">suppressWarnings</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="../reference/cacs_derive_rates.html">cacs_derive_rates</a></span><span class="op">(</span><span class="va">propagated</span>, formula_dispatch <span class="op">=</span> <span class="st">"auto"</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
</div>
<p>The numerator and denominator totals the rate divides are the <em>aggregation carriers</em> — the Family-A coverage totals <span class="math inline">\widehat{A}_s</span>, <span class="math inline">\widehat{B}_s</span> and their accumulated variances that <code><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight()</a></code> preserves as an attribute for exactly this purpose. We pull them so the by-hand checks read from the same numbers the package divides:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">z</span>    <span class="op">&lt;-</span> <span class="fl">1.645</span></span>
<span><span class="va">carr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted</span>, <span class="st">"cacs_aggregation_carriers"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># A tiny accessor: the coverage total and its accumulated variance for one cell.</span></span>
<span><span class="va">get</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">code</span>, <span class="va">col</span><span class="op">)</span> <span class="va">carr</span><span class="op">[[</span><span class="va">col</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="va">carr</span><span class="op">$</span><span class="va">variable</span> <span class="op">==</span> <span class="va">code</span><span class="op">]</span></span>
<span></span>
<span><span class="va">carr</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"B22003_002"</span>, <span class="st">"B22003_001"</span>,   <span class="co"># snap_rate  num / den</span></span>
<span>    <span class="st">"B23025_002"</span>, <span class="st">"B23025_001"</span>,   <span class="co"># labor_force_participation num / den</span></span>
<span>    <span class="st">"B17001_002"</span>, <span class="st">"B17001_001"</span>    <span class="co"># poverty_rate num / den</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">est_total</span>, <span class="va">var_total_raw</span>, <span class="va">weight_sum</span>, <span class="va">n_tracts</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  variable   est_total var_total_raw weight_sum n_tracts
  &lt;chr&gt;          &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;    &lt;int&gt;
1 B17001_001      8474       320617.          3        3
2 B17001_002      2165        11820.          3        3
3 B22003_001      3556        48137.          3        3
4 B22003_002       891         2533.          3        3
5 B23025_001      8136       208358.          3        3
6 B23025_002      4359        73889.          3        3</code></pre>
</div>
</div>
<section class="level3"><h3 id="check-1-a-c2-rate-by-hand-snap_rate">Check 1 — a C2 rate by hand (<code>snap_rate</code>)<a class="anchor" aria-label="anchor" href="#check-1-a-c2-rate-by-hand-snap_rate"></a>
</h3>
<p><code>snap_rate</code> is a household-benefit ratio, so it routes to Family C2 under every dispatch mode. Its point estimate is the ratio of the two coverage totals <span class="math inline">\widehat{R}_s = \widehat{A}_s / \widehat{B}_s</span>, and its margin is the C2 ratio form, recovered from the carriers’ accumulated variances <span class="math inline">\mathrm{Var}(A) = (M_A/z)^2</span> and <span class="math inline">\mathrm{Var}(B) = (M_B/z)^2</span> as <span class="math inline">M = z\sqrt{\mathrm{Var}(A) + (A/B)^2\,\mathrm{Var}(B)}\,/\,|B|</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">A_snap</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B22003_002"</span>, <span class="st">"est_total"</span><span class="op">)</span></span>
<span><span class="va">B_snap</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B22003_001"</span>, <span class="st">"est_total"</span><span class="op">)</span></span>
<span><span class="va">VarA_snap</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B22003_002"</span>, <span class="st">"var_total_raw"</span><span class="op">)</span></span>
<span><span class="va">VarB_snap</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B22003_001"</span>, <span class="st">"var_total_raw"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p_snap</span>        <span class="op">&lt;-</span> <span class="va">A_snap</span> <span class="op">/</span> <span class="va">B_snap</span>                                     <span class="co"># the ratio A / B</span></span>
<span><span class="va">hand_est_snap</span> <span class="op">&lt;-</span> <span class="va">p_snap</span></span>
<span><span class="va">hand_moe_snap</span> <span class="op">&lt;-</span> <span class="va">z</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">VarA_snap</span> <span class="op">+</span> <span class="va">p_snap</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB_snap</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">B_snap</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pkg_snap</span> <span class="op">&lt;-</span> <span class="va">rates</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">==</span> <span class="st">"snap_rate"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="va">moe</span>, <span class="va">moe_formula_effective</span>, <span class="va">moe_fallback</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span></span>
<span>  A <span class="op">=</span> <span class="va">A_snap</span>, B <span class="op">=</span> <span class="va">B_snap</span>,</span>
<span>  hand_estimate <span class="op">=</span> <span class="va">hand_est_snap</span>,</span>
<span>  hand_moe_C2   <span class="op">=</span> <span class="va">hand_moe_snap</span>,</span>
<span>  pkg           <span class="op">=</span> <span class="va">pkg_snap</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$A
[1] 891

$B
[1] 3556

$hand_estimate
[1] 0.2505624

$hand_moe_C2
[1] 0.0344782

$pkg
# A tibble: 1 × 4
  estimate    moe moe_formula_effective      moe_fallback
     &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;                      &lt;lgl&gt;
1    0.251 0.0345 general_ratio_conservative FALSE       </code></pre>
</div>
</div>
<p>Both reproduce exactly. The package routed <code>snap_rate</code> through <code>moe_formula_effective = "general_ratio_conservative"</code> with no fallback; its reported estimate (about <code>0.2506</code>) is the by-hand ratio <span class="math inline">A/B</span>, and its reported margin (about <code>0.0345</code>) is the by-hand C2 root:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  estimate_match <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">hand_est_snap</span>, <span class="va">pkg_snap</span><span class="op">$</span><span class="va">estimate</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  moe_match      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">hand_moe_snap</span>, <span class="va">pkg_snap</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  moe_abs_diff   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">hand_moe_snap</span> <span class="op">-</span> <span class="va">pkg_snap</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>estimate_match      moe_match   moe_abs_diff
             1              1              0 </code></pre>
</div>
</div>
<p>The rate on this page and the rate in the code are the same arithmetic.</p>
</section><section class="level3"><h3 id="check-2-a-c1-eligible-rate-whose-subset-formula-succeeds-labor_force_participation">Check 2 — a C1-eligible rate whose subset formula succeeds (<code>labor_force_participation</code>)<a class="anchor" aria-label="anchor" href="#check-2-a-c1-eligible-rate-whose-subset-formula-succeeds-labor_force_participation"></a>
</h3>
<p><code>labor_force_participation</code> is C1-eligible (labor force <span class="math inline">\subseteq</span> population 16+), so under <code>auto</code> it is computed with the <strong>tighter</strong> Family C1 formula <span class="math inline">M = z\sqrt{\mathrm{Var}(A) - (A/B)^2\,\mathrm{Var}(B)}\,/\,|B|</span> — <em>provided the bracket stays non-negative.</em> We compute the bracket by hand, confirm it is positive, and form the C1 margin:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">A_lfp</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B23025_002"</span>, <span class="st">"est_total"</span><span class="op">)</span></span>
<span><span class="va">B_lfp</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B23025_001"</span>, <span class="st">"est_total"</span><span class="op">)</span></span>
<span><span class="va">VarA_lfp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B23025_002"</span>, <span class="st">"var_total_raw"</span><span class="op">)</span></span>
<span><span class="va">VarB_lfp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B23025_001"</span>, <span class="st">"var_total_raw"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p_lfp</span>       <span class="op">&lt;-</span> <span class="va">A_lfp</span> <span class="op">/</span> <span class="va">B_lfp</span></span>
<span><span class="va">inside_C1</span>   <span class="op">&lt;-</span> <span class="va">VarA_lfp</span> <span class="op">-</span> <span class="va">p_lfp</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB_lfp</span>           <span class="co"># C1 bracket; must be &gt;= 0</span></span>
<span><span class="va">hand_moe_C1</span> <span class="op">&lt;-</span> <span class="va">z</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">inside_C1</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">B_lfp</span><span class="op">)</span></span>
<span><span class="va">hand_moe_C2</span> <span class="op">&lt;-</span> <span class="va">z</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">VarA_lfp</span> <span class="op">+</span> <span class="va">p_lfp</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB_lfp</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">B_lfp</span><span class="op">)</span>  <span class="co"># for contrast</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span></span>
<span>  C1_inside_bracket <span class="op">=</span> <span class="va">inside_C1</span>,          <span class="co"># &gt; 0, so C1 is admissible</span></span>
<span>  hand_moe_C1       <span class="op">=</span> <span class="va">hand_moe_C1</span>,</span>
<span>  hand_moe_C2       <span class="op">=</span> <span class="va">hand_moe_C2</span>          <span class="co"># the wider value C1 avoids</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$C1_inside_bracket
[1] 14080.91

$hand_moe_C1
[1] 0.02399222

$hand_moe_C2
[1] 0.07392929</code></pre>
</div>
</div>
<p>The bracket is positive, so C1 is admissible, and the C1 margin (about <code>0.0240</code>) is markedly <strong>tighter</strong> than the conservative C2 value (about <code>0.0739</code>) on the identical inputs — that gap is exactly the cross term C1 credits and C2 does not. The package agrees, and reports <code>proportion_subset</code> with no fallback:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pkg_lfp</span> <span class="op">&lt;-</span> <span class="va">rates</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">==</span> <span class="st">"labor_force_participation"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="va">moe</span>, <span class="va">moe_formula_effective</span>, <span class="va">moe_fallback</span>, <span class="va">moe_fallback_reason</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pkg_lfp</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  estimate    moe moe_formula_effective moe_fallback moe_fallback_reason
     &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;                 &lt;lgl&gt;        &lt;chr&gt;
1    0.536 0.0240 proportion_subset     FALSE        n/a                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  moe_match   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">hand_moe_C1</span>, <span class="va">pkg_lfp</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  is_C1       <span class="op">=</span> <span class="va">pkg_lfp</span><span class="op">$</span><span class="va">moe_formula_effective</span> <span class="op">==</span> <span class="st">"proportion_subset"</span>,</span>
<span>  no_fallback <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="op">!</span><span class="va">pkg_lfp</span><span class="op">$</span><span class="va">moe_fallback</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  moe_match       is_C1 no_fallback
       TRUE        TRUE        TRUE </code></pre>
</div>
</div>
<p>The package’s margin equals the hand-computed <strong>subset</strong> root, its effective formula is <code>proportion_subset</code>, and it did not fall back. The tighter formula was requested, was admissible, and was used.</p>
</section><section class="level3"><h3 id="check-3-a-c1-eligible-rate-that-falls-back-to-c2-poverty_rate">Check 3 — a C1-eligible rate that falls back to C2 (<code>poverty_rate</code>)<a class="anchor" aria-label="anchor" href="#check-3-a-c1-eligible-rate-that-falls-back-to-c2-poverty_rate"></a>
</h3>
<p>On this <em>same</em> catchment, the other C1-eligible rate behaves differently, and that is the point of choosing it. <code>poverty_rate</code>’s numerator is <em>persons in poverty</em> (<code>B17001_002</code>) and its denominator is <em>persons for whom poverty status is determined</em> (<code>B17001_001</code>); the numerator is a true subset of the denominator, so it is also requested as <code>proportion_subset</code> under <code>auto</code>. But its C1 bracket comes out <strong>negative</strong>, so the subset formula is inadmissible and the package falls back to C2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">A_pov</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B17001_002"</span>, <span class="st">"est_total"</span><span class="op">)</span></span>
<span><span class="va">B_pov</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B17001_001"</span>, <span class="st">"est_total"</span><span class="op">)</span></span>
<span><span class="va">VarA_pov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B17001_002"</span>, <span class="st">"var_total_raw"</span><span class="op">)</span></span>
<span><span class="va">VarB_pov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html" class="external-link">get</a></span><span class="op">(</span><span class="st">"B17001_001"</span>, <span class="st">"var_total_raw"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p_pov</span>       <span class="op">&lt;-</span> <span class="va">A_pov</span> <span class="op">/</span> <span class="va">B_pov</span></span>
<span><span class="va">inside_C1</span>   <span class="op">&lt;-</span> <span class="va">VarA_pov</span> <span class="op">-</span> <span class="va">p_pov</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB_pov</span>           <span class="co"># C1 bracket; &lt; 0 here</span></span>
<span><span class="va">hand_moe_C2</span> <span class="op">&lt;-</span> <span class="va">z</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">VarA_pov</span> <span class="op">+</span> <span class="va">p_pov</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB_pov</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">B_pov</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span></span>
<span>  C1_inside_bracket <span class="op">=</span> <span class="va">inside_C1</span>,    <span class="co"># &lt; 0, so C1 is inadmissible -&gt; fall back</span></span>
<span>  hand_moe_C2       <span class="op">=</span> <span class="va">hand_moe_C2</span>   <span class="co"># the value the fallback should report</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$C1_inside_bracket
[1] -9107.609

$hand_moe_C2
[1] 0.03512943</code></pre>
</div>
</div>
<p>The bracket is negative, so C1 cannot produce a real margin and the routing’s safety valve fires. The package records the substitution exactly as the never-silent contract requires, and the reported margin is the <strong>C2</strong> root, not a missing value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pkg_pov</span> <span class="op">&lt;-</span> <span class="va">rates</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">==</span> <span class="st">"poverty_rate"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="va">moe</span>,</span>
<span>         <span class="va">moe_formula_requested</span>, <span class="va">moe_formula_effective</span>,</span>
<span>         <span class="va">moe_fallback</span>, <span class="va">moe_fallback_reason</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pkg_pov</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  estimate    moe moe_formula_requested moe_formula_effective      moe_fallback
     &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;                 &lt;chr&gt;                      &lt;lgl&gt;
1    0.255 0.0351 proportion_subset     general_ratio_conservative TRUE
# ℹ 1 more variable: moe_fallback_reason &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  moe_match        <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">hand_moe_C2</span>, <span class="va">pkg_pov</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  requested_is_C1  <span class="op">=</span> <span class="va">pkg_pov</span><span class="op">$</span><span class="va">moe_formula_requested</span> <span class="op">==</span> <span class="st">"proportion_subset"</span>,</span>
<span>  effective_is_C2  <span class="op">=</span> <span class="va">pkg_pov</span><span class="op">$</span><span class="va">moe_formula_effective</span> <span class="op">==</span> <span class="st">"general_ratio_conservative"</span>,</span>
<span>  fallback_flagged <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="va">pkg_pov</span><span class="op">$</span><span class="va">moe_fallback</span><span class="op">)</span>,</span>
<span>  reason_recorded  <span class="op">=</span> <span class="va">pkg_pov</span><span class="op">$</span><span class="va">moe_fallback_reason</span> <span class="op">==</span> <span class="st">"negative_variance"</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       moe_match  requested_is_C1  effective_is_C2 fallback_flagged
            TRUE             TRUE             TRUE             TRUE
 reason_recorded
            TRUE </code></pre>
</div>
</div>
<p>Every flag lands: the row asked for <code>proportion_subset</code>, its subset variance went negative, and the conservative formula produced the value, with <code>moe_fallback = TRUE</code> and <code>moe_fallback_reason = "negative_variance"</code> recorded so the path is auditable. The fallback margin reproduces the hand-computed C2 root exactly. Two C1-eligible rates, the same catchment, opposite outcomes — and both fully recorded.</p>
</section><section class="level3"><h3 id="the-routing-made-visible-moe_formula_effective-across-all-five-rates">The routing made visible: <code>moe_formula_effective</code> across all five rates<a class="anchor" aria-label="anchor" href="#the-routing-made-visible-moe_formula_effective-across-all-five-rates"></a>
</h3>
<p>Finally, the single table the whole routing section describes — every rate, its requested formula, the formula whose value was actually written, and the bivariate tract exposure on each rate row:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rates</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">estimand_family</span> <span class="op">==</span> <span class="st">"derived_rate"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span>,</span>
<span>         <span class="va">moe_formula_requested</span>, <span class="va">moe_formula_effective</span>,</span>
<span>         <span class="va">moe_fallback</span>, <span class="va">moe_fallback_reason</span>,</span>
<span>         <span class="va">n_tracts</span>, <span class="va">n_tracts_num</span>, <span class="va">n_tracts_den</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 10
  variable          estimate     moe moe_formula_requested moe_formula_effective
  &lt;chr&gt;                &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                 &lt;chr&gt;
1 poverty_rate        0.255  0.0351  proportion_subset     general_ratio_conser…
2 snap_rate           0.251  0.0345  general_ratio_conser… general_ratio_conser…
3 ssi_rate            0.0852 0.0113  general_ratio_conser… general_ratio_conser…
4 unemp_rate          0.0664 0.00838 general_ratio_conser… general_ratio_conser…
5 labor_force_part…   0.536  0.0240  proportion_subset     proportion_subset
# ℹ 5 more variables: moe_fallback &lt;lgl&gt;, moe_fallback_reason &lt;chr&gt;,
#   n_tracts &lt;int&gt;, n_tracts_num &lt;int&gt;, n_tracts_den &lt;int&gt;</code></pre>
</div>
</div>
<p>Read the <code>moe_formula_effective</code> column straight down. <code>snap_rate</code>, <code>ssi_rate</code>, and <code>unemp_rate</code> are <code>general_ratio_conservative</code> — the three C2 rates, exactly as the policy assigns (<code>unemp_rate</code> among them, its subset numerator notwithstanding). <code>labor_force_participation</code> is <code>proportion_subset</code> — a C1-eligible rate whose subset formula was admissible. And <code>poverty_rate</code> reads <code>general_ratio_conservative</code> with <code>moe_fallback = TRUE</code> — a C1-eligible rate that fell back. The bivariate exposure is visible too: every rate row carries <code>n_tracts = NA</code> while <code>n_tracts_num</code> and <code>n_tracts_den</code> hold the per-side tract counts.</p>
</section><section class="level3"><h3 id="carrier-missing-routing">Carrier-missing routing<a class="anchor" aria-label="anchor" href="#carrier-missing-routing"></a>
</h3>
<p>One last routing outcome is not a formula choice at all: a rate whose numerator or denominator <strong>carrier is absent</strong> for a cell cannot be computed, and the package records that as an <em>upstream carrier failure</em>, distinct from any MOE fallback. The default ACS catalogue supplies every carrier the five rates need, so this arises only in direct pipelines that drop a variable. We force it by removing the SSI numerator cell <code>B19056_002</code> from the ACS extract and rerunning:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">acs_drop</span> <span class="op">&lt;-</span> <span class="va">acs</span><span class="op">[</span><span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html" class="external-link">st_drop_geometry</a></span><span class="op">(</span><span class="va">acs</span><span class="op">)</span><span class="op">$</span><span class="va">variable</span> <span class="op">!=</span> <span class="st">"B19056_002"</span>, <span class="op">]</span></span>
<span></span>
<span><span class="va">weighted_d</span>   <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight</a></span><span class="op">(</span></span>
<span>  iso_sf <span class="op">=</span> <span class="va">iso_one</span>, acs_sf <span class="op">=</span> <span class="va">acs_drop</span>,</span>
<span>  weight_method <span class="op">=</span> <span class="st">"area"</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span><span class="va">propagated_d</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe</a></span><span class="op">(</span><span class="va">weighted_d</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">rates_d</span>      <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/warning.html" class="external-link">suppressWarnings</a></span><span class="op">(</span><span class="fu"><a href="../reference/cacs_derive_rates.html">cacs_derive_rates</a></span><span class="op">(</span><span class="va">propagated_d</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rates_d</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">estimand_family</span> <span class="op">==</span> <span class="st">"derived_rate"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span>,</span>
<span>         <span class="va">moe_fallback_reason</span>, <span class="va">failure_origin</span>, <span class="va">n_tracts_num</span>, <span class="va">n_tracts_den</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  variable     estimate      moe moe_fallback_reason failure_origin n_tracts_num
  &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;               &lt;chr&gt;                 &lt;int&gt;
1 poverty_rate   0.255   0.0351  n/a                 none                      3
2 snap_rate      0.251   0.0345  n/a                 none                      3
3 ssi_rate      NA      NA       n/a                 carrier                  NA
4 unemp_rate     0.0664  0.00838 n/a                 none                      3
5 labor_force…   0.536   0.0739  n/a                 none                      3
# ℹ 1 more variable: n_tracts_den &lt;int&gt;</code></pre>
</div>
</div>
<p><code>ssi_rate</code> now reports <code>estimate = NA</code>, <code>moe = NA</code>, <code>failure_origin = "carrier"</code>, and both <code>n_tracts_num</code> and <code>n_tracts_den</code> collapse to <code>NA</code> — while the other four rates compute normally. Critically, its <code>moe_fallback_reason</code> stays <code>"n/a"</code>, not a fallback reason: a missing carrier is an upstream failure surfaced through <code>failure_origin</code>, <strong>not</strong> an MOE-formula fallback. The two diagnostic surfaces stay distinct, exactly as the schema promises.</p>
<p>To summarize the check: a C2 rate (<code>snap_rate</code>) and its conservative margin reproduce by hand to the floating-point floor; a C1-eligible rate (<code>labor_force_participation</code>) reports the <em>tighter</em> subset margin, also matched by hand, and is recorded as <code>proportion_subset</code> with no fallback; a second C1-eligible rate (<code>poverty_rate</code>) on the same catchment falls back to C2 because its subset variance goes negative, with the substitution recorded as <code>moe_formula_effective = "general_ratio_conservative"</code>, <code>moe_fallback = TRUE</code>, and <code>moe_fallback_reason = "negative_variance"</code>, its margin again matched by hand; the <code>moe_formula_effective</code> column makes the C1-vs-C2 routing of all five rates visible at once; and a dropped carrier surfaces as <code>failure_origin = "carrier"</code> rather than an MOE fallback. The catalogue and the routing on this page are the catalogue and the routing the code runs.</p>
</section></section><section class="level2"><h2 id="where-this-sits">Where this sits<a class="anchor" aria-label="anchor" href="#where-this-sits"></a>
</h2>
<p>This article fixed the rate catalogue and routed each rate into the MOE machinery. Its companions cover the geometry and the uncertainty algebra it depends on, and the overview ties all three together; each reuses the notation fixed in the overview.</p>
<ul>
<li>
<strong>The estimator overview</strong>, with the shared notation, the six-family table that lists the <code>derived_rate</code> form, and the place of derived rates in the pipeline: <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>.</li>
<li>
<strong>Spatial aggregation</strong> — how the coverage weight <span class="math inline">w^{cov}_{sj}</span> is built and how each of a rate’s two totals <span class="math inline">\widehat{A}_s</span>, <span class="math inline">\widehat{B}_s</span> is aggregated as a <code>spatial_total</code>: <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code>.</li>
<li>
<strong>MOE propagation</strong> — the derivation of the two ratio-variance formulas (the subtracting C1 and the adding C2), the SE ↔︎ MOE relation, the numerical guards, and the never-silent C1 → C2 negative-variance fallback this article routes rates into: <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code>.</li>
<li>
<strong>Function reference</strong> — the <code>formula_dispatch</code> modes, the per-rate downgrade recording, the <code>n_tracts_num</code> / <code>n_tracts_den</code> contract, and the carrier-missing behavior are documented in <code><a href="../reference/cacs_derive_rates.html">?cacs_derive_rates</a></code>; the frozen five-rate catalogue object and its stability promise are in <code><a href="../reference/cacs_acs_default_rates.html">?cacs_acs_default_rates</a></code>.</li>
</ul>
<p>For the applied, run-it path that produces reporting tables with these rates and their margins of error from the same fixtures, see <code><a href="../articles/getting-started.html">vignette("getting-started", package = "catchmentACS")</a></code> and <code><a href="../articles/alabama-tutorial.html">vignette("alabama-tutorial", package = "catchmentACS")</a></code>.</p>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="https://github.com/joonho112" class="external-link">JoonHo Lee</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
