<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>MOE propagation: margins of error • catchmentACS</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="image/svg+xml" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<!-- katex math --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script><script src="../katex-auto.js"></script><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="theory-moe-propagation_files/libs/quarto-html/popper.min.js"></script><script src="theory-moe-propagation_files/libs/quarto-html/tippy.umd.min.js"></script><link href="theory-moe-propagation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="theory-moe-propagation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="MOE propagation: margins of error">
<meta property="og:image" content="https://joonho112.github.io/catchmentACS/logo.svg">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">catchmentACS</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.5.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-vignettes" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Vignettes</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-vignettes">
<li><h6 class="dropdown-header" data-toc-skip>--- Applied Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/getting-started.html">Getting started</a></li>
    <li><a class="dropdown-item" href="../articles/alabama-tutorial.html">Alabama tutorial</a></li>
    <li><a class="dropdown-item" href="../articles/providers.html">Providers</a></li>
    <li><a class="dropdown-item" href="../articles/visual-walkthrough.html">Visual walkthrough</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Method Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/methodology.html">Methodology</a></li>
    <li><a class="dropdown-item" href="../articles/theory-spatial-aggregation.html">Spatial aggregation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-moe-propagation.html">MOE propagation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-derived-rates.html">Derived rates</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Migration ---</h6></li>
    <li><a class="dropdown-item" href="../articles/porting-v01-to-v03.html">Porting from v0.1 to v0.3</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v03-to-v04.html">Porting from v0.3 to v0.4</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v04-to-v05.html">Porting from v0.4 to v0.5</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/joonho112/catchmentACS/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.svg" class="logo" alt=""><h1>MOE propagation: margins of error</h1>




      <small class="dont-index">Source: <a href="https://github.com/joonho112/catchmentACS/blob/HEAD/vignettes/theory-moe-propagation.qmd" class="external-link"><code>vignettes/theory-moe-propagation.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/joonho112/catchmentACS" class="external-link">catchmentACS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/" class="external-link">sf</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Force network-free, deterministic builds: no provider/Census calls, no cache.</span></span>
<span><span class="va">old_options</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span></span>
<span>  catchmentACS.progress <span class="op">=</span> <span class="st">"off"</span>,</span>
<span>  catchmentACS.rate_first_default <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span><span class="va">old_cache</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">getOption</a></span><span class="op">(</span><span class="st">"catchmentACS.cache_enabled"</span>, <span class="cn">NULL</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="va">old_options</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span>catchmentACS.cache_enabled <span class="op">=</span> <span class="va">old_cache</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/cacs_set_cache.html">cacs_set_cache</a></span><span class="op">(</span><span class="cn">FALSE</span>, scope <span class="op">=</span> <span class="st">"session"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>This article is the <strong>method-track</strong> companion to <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code> that develops the <em>uncertainty</em> half of the estimator. The overview <em>names</em> the four margin-of-error (MOE) formula families and states the <span class="math inline">M = 1.645\,SE</span> conversion; this article <em>derives</em> them — the SE/MOE relation, the weighted root-sum-square for sums and means, the two ratio-variance forms, the never-silent C1 → C2 fallback, and the numerical guards — and then does the thing the overview cannot: it <strong>reproduces the package’s MOE arithmetic by hand</strong> on a bundled fixture and <strong>triggers the fallback on purpose</strong>, so a methodologist can confirm that the formulas on this page are the formulas the code runs. The reference page <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code> is the implementation anchor; this article supplies the mathematics behind its “MOE formula families” section.</p>
<p>It is written for a reader who wants the propagation model on the page: why variances must accumulate on the standard-error scale, why a weighted sum and a weighted mean share one combination rule, why a ratio has two variance formulas and which one is the default, and exactly what the package records when the tighter formula breaks down. We reuse the notation fixed in the overview without re-motivating it: the isochrone <span class="math inline">I_s</span>, the tract <span class="math inline">T_j</span>, the coverage weight <span class="math inline">w^{cov}_{sj}</span> and the normalized mean weight <span class="math inline">w^{mean}_{sj}</span>, a tract-level count <span class="math inline">Y_j</span>, a scalar <span class="math inline">X_j</span>, a ratio’s numerator and denominator counts <span class="math inline">A_j, B_j</span>, and the published 90% tract margin of error <span class="math inline">M_j</span>. The <em>spatial</em> half — how those weights are built and how the point estimates <span class="math inline">\widehat{Y}_s</span>, <span class="math inline">\widehat{\bar X}_s</span>, <span class="math inline">\widehat{R}_s</span> aggregate — is derived in <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code>; this article takes the weights as given and carries the published uncertainty through them.</p>
<div>
<blockquote>
<p><strong>About the data in this article</strong></p>
<p>Every executable cell here is built entirely from the package’s bundled <code>inst/extdata</code> fixtures — the synthetic <code>legacy_2025_isochrones</code>, <code>legacy_2025_sites</code>, and <code>sample_alabama_subset</code> objects — so this article renders with <strong>no</strong> Census, OSRM, ORS, or other network calls. These fixtures preserve the production calling contract (sites, drive-time polygons, tract-level ACS variables) but are <strong>synthetic and illustrative</strong>: they are included only for examples, tests, and reproducible package checks. They are <strong>not</strong> live Alabama policy estimates and must not be cited as real ACS results. Any real analysis requires a fresh live run (see <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>).</p>
</blockquote>
</div>
<section class="level2"><h2 id="why-moe-propagation-needs-its-own-algebra">Why MOE propagation needs its own algebra<a class="anchor" aria-label="anchor" href="#why-moe-propagation-needs-its-own-algebra"></a>
</h2>
<p>Every ACS estimate ships with a published margin of error, and a catchment estimate is a <em>function of many</em> such estimates — a weighted sum of tract counts, a weighted blend of tract scalars, a ratio of two aggregated totals. The published MOEs describe the uncertainty of the <em>inputs</em>; the question this article answers is how that uncertainty travels to the <em>output</em>. Dropping it is not an option: a coverage-weighted count of persons in poverty with no margin of error invites a false precision the underlying survey never claimed. Carrying it naively is just as wrong, because margins of error do not add — a sum of two estimates each with margin <span class="math inline">M</span> does not have margin <span class="math inline">2M</span>.</p>
<p>The propagation rule is the standard one for a linear (or locally linear) combination of approximately independent estimates: <strong>variances add, margins of error do not.</strong> So the whole apparatus reduces to three moves repeated in four guises — convert each component margin to a variance, combine the variances under the appropriate model, and convert the combined variance back to a margin. The four families differ only in <em>how</em> the variances combine: a weighted sum (Family A), a weighted mean (Family B), a subset proportion (Family C1), and a general ratio (Family C2). The U.S. Census Bureau’s published guidance on approximating the margin of error of derived estimates (its ACS handbook for data users) gives all four; the package reimplements them so the formula, its guards, and its audit trail live in one place.</p>
<p>Two modeling assumptions sit under everything below, and both are inherited from the spatial-aggregation model rather than introduced here. First, the tract-level ACS estimates entering a catchment aggregate are treated as <strong>approximately independent</strong>, which is what lets their variances add without covariance terms; this is the same assumption the Census Bureau’s own sum-of-estimates approximation makes, and it is generally slightly conservative for positively correlated neighbors. Second, the <strong>weights are treated as fixed</strong> design quantities, not random — the coverage and mean weights are geometric ratios of measured areas, so they carry no sampling variance of their own. Both are stated plainly so a reader knows exactly what the margins below do and do not capture.</p>
</section><section class="level2"><h2 id="standard-errors-margins-of-error-and-the-90-convention">Standard errors, margins of error, and the 90% convention<a class="anchor" aria-label="anchor" href="#standard-errors-margins-of-error-and-the-90-convention"></a>
</h2>
<p>The U.S. Census Bureau publishes ACS uncertainty as a <strong>margin of error</strong> (MOE): the half-width of a confidence interval, reported at the <strong>90%</strong> level. An estimate <span class="math inline">\widehat{\theta}</span> ships as <span class="math inline">\widehat{\theta} \pm M</span>, and the interval <span class="math inline">[\widehat{\theta} - M,\; \widehat{\theta} + M]</span> is the Bureau’s 90% interval. The MOE is a <em>reported</em> quantity, but it is not the natural quantity for <em>combining</em> uncertainties — variances are. A margin of error and a standard error (SE) are interconvertible through a single confidence multiplier <span class="math inline">z</span>,</p>
<p><span class="math display">
M = z\, SE, \qquad SE = \frac{M}{z},
</span></p>
<p>and at the 90% level the Census multiplier is</p>
<p><span class="math display">
z = 1.645,
\qquad\text{so}\qquad
M = 1.645\, SE, \qquad SE = \frac{M}{1.645}.
</span></p>
<p>The constant <span class="math inline">1.645</span> is the Bureau’s official rounded value of the standard normal 95th percentile; the exact quantile <span class="math inline">\Phi^{-1}(0.95) \approx 1.6448536</span> differs only in the fourth decimal place, and the package adopts the rounded <span class="math inline">1.645</span> at the default level so its output is byte-compatible with hand calculations done the Bureau’s way. (The multiplier is configurable through the <code>level</code> argument; any other level resolves <span class="math inline">z</span> from the exact symmetric two-tailed normal quantile instead. Everything below is at the default <span class="math inline">z = 1.645</span>.)</p>
<p><strong>Why the SE scale matters.</strong> Variances of independent quantities add; margins of error do not. If two independent estimates have margins <span class="math inline">M_1</span> and <span class="math inline">M_2</span>, the margin of their sum is <strong>not</strong> <span class="math inline">M_1 + M_2</span>. The correct route is to drop to the SE scale, where variances are additive, combine, and convert back:</p>
<p><span class="math display">
M_{\text{sum}}
= z\, SE_{\text{sum}}
= z \sqrt{SE_1^2 + SE_2^2}
= z \sqrt{\left(\tfrac{M_1}{z}\right)^2 + \left(\tfrac{M_2}{z}\right)^2}.
</span></p>
<p>Every formula in this article is an instance of that pattern: <strong>divide each component MOE by <span class="math inline">z</span> to a standard error, combine the standard errors (or variances) under an independence assumption, multiply the combined SE back by <span class="math inline">z</span>.</strong> The package exposes the two conversions directly as <code><a href="../reference/cacs_se_to_moe.html">cacs_se_to_moe()</a></code> and <code><a href="../reference/cacs_moe_to_se.html">cacs_moe_to_se()</a></code> (exact inverses at a given level), and both are NA-safe: a missing input returns <code>NA</code>, never a silent zero. Internally the same constant divides MOEs into variances at the start of each family’s calculation and multiplies back at the end.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># M = 1.645 * SE and its exact inverse, on the same vector. NA passes through.</span></span>
<span><span class="va">se</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">50</span>, <span class="fl">100</span>, <span class="cn">NA</span><span class="op">)</span></span>
<span><span class="va">moe</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_se_to_moe.html">cacs_se_to_moe</a></span><span class="op">(</span><span class="va">se</span>, level <span class="op">=</span> <span class="fl">0.90</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span>moe <span class="op">=</span> <span class="va">moe</span>, recovered_se <span class="op">=</span> <span class="fu"><a href="../reference/cacs_moe_to_se.html">cacs_moe_to_se</a></span><span class="op">(</span><span class="va">moe</span>, level <span class="op">=</span> <span class="fl">0.90</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         moe1          moe2          moe3 recovered_se1 recovered_se2
        82.25        164.50            NA         50.00        100.00
recovered_se3
           NA </code></pre>
</div>
</div>
<p>The first SE of <code>50</code> becomes a margin of <code>82.25</code>, the second <code>100</code> becomes <code>164.5</code>, and <code><a href="../reference/cacs_moe_to_se.html">cacs_moe_to_se()</a></code> recovers the originals exactly; the <code>NA</code> survives both directions. This round-trip is the backbone of every combination below.</p>
</section><section class="level2"><h2 id="families-a-and-b-the-weighted-root-sum-square">Families A and B: the weighted root-sum-square<a class="anchor" aria-label="anchor" href="#families-a-and-b-the-weighted-root-sum-square"></a>
</h2>
<p>The first two families propagate margins through a <em>linear</em> combination of tract estimates, and they share one closed form. They differ only in the weight that multiplies each component margin — and that weight is exactly the one the matching estimand family uses for its point estimate, so the uncertainty travels through the <em>same</em> geometry as the estimate.</p>
<section class="level3"><h3 id="family-a-spatial-total-weighted-sum-of-counts">Family A — spatial total (weighted sum of counts)<a class="anchor" aria-label="anchor" href="#family-a-spatial-total-weighted-sum-of-counts"></a>
</h3>
<p>A <code>spatial_total</code> is the coverage-weighted sum of tract counts, <span class="math inline">\widehat{Y}_s = \sum_j w^{cov}_{sj}\, Y_j</span>, with the coverage weight derived in the spatial-aggregation article. Each tract contributes <span class="math inline">w^{cov}_{sj}\, Y_j</span>, an estimate whose standard error is <span class="math inline">w^{cov}_{sj}\, (M_j / z)</span>, because a fixed weight scales an SE linearly. Under approximate independence the variances add, so the variance of the catchment total is the sum of the squared coverage-weighted component SEs, and the margin of error is that combined SE lifted back by <span class="math inline">z</span>:</p>
<p><span class="math display">
M = z \sqrt{\sum_j \left(\frac{w^{cov}_{sj}\, M_j}{z}\right)^2}.
</span></p>
<p>This is a <strong>root-sum-square of coverage-weighted component MOEs.</strong> Read the structure: each published margin <span class="math inline">M_j</span> is divided by <span class="math inline">z</span> to a standard error, scaled by that tract’s coverage weight (the fraction of the tract the catchment captured), squared and summed into a variance, and the result is square-rooted and multiplied by <span class="math inline">z</span> back to a margin. A tract captured whole (<span class="math inline">w^{cov}_{sj} = 1</span>) contributes its full margin; a tract clipped to a tenth of its area contributes a tenth of it. The root-sum-square — rather than a plain sum — is the arithmetic statement that independent errors partially cancel: the combined margin grows like the square root of the number of comparable terms, not linearly.</p>
</section><section class="level3"><h3 id="family-b-weighted-scalar-proxy-mean">Family B — weighted scalar / proxy mean<a class="anchor" aria-label="anchor" href="#family-b-weighted-scalar-proxy-mean"></a>
</h3>
<p>A scalar proxy — per-capita income, a median-income proxy — is the normalized-mean-weighted blend <span class="math inline">\widehat{\bar X}_s = \sum_j w^{mean}_{sj}\, X_j</span>, with the mean weights that sum to one within a site and drive-time cell. Because the mean weights are also fixed design quantities, the propagation is structurally identical to Family A; only the weight changes from <span class="math inline">w^{cov}</span> to <span class="math inline">w^{mean}</span>:</p>
<p><span class="math display">
M = z \sqrt{\sum_j \left(\frac{w^{mean}_{sj}\, M_j}{z}\right)^2}.
</span></p>
<p>The single difference from Family A is the weight. The coverage weight allocates a <em>fraction</em> of each tract’s amount and is unbounded in sum; the mean weight is a <em>share</em> that is pre-normalized to sum to one. So a Family-A margin scales with how much area the catchment captured, while a Family-B margin is a weighted average of component margins on the same per-unit scale as the proxy itself — consistent with the point estimate, which is a convex combination of the tract values. In both families the weight that appears in the margin is the <em>same</em> weight that appears in the point estimate: coverage for a total, normalized mean for a proxy. This is the propagation analogue of the central spatial-aggregation point — a count and an average are aggregated by different weights — and it is why a single root-sum-square form serves both with only the weight swapped. (The implementation carries a raw accumulated variance per component and an explicit <code>weight_basis</code> so the two paths never cross; the per-cell normalization for Family B is the package’s responsibility, documented in <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>. A <code>metadata_only</code> row carries no estimate and therefore no margin.)</p>
<p>The numerical check below verifies Family A by hand against the package on a catchment with genuinely partial coverage, so the weights actually bite.</p>
</section></section><section class="level2"><h2 id="families-c1-and-c2-ratio-variance-subset-versus-conservative">Families C1 and C2: ratio variance, subset versus conservative<a class="anchor" aria-label="anchor" href="#families-c1-and-c2-ratio-variance-subset-versus-conservative"></a>
</h2>
<p>A <code>derived_rate</code> is not linear in its inputs — it is a <em>ratio</em> <span class="math inline">\widehat{R}_s = A/B</span> of two aggregated coverage totals, where both the numerator total <span class="math inline">A = \sum_j w^{cov}_{sj} A_j</span> and the denominator total <span class="math inline">B = \sum_j w^{cov}_{sj} B_j</span> are random estimates carrying their own propagated variance from Family A. A ratio has no exact finite-sample variance, so propagation uses the standard first-order (delta-method) linearization, and the package offers the two forms the Census Bureau’s handbook gives. Both are stated on the variance scale; the reported margin is recovered as <span class="math inline">M = z\sqrt{\widehat{\mathrm{Var}}(A/B)}</span> at the end. They differ by exactly one sign, and that sign is the hinge of both their statistical meaning and their numerical behavior.</p>
<section class="level3"><h3 id="family-c1-proportion-subset">Family C1 — proportion subset<a class="anchor" aria-label="anchor" href="#family-c1-proportion-subset"></a>
</h3>
<p>When the numerator <span class="math inline">A</span> is a true <strong>subset</strong> of the denominator <span class="math inline">B</span> — every person counted in <span class="math inline">A</span> is also counted in <span class="math inline">B</span>, as persons in poverty are a subset of the population for whom poverty status is determined — the numerator and denominator errors are positively correlated, and the Bureau’s proportion formula <em>subtracts</em> a cross term to credit that correlation:</p>
<p><span class="math display">
\widehat{\mathrm{Var}}(A/B)
\approx \frac{\mathrm{Var}(A) - (A/B)^2\, \mathrm{Var}(B)}{B^2}.
</span></p>
<p>Subtracting the cross term makes this the <em>tighter</em> (smaller) of the two estimates when it is valid, which is the whole reason to use it: it does not double-count the shared sampling uncertainty the subset relationship guarantees. But the subtraction is also its fragility — the bracketed expression can go <strong>negative</strong> when the denominator’s scaled variance <span class="math inline">(A/B)^2\,\mathrm{Var}(B)</span> exceeds the numerator’s <span class="math inline">\mathrm{Var}(A)</span>, in which case its square root is undefined and the formula returns no admissible variance. That edge case is handled in the next section, never silently.</p>
</section><section class="level3"><h3 id="family-c2-general-ratio-conservative">Family C2 — general ratio (conservative)<a class="anchor" aria-label="anchor" href="#family-c2-general-ratio-conservative"></a>
</h3>
<p>When the subset relationship is <em>not</em> guaranteed — an arbitrary ratio of two counts, or a derived rate where conservative reproducibility is preferred — the correct general form treats the numerator and denominator as approximately independent and <em>adds</em> the cross term:</p>
<p><span class="math display">
\widehat{\mathrm{Var}}(A/B)
\approx \frac{\mathrm{Var}(A) + (A/B)^2\, \mathrm{Var}(B)}{B^2}.
</span></p>
<p>Note the <strong>+</strong> sign. Two consequences follow from that single change. First, this variance is <strong>always non-negative</strong>: a sum of two squared, non-negative terms can never go below zero, so Family C2 always yields an admissible margin. Second, it is the <strong>conservative</strong> estimate — by adding rather than subtracting the cross term, it never understates the uncertainty, at the cost of being slightly wide when the numerator really is a subset. This is exactly the trade the package makes for its curated derived rates: <strong>Family C2 (<code>general_ratio_conservative</code>) is the default</strong>, and the tighter Family C1 (<code>proportion_subset</code>) is applied only when a true subset relationship is asserted for a rate eligible for it. Among the five curated rates, the poverty rate and labor-force participation are the subset-eligible ones; the SNAP, SSI, and unemployment rates route to C2 by default. The full per-rate policy is derived in <code><a href="../articles/theory-derived-rates.html">vignette("theory-derived-rates", package = "catchmentACS")</a></code>.</p>
<p>The sign is the entire distinction. A single character — the minus in C1, the plus in C2 — separates the tighter, subset-only formula from the conservative, always-defined one. Whether C1 is <em>allowed</em> to break down gracefully is the subject of the fallback.</p>
</section></section><section class="level2"><h2 id="the-c1-c2-fallback-and-the-status-columns">The C1 → C2 fallback and the status columns<a class="anchor" aria-label="anchor" href="#the-c1-c2-fallback-and-the-status-columns"></a>
</h2>
<p>The two ratio formulas are not independent choices made once at dispatch — they are connected by a guard. When a row is dispatched to Family C1 but its subset variance comes out <strong>negative</strong>, the package does not return a missing value, a silent C1 number, or a <code>NaN</code> a caller might miss. It <strong>recomputes the margin with the always-non-negative Family C2 formula</strong> so a defensible value is still produced, and — this is the design commitment — it <strong>records the substitution per row</strong> rather than hiding it. The fallback is never silent.</p>
<p><code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code> returns, for every row, both the formula the dispatch <em>asked for</em> and the formula it <em>actually used</em>:</p>
<table class="table caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Column</th>
<th>Meaning</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>moe_formula_requested</code></td>
<td>the formula the dispatch resolved for this row (here, <code>proportion_subset</code>)</td>
</tr>
<tr class="even">
<td><code>moe_formula_effective</code></td>
<td>the formula whose value was actually written (after any fallback)</td>
</tr>
<tr class="odd">
<td><code>moe_fallback</code></td>
<td>
<code>TRUE</code> when the effective formula overrode the request</td>
</tr>
<tr class="even">
<td><code>moe_fallback_reason</code></td>
<td>the cause: <code>negative_variance</code>, <code>zero_denominator</code>, <code>missing_moe</code>, or <code>n/a</code>
</td>
</tr>
</tbody>
</table>
<p>For the C1 → C2 case specifically, a row whose subset variance went negative is recorded as</p>
<ul>
<li>
<code>moe_formula_requested = "proportion_subset"</code> — the request is preserved,</li>
<li>
<code>moe_formula_effective = "general_ratio_conservative"</code> — C2 produced the value,</li>
<li>
<code>moe_fallback = TRUE</code>,</li>
<li>
<code>moe_fallback_reason = "negative_variance"</code>.</li>
</ul>
<p>A clean C1 row that stayed positive keeps <code>moe_formula_effective = "proportion_subset"</code>, <code>moe_fallback = FALSE</code>, and <code>moe_fallback_reason = "n/a"</code>, and its requested and effective formulas agree. At the end of a run a <strong>single summary</strong> reports the total counts by reason, and a run-level provenance attribute records how many rows took each path, so the fallback is auditable in aggregate as well as per row. The point of keeping both <code>requested</code> and <code>effective</code> is that the row reads as a self-documenting audit record: <em>this row asked for the subset formula, its variance went negative, so the conservative formula produced the value.</em> An auditor reading the output five years later can reconstruct exactly which rows took which path without rerunning anything; no information is lost and nothing is repaired behind the analyst’s back.</p>
<p>The same <code>moe_fallback</code>/<code>moe_fallback_reason</code> mechanism also records the two <em>degenerate</em> outcomes that are not formula substitutions but value losses, covered next: a zero denominator and a missing input margin both yield <code>NA</code> with their own reason strings.</p>
</section><section class="level2"><h2 id="numerical-guards">Numerical guards<a class="anchor" aria-label="anchor" href="#numerical-guards"></a>
</h2>
<p>Five guards protect the formulas from the inputs real ACS data presents. They are implemented once, in the package’s MOE helpers, so every family inherits the same behavior, and each leaves a visible trace rather than a silent number.</p>
<ul>
<li>
<strong>Denominator near zero.</strong> Families B and C divide by a weight sum or a denominator estimate. When that divisor is within a small epsilon of zero (the package uses the square root of machine epsilon, about <span class="math inline">1.5 \times 10^{-8}</span>), the result is set to <code>NA</code> rather than allowed to explode. For a ratio row this is recorded as <code>moe_fallback_reason = "zero_denominator"</code> — the structural reason an empty or near-empty catchment does not masquerade as a precise rate.</li>
<li>
<strong>Negative variance in a proportion.</strong> The Family C1 subtraction can go below zero; this is the trigger for the C1 → C2 fallback of the previous section, recorded as <code>moe_fallback_reason = "negative_variance"</code>.</li>
<li>
<strong>Missing-margin propagation.</strong> A missing component margin propagates to a missing result rather than being silently treated as zero, preserving ACS suppression as a signal. For a ratio row a missing numerator or denominator margin yields <code>NA</code> with <code>moe_fallback_reason = "missing_moe"</code>.</li>
<li>
<strong>Non-negative C2 variance.</strong> Because C2 adds rather than subtracts, its bracket is provably <span class="math inline">\ge 0</span>; it has no negative-variance branch and always yields a real margin. This is what makes C2 a safe fallback target for C1.</li>
<li>
<strong>The multiplier is a fixed constant.</strong> At the default 90% level <span class="math inline">z = 1.645</span> is the Bureau’s rounded value, not the exact normal quantile; this is a deliberate choice for byte-level reproducibility against ACS-published margins, and the roughly <span class="math inline">5 \times 10^{-5}</span> gap to <span class="math inline">\Phi^{-1}(0.95)</span> is absorbed within the package’s regression tolerance. Other confidence levels resolve <span class="math inline">z</span> at full precision.</li>
</ul>
<p>The common thread is that none of these guards repairs silently. A zero denominator, a negative subset variance, and a missing margin each leave a typed trace in <code>moe_fallback_reason</code> and feed the end-of-run summary, so a degenerate input is always distinguishable in the output from a clean computation.</p>
</section><section class="level2"><h2 id="numerical-verification-the-formulas-match-the-package">Numerical verification: the formulas match the package<a class="anchor" aria-label="anchor" href="#numerical-verification-the-formulas-match-the-package"></a>
</h2>
<p>This is the section that earns a methodologist’s trust. We do two checks against the <em>real</em> <code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code>, both offline on bundled fixtures, on a single catchment. First we reproduce a <strong>Family A weighted root-sum-square</strong> entirely by hand and assert it equals the package’s reported margin to machine precision. Then, on the <em>same</em> catchment, we deliberately construct a derived-rate case whose <strong>C1 subset variance is negative</strong> and watch the package fall back to C2 — recording <code>moe_fallback = TRUE</code> and <code>moe_fallback_reason = "negative_variance"</code> — and we reproduce the C2 value by hand as well. If the formulas on this page were not the formulas the code runs, either check would fail.</p>
<p>We build the catchment from the fixtures with <code><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight()</a></code>, exactly the shapes pipeline stages 1–2 would have produced. We pick a catchment whose coverage is <em>partial and uneven</em> so the weighted root-sum-square is genuinely exercised: <code>AL_SITE_17</code> at a 10-minute drive intersects three tracts — one fully enclosed and two clipped to about a ninth of their area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># These fixtures are exactly the shapes stages 1-2 would have returned, frozen.</span></span>
<span><span class="va">iso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_isochrones.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">acs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"sample_alabama_subset.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">site_id</span>    <span class="op">&lt;-</span> <span class="st">"AL_SITE_17"</span></span>
<span><span class="va">drive_time</span> <span class="op">&lt;-</span> <span class="fl">10L</span></span>
<span></span>
<span><span class="va">iso_one</span> <span class="op">&lt;-</span> <span class="va">iso</span><span class="op">[</span></span>
<span>  <span class="va">iso</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">site_id</span> <span class="op">&amp;</span> <span class="va">iso</span><span class="op">$</span><span class="va">drive_time_min</span> <span class="op">==</span> <span class="va">drive_time</span>, ,</span>
<span>  drop <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">]</span></span>
<span></span>
<span><span class="co"># keep_tract_audit exposes the per-tract coverage weights we recompute by hand.</span></span>
<span><span class="va">weighted</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight</a></span><span class="op">(</span></span>
<span>  iso_sf           <span class="op">=</span> <span class="va">iso_one</span>,</span>
<span>  acs_sf           <span class="op">=</span> <span class="va">acs</span>,</span>
<span>  weight_method    <span class="op">=</span> <span class="st">"area"</span>,</span>
<span>  keep_tract_audit <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  verbose          <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">propagated</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe</a></span><span class="op">(</span><span class="va">weighted</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
</div>
<section class="level3"><h3 id="step-1-reproduce-a-family-a-weighted-rss-by-hand">Step 1 — reproduce a Family A weighted RSS by hand<a class="anchor" aria-label="anchor" href="#step-1-reproduce-a-family-a-weighted-rss-by-hand"></a>
</h3>
<p><em>Persons in poverty</em> (<code>B17001_002</code>) is a <code>spatial_total</code>, so its margin comes from Family A. The per-tract audit gives the coverage weight <span class="math inline">w^{cov}_{sj}</span> (<code>area_wt</code>); we join each tract’s <strong>published</strong> margin <span class="math inline">M_j</span> from the ACS fixture and assemble the inputs:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">VAR</span> <span class="op">&lt;-</span> <span class="st">"B17001_002"</span></span>
<span></span>
<span><span class="va">audit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted</span>, <span class="st">"cacs_tract_audit"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html" class="external-link">transmute</a></span><span class="op">(</span><span class="va">GEOID</span>, w_cov <span class="op">=</span> <span class="va">area_wt</span><span class="op">)</span></span>
<span></span>
<span><span class="va">published</span> <span class="op">&lt;-</span> <span class="va">acs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html" class="external-link">st_drop_geometry</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">GEOID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="va">audit</span><span class="op">$</span><span class="va">GEOID</span>, <span class="va">variable</span> <span class="op">==</span> <span class="va">VAR</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span>, M_j <span class="op">=</span> <span class="va">moe</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hand_A</span> <span class="op">&lt;-</span> <span class="va">audit</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">published</span>, by <span class="op">=</span> <span class="st">"GEOID"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html" class="external-link">desc</a></span><span class="op">(</span><span class="va">w_cov</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hand_A</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  GEOID       w_cov   M_j
  &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;
1 01125001001 1       200
2 01127001001 0.113   218
3 01123001001 0.113   152</code></pre>
</div>
</div>
<p>Now the Family A formula, term by term: scale each published margin by its coverage weight, divide by <span class="math inline">z</span>, square, sum, square-root, and multiply back by <span class="math inline">z</span> — <span class="math inline">M = z\sqrt{\sum_j (w^{cov}_{sj} M_j / z)^2}</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">z</span> <span class="op">&lt;-</span> <span class="fl">1.645</span></span>
<span></span>
<span><span class="va">per_tract_var</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">hand_A</span><span class="op">$</span><span class="va">w_cov</span> <span class="op">*</span> <span class="va">hand_A</span><span class="op">$</span><span class="va">M_j</span> <span class="op">/</span> <span class="va">z</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span>  <span class="co"># (w * M / z)^2 per tract</span></span>
<span><span class="va">hand_moe_A</span>    <span class="op">&lt;-</span> <span class="va">z</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">per_tract_var</span><span class="op">)</span><span class="op">)</span>       <span class="co"># z * sqrt(sum(...))</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span></span>
<span>  per_tract_var <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="va">per_tract_var</span>, <span class="fl">4</span><span class="op">)</span>,</span>
<span>  summed_var    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">per_tract_var</span><span class="op">)</span>,</span>
<span>  hand_moe_A    <span class="op">=</span> <span class="va">hand_moe_A</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$per_tract_var
[1] 14781.8294   222.3397   108.0903

$summed_var
[1] 15112.26

$hand_moe_A
[1] 202.223</code></pre>
</div>
</div>
<p>The fully-enclosed tract dominates the combined variance; the two clipped tracts enter with small coverage weights (about a ninth) and contribute little even though their <em>raw</em> published margins are not small — exactly what the weighted form predicts, since the weight, not the raw margin, governs the contribution. Now the package’s own row for the same variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pkg_A</span> <span class="op">&lt;-</span> <span class="va">propagated</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">==</span> <span class="va">VAR</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span>, <span class="va">moe_formula_effective</span>, <span class="va">moe_fallback</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pkg_A</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  variable   estimate   moe moe_formula_effective moe_fallback
  &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                 &lt;lgl&gt;
1 B17001_002    1237.  202. weighted_sum          FALSE       </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  moe_match    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">hand_moe_A</span>, <span class="va">pkg_A</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  moe_abs_diff <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">hand_moe_A</span> <span class="op">-</span> <span class="va">pkg_A</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   moe_match moe_abs_diff
           1            0 </code></pre>
</div>
</div>
<p>The package routed this count through <code>moe_formula_effective = "weighted_sum"</code> (Family A) with no fallback, and its reported <code>moe</code> — about <code>202.2</code> — <strong>equals</strong> the hand-computed weighted root-sum-square exactly, with an absolute difference of zero. The margin on this page and the margin in the code are the same arithmetic.</p>
</section><section class="level3"><h3 id="step-2-trigger-the-c1-c2-fallback">Step 2 — trigger the C1 → C2 fallback<a class="anchor" aria-label="anchor" href="#step-2-trigger-the-c1-c2-fallback"></a>
</h3>
<p>Now the fallback. The poverty rate’s numerator <code>B17001_002</code> is a true subset of its denominator <code>B17001_001</code>, so it is C1-eligible; we will request the <code>proportion_subset</code> formula. To make the subset variance go <strong>negative</strong> in a fully controlled way, we take the real catchment and lower the numerator’s accumulated variance well below the denominator’s scaled variance <span class="math inline">(A/B)^2\,\mathrm{Var}(B)</span> — the configuration that drives C1’s bracket below zero. The aggregation carriers (an attribute of the intersect output) hold each component’s coverage total and accumulated variance; we copy them, shrink the numerator’s variance, and attach a matching carrier and long row for the rate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">carr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted</span>, <span class="st">"cacs_aggregation_carriers"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">num_code</span> <span class="op">&lt;-</span> <span class="st">"B17001_002"</span>  <span class="co"># poverty_rate numerator (subset)</span></span>
<span><span class="va">den_code</span> <span class="op">&lt;-</span> <span class="st">"B17001_001"</span>  <span class="co"># poverty_rate denominator (universe)</span></span>
<span></span>
<span><span class="va">A</span>    <span class="op">&lt;-</span> <span class="va">carr</span><span class="op">$</span><span class="va">est_total</span><span class="op">[</span><span class="va">carr</span><span class="op">$</span><span class="va">variable</span> <span class="op">==</span> <span class="va">num_code</span><span class="op">]</span>      <span class="co"># numerator total</span></span>
<span><span class="va">B</span>    <span class="op">&lt;-</span> <span class="va">carr</span><span class="op">$</span><span class="va">est_total</span><span class="op">[</span><span class="va">carr</span><span class="op">$</span><span class="va">variable</span> <span class="op">==</span> <span class="va">den_code</span><span class="op">]</span>      <span class="co"># denominator total</span></span>
<span><span class="va">VarB</span> <span class="op">&lt;-</span> <span class="va">carr</span><span class="op">$</span><span class="va">var_total_raw</span><span class="op">[</span><span class="va">carr</span><span class="op">$</span><span class="va">variable</span> <span class="op">==</span> <span class="va">den_code</span><span class="op">]</span>  <span class="co"># denominator variance</span></span>
<span><span class="va">p</span>    <span class="op">&lt;-</span> <span class="va">A</span> <span class="op">/</span> <span class="va">B</span>                                          <span class="co"># the proportion A / B</span></span>
<span></span>
<span><span class="co"># Force C1's bracket Var(A) - p^2 Var(B) below zero by setting the numerator's</span></span>
<span><span class="co"># accumulated variance to a quarter of the denominator's scaled variance.</span></span>
<span><span class="va">VarA_neg</span> <span class="op">&lt;-</span> <span class="fl">0.25</span> <span class="op">*</span> <span class="va">p</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB</span></span>
<span></span>
<span><span class="va">carr_fb</span> <span class="op">&lt;-</span> <span class="va">carr</span></span>
<span><span class="va">carr_fb</span><span class="op">$</span><span class="va">var_total_raw</span><span class="op">[</span><span class="va">carr_fb</span><span class="op">$</span><span class="va">variable</span> <span class="op">==</span> <span class="va">num_code</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">VarA_neg</span></span>
<span></span>
<span><span class="co"># A carrier row keyed on the rate name so the long rate row passes the</span></span>
<span><span class="co"># carrier-key check; C1/C2 read the numerator/denominator ACS-code rows, not</span></span>
<span><span class="co"># this placeholder, so its numeric fields are inert.</span></span>
<span><span class="va">rate_carrier</span> <span class="op">&lt;-</span> <span class="va">carr_fb</span><span class="op">[</span><span class="va">carr_fb</span><span class="op">$</span><span class="va">variable</span> <span class="op">==</span> <span class="va">num_code</span>, , drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span>, <span class="op">]</span></span>
<span><span class="va">rate_carrier</span><span class="op">$</span><span class="va">variable</span>        <span class="op">&lt;-</span> <span class="st">"poverty_rate"</span></span>
<span><span class="va">rate_carrier</span><span class="op">$</span><span class="va">estimand_family</span> <span class="op">&lt;-</span> <span class="st">"derived_rate"</span></span>
<span><span class="va">rate_carrier</span><span class="op">$</span><span class="va">est_total</span>       <span class="op">&lt;-</span> <span class="cn">NA_real_</span></span>
<span><span class="va">rate_carrier</span><span class="op">$</span><span class="va">var_total_raw</span>   <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span><span class="va">rate_carrier</span><span class="op">$</span><span class="va">est_mean</span>        <span class="op">&lt;-</span> <span class="cn">NA_real_</span></span>
<span><span class="va">rate_carrier</span><span class="op">$</span><span class="va">var_mean_raw</span>    <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span><span class="va">carr_fb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html" class="external-link">bind_rows</a></span><span class="op">(</span><span class="va">carr_fb</span>, <span class="va">rate_carrier</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The long-format derived_rate row the formula will act on (built from a</span></span>
<span><span class="co"># spatial_total template so all canonical columns and types are present).</span></span>
<span><span class="va">rate_row</span> <span class="op">&lt;-</span> <span class="va">weighted</span><span class="op">[</span><span class="va">weighted</span><span class="op">$</span><span class="va">variable</span> <span class="op">==</span> <span class="va">num_code</span>, , drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span>, <span class="op">]</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">variable</span>              <span class="op">&lt;-</span> <span class="st">"poverty_rate"</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">estimand_family</span>       <span class="op">&lt;-</span> <span class="st">"derived_rate"</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">estimate</span>              <span class="op">&lt;-</span> <span class="cn">NA_real_</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">moe</span>                   <span class="op">&lt;-</span> <span class="cn">NA_real_</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">weight_basis</span>          <span class="op">&lt;-</span> <span class="st">"coverage"</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">moe_formula_requested</span> <span class="op">&lt;-</span> <span class="cn">NA_character_</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">moe_formula_effective</span> <span class="op">&lt;-</span> <span class="cn">NA_character_</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">moe_fallback</span>          <span class="op">&lt;-</span> <span class="cn">NA</span></span>
<span><span class="va">rate_row</span><span class="op">$</span><span class="va">moe_fallback_reason</span>   <span class="op">&lt;-</span> <span class="st">"n/a"</span></span>
<span></span>
<span><span class="va">weighted_fb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html" class="external-link">bind_rows</a></span><span class="op">(</span><span class="va">weighted</span>, <span class="va">rate_row</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted_fb</span>, <span class="st">"cacs_aggregation_carriers"</span><span class="op">)</span>  <span class="op">&lt;-</span> <span class="va">carr_fb</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted_fb</span>, <span class="st">"cacs_schema_version"</span><span class="op">)</span>         <span class="op">&lt;-</span> <span class="st">"1.0"</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted_fb</span>, <span class="st">"cacs_aggregation_provenance"</span><span class="op">)</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted</span>, <span class="st">"cacs_aggregation_provenance"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Confirm we have genuinely created a negative subset variance:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  Var_A_set         <span class="op">=</span> <span class="va">VarA_neg</span>,</span>
<span>  scaled_Var_B      <span class="op">=</span> <span class="va">p</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB</span>,</span>
<span>  C1_inside_bracket <span class="op">=</span> <span class="va">VarA_neg</span> <span class="op">-</span> <span class="va">p</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB</span>   <span class="co"># &lt; 0 by construction</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Var_A_set      scaled_Var_B C1_inside_bracket
         612.6206         2450.4825        -1837.8618 </code></pre>
</div>
</div>
<p>The bracket <span class="math inline">\mathrm{Var}(A) - (A/B)^2\,\mathrm{Var}(B)</span> is negative, so C1 cannot produce a real margin. We now request <code>proportion_subset</code> for this rate through the locked <code>formula</code> argument and let the package decide:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">propagated_fb</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe</a></span><span class="op">(</span></span>
<span>  <span class="va">weighted_fb</span>,</span>
<span>  formula <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span>poverty_rate <span class="op">=</span> <span class="st">"proportion_subset"</span><span class="op">)</span>,</span>
<span>  verbose <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">fb_row</span> <span class="op">&lt;-</span> <span class="va">propagated_fb</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">==</span> <span class="st">"poverty_rate"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span>,</span>
<span>         <span class="va">moe_formula_requested</span>, <span class="va">moe_formula_effective</span>,</span>
<span>         <span class="va">moe_fallback</span>, <span class="va">moe_fallback_reason</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fb_row</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  variable     estimate    moe moe_formula_requested moe_formula_effective
  &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;                 &lt;chr&gt;
1 poverty_rate    0.335 0.0246 proportion_subset     general_ratio_conservative
# ℹ 2 more variables: moe_fallback &lt;lgl&gt;, moe_fallback_reason &lt;chr&gt;</code></pre>
</div>
</div>
<p>The status columns tell the whole story: <code>moe_formula_requested</code> is still <code>"proportion_subset"</code> (the request is preserved), but <code>moe_formula_effective</code> is <code>"general_ratio_conservative"</code>, <code>moe_fallback</code> is <code>TRUE</code>, and <code>moe_fallback_reason</code> is <code>"negative_variance"</code>. The fallback fired, and it is fully recorded — exactly the never-silent contract.</p>
</section><section class="level3"><h3 id="step-3-reproduce-the-c2-fallback-value-by-hand">Step 3 — reproduce the C2 fallback value by hand<a class="anchor" aria-label="anchor" href="#step-3-reproduce-the-c2-fallback-value-by-hand"></a>
</h3>
<p>The recorded margin should be the <strong>C2</strong> formula evaluated on the same inputs, <span class="math inline">M = z\sqrt{\mathrm{Var}(A) + (A/B)^2\,\mathrm{Var}(B)}\,/\,|B|</span>, and the estimate should be the proportion <span class="math inline">p = A/B</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hand_moe_C2</span> <span class="op">&lt;-</span> <span class="va">z</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">VarA_neg</span> <span class="op">+</span> <span class="va">p</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">VarB</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">B</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  estimate_match <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">p</span>,           <span class="va">fb_row</span><span class="op">$</span><span class="va">estimate</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  moe_match      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">hand_moe_C2</span>, <span class="va">fb_row</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  moe_abs_diff   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">hand_moe_C2</span> <span class="op">-</span> <span class="va">fb_row</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>estimate_match      moe_match   moe_abs_diff
             1              1              0 </code></pre>
</div>
</div>
<p>Both match exactly. The package’s fallback margin equals the hand-computed C2 root, and its estimate equals the proportion <span class="math inline">A/B</span>. The run-level provenance attribute also counts the event:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">propagated_fb</span>, <span class="st">"cacs_moe_provenance"</span><span class="op">)</span><span class="op">$</span><span class="va">n_rows_fallback_c1_to_c2</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>One row took the C1 → C2 path, matching the single fallback we constructed.</p>
<p>To summarize the check: a Family A weighted root-sum-square reproduced by hand equals the package’s reported <code>spatial_total</code> margin to the floating-point floor on a partially-covered catchment; a deliberately negative C1 subset variance on the same catchment triggers the package’s never-silent C1 → C2 fallback, recorded as <code>moe_formula_requested = "proportion_subset"</code>, <code>moe_formula_effective = "general_ratio_conservative"</code>, <code>moe_fallback = TRUE</code>, and <code>moe_fallback_reason = "negative_variance"</code>; and the resulting C2 margin and the <span class="math inline">A/B</span> estimate both reproduce by hand exactly. The formulas in this article and the arithmetic in the code are the same arithmetic, fallback included.</p>
</section></section><section class="level2"><h2 id="where-this-sits">Where this sits<a class="anchor" aria-label="anchor" href="#where-this-sits"></a>
</h2>
<p>This article derived and verified the uncertainty half of the estimator. Its companions cover the spatial half and the rate catalogue, and the methodology overview ties all three together; each reuses the notation fixed in the overview.</p>
<ul>
<li>
<strong>The estimator overview</strong>, with the shared notation, the six-family table, and the four-family MOE summary this article expands: <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>. This article is the derivation behind its margins-of-error section.</li>
<li>
<strong>Spatial aggregation</strong> — the coverage and normalized mean weights this article carries margins through, the per-site intersection algorithm, and the point-estimate forms <span class="math inline">\widehat{Y}_s</span>, <span class="math inline">\widehat{\bar X}_s</span>, <span class="math inline">\widehat{R}_s</span>: <code><a href="../articles/theory-spatial-aggregation.html">vignette("theory-spatial-aggregation", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>.</li>
<li>
<strong>Derived rates</strong> — which of the curated rates are C1-eligible versus C2 by baseline policy, their ACS numerator/denominator pairs, and the carrier-lookup mechanics behind the ratio margins: <code><a href="../articles/theory-derived-rates.html">vignette("theory-derived-rates", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_derive_rates.html">?cacs_derive_rates</a></code>.</li>
<li>
<strong>Function reference</strong> — the four families, the C1 → C2 fallback, the full status-column contract, the five numerical guards, and the <code>formula</code> and <code>level</code> arguments are documented in <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code>; the SE ↔︎ MOE converters are <code><a href="../reference/cacs_se_to_moe.html">?cacs_se_to_moe</a></code> and <code><a href="../reference/cacs_moe_to_se.html">?cacs_moe_to_se</a></code>.</li>
</ul>
<p>For the applied, run-it path that produces reporting tables with margins of error from these same fixtures, see <code><a href="../articles/getting-started.html">vignette("getting-started", package = "catchmentACS")</a></code> and <code><a href="../articles/alabama-tutorial.html">vignette("alabama-tutorial", package = "catchmentACS")</a></code>.</p>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="https://github.com/joonho112" class="external-link">JoonHo Lee</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
