<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Alabama Pre-K tutorial: from the raw pipeline to reporting tables • catchmentACS</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="image/svg+xml" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<!-- katex math --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script><script src="../katex-auto.js"></script><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="alabama-tutorial_files/libs/quarto-html/popper.min.js"></script><script src="alabama-tutorial_files/libs/quarto-html/tippy.umd.min.js"></script><link href="alabama-tutorial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="alabama-tutorial_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="alabama-tutorial_files/libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="alabama-tutorial_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><link href="alabama-tutorial_files/libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="alabama-tutorial_files/libs/leaflet-1.3.1/leaflet.js"></script><link href="alabama-tutorial_files/libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="alabama-tutorial_files/libs/proj4-2.6.2/proj4.min.js"></script><script src="alabama-tutorial_files/libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script><link href="alabama-tutorial_files/libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="alabama-tutorial_files/libs/leaflet-binding-2.2.3/leaflet.js"></script><script src="alabama-tutorial_files/libs/leaflet-providers-3.0.0/leaflet-providers.js"></script><script src="alabama-tutorial_files/libs/leaflet-providers-plugin-2.2.3/leaflet-providers-plugin.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Alabama Pre-K tutorial: from the raw pipeline to reporting tables">
<meta property="og:image" content="https://joonho112.github.io/catchmentACS/logo.svg">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">catchmentACS</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.5.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-vignettes" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Vignettes</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-vignettes">
<li><h6 class="dropdown-header" data-toc-skip>--- Applied Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/getting-started.html">Getting started</a></li>
    <li><a class="dropdown-item" href="../articles/alabama-tutorial.html">Alabama tutorial</a></li>
    <li><a class="dropdown-item" href="../articles/providers.html">Providers</a></li>
    <li><a class="dropdown-item" href="../articles/visual-walkthrough.html">Visual walkthrough</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Method Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/methodology.html">Methodology</a></li>
    <li><a class="dropdown-item" href="../articles/theory-spatial-aggregation.html">Spatial aggregation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-moe-propagation.html">MOE propagation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-derived-rates.html">Derived rates</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Migration ---</h6></li>
    <li><a class="dropdown-item" href="../articles/porting-v01-to-v03.html">Porting from v0.1 to v0.3</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v03-to-v04.html">Porting from v0.3 to v0.4</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v04-to-v05.html">Porting from v0.4 to v0.5</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/joonho112/catchmentACS/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.svg" class="logo" alt=""><h1>Alabama Pre-K tutorial: from the raw pipeline to reporting tables</h1>




      <small class="dont-index">Source: <a href="https://github.com/joonho112/catchmentACS/blob/main/vignettes/alabama-tutorial.qmd" class="external-link"><code>vignettes/alabama-tutorial.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/joonho112/catchmentACS" class="external-link">catchmentACS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/" class="external-link">sf</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org" class="external-link">tidyr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Force network-free, deterministic builds: no provider/Census calls, no cache.</span></span>
<span><span class="va">old_options</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span></span>
<span>  catchmentACS.progress <span class="op">=</span> <span class="st">"off"</span>,</span>
<span>  catchmentACS.rate_first_default <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span><span class="va">old_cache</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">getOption</a></span><span class="op">(</span><span class="st">"catchmentACS.cache_enabled"</span>, <span class="cn">NULL</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="va">old_options</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span>catchmentACS.cache_enabled <span class="op">=</span> <span class="va">old_cache</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/cacs_set_cache.html">cacs_set_cache</a></span><span class="op">(</span><span class="cn">FALSE</span>, scope <span class="op">=</span> <span class="st">"session"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>This is the package’s long-form, flagship tutorial. Where <code><a href="../articles/getting-started.html">vignette("getting-started", package = "catchmentACS")</a></code> shows the whole pipeline in one call and <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code> explains the math, this article does two things in sequence. First it takes the one call <em>apart</em> — walking the five pipeline functions one stage at a time, reading each intermediate result, then collapsing them back into a single <code><a href="../reference/cacs_run.html">cacs_run()</a></code> and confirming the two paths agree to the last digit. Then it carries the recomposed result all the way to the <em>deliverables</em> an equity researcher actually hands off: a site-by-drive-time rate matrix, a priority ranking, a single-site profile, and a tidy table ready to write to CSV.</p>
<p>It is written for a Pre-K equity researcher who wants to understand each stage well enough to describe it in a methods section, and who then needs to turn the output into a memo, a dissertation chapter, or a journal table. It assumes you have met <code>dplyr</code>, <code>sf</code>, isochrones, and margins of error before.</p>
<p>The motivating question comes from Pre-K funding-equity work: <em>for each First Class Pre-K site, what are the neighborhood conditions — poverty, food assistance, employment — within a short drive, and how much do those conditions shift as the catchment grows from 5 to 15 minutes?</em> <code>catchmentACS</code> is the reusable engine for that question. It replaces an earlier set of one-off analysis scripts with a documented, regression-tested package, so a finding can be reproduced — and a table re-generated — by a colleague who was not in the room when it was first run. Stable, uncertainty-aware answers feed directly into how the state reasons about where new Pre-K capacity should go.</p>
<div>
<blockquote>
<p><strong>About the data in this article</strong></p>
<p>Every table, map, and figure here is built entirely from the package’s bundled <code>inst/extdata</code> fixtures (<code>cacs_alabama_sites</code>, the synthetic <code>legacy_2025_*</code> objects, and <code>sample_alabama_subset</code>), so this article renders with <strong>no</strong> Census, OSRM, ORS, or other network calls. These fixtures preserve the production calling contract (sites, drive-time polygons, tract-level ACS variables) but are <strong>synthetic and illustrative</strong> — included only for examples, tests, and reproducible package checks. They are <strong>not</strong> live Alabama policy estimates and must not be cited as real ACS results. Any real analysis requires a fresh live run (see <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>).</p>
</blockquote>
</div>
<section class="level2"><h2 id="the-data-alabama-pre-k-sites">The data: Alabama Pre-K sites<a class="anchor" aria-label="anchor" href="#the-data-alabama-pre-k-sites"></a>
</h2>
<p>A production run starts from a small table of program sites. The bundled <code>cacs_alabama_sites</code> shows the shape that table needs: a stable site identifier, a display name, a county FIPS code, a region label, and a single point geometry in EPSG:4326. These ten sites are the live-run template — coordinates are jittered and names are anonymized — so you can swap in your own administrative site list with the same columns and nothing else changes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">cacs_alabama_sites</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html" class="external-link">st_drop_geometry</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">site_name</span>, <span class="va">county_fips</span>, <span class="va">region_label</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      site_id      site_name county_fips     region_label
1  AL_SITE_01  Sample Site 1       01073 Birmingham Metro
2  AL_SITE_02  Sample Site 2       01097      South Coast
3  AL_SITE_03  Sample Site 3       01089            North
4  AL_SITE_04  Sample Site 4       01101          Central
5  AL_SITE_05  Sample Site 5       01125     West Central
6  AL_SITE_06  Sample Site 6       01081     East Central
7  AL_SITE_07  Sample Site 7       01103    North Central
8  AL_SITE_08  Sample Site 8       01077        Northwest
9  AL_SITE_09  Sample Site 9       01069        Southeast
10 AL_SITE_10 Sample Site 10       01055        Northeast</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html" class="external-link">st_geometry</a></span><span class="op">(</span><span class="va">cacs_alabama_sites</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 10 features
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -88.0382 ymin: 30.68891 xmax: -85.38495 ymax: 34.79879
Geodetic CRS:  WGS 84
First 5 geometries:</code></pre>
</div>
</div>
<p>One bookkeeping note. <code>cacs_alabama_sites</code> is the live-run <em>template</em>; the executable path in this article instead uses the interlocking <code>legacy_2025_*</code> fixtures, because those carry the precomputed isochrones and the matching frozen baseline that let the whole document render offline and deterministically. So that the intermediate tables below stay small enough to read, the walkthrough uses three legacy sites — one northern, one north-central, one northwest — at drive times of 5, 10, and 15 minutes. The reasoning is identical for the full ten-site batch.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">site_ids</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"AL_SITE_03"</span>, <span class="st">"AL_SITE_07"</span>, <span class="st">"AL_SITE_08"</span><span class="op">)</span></span></code></pre></div>
</div>
</section><section class="level2"><h2 id="the-pipeline-one-stage-at-a-time">The pipeline, one stage at a time<a class="anchor" aria-label="anchor" href="#the-pipeline-one-stage-at-a-time"></a>
</h2>
<p><code><a href="../reference/cacs_run.html">cacs_run()</a></code> orchestrates five functions in sequence. The first two reach the network; the last three are pure local computation on whatever those two returned:</p>
<blockquote>
<p><code><a href="../reference/cacs_acs_prefetch.html">cacs_acs_prefetch()</a></code> (ACS download) → <code><a href="../reference/cacs_isochrone.html">cacs_isochrone()</a></code> (routing) → <code><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight()</a></code> → <code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code> → <code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code>.</p>
</blockquote>
<p>This section runs each stage on its own so you can see the object that moves between them — and so you can lift any stage out as a standalone manuscript figure.</p>
<section class="level3"><h3 id="stages-1-and-2-are-network-operations-shown-not-run">Stages 1 and 2 are network operations (shown, not run)<a class="anchor" aria-label="anchor" href="#stages-1-and-2-are-network-operations-shown-not-run"></a>
</h3>
<p>In a live run you would fetch statewide ACS tracts and draw drive-time isochrones like this. Both forms are shown for reference and are <strong>not executed</strong> here, because each would make a network request:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Live form (needs a Census API key and network access):</span></span>
<span><span class="va">acs</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_acs_prefetch.html">cacs_acs_prefetch</a></span><span class="op">(</span>state <span class="op">=</span> <span class="st">"AL"</span>, year <span class="op">=</span> <span class="fl">2023</span><span class="op">)</span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Live form (needs a routing provider; the OSRM public demo needs no key):</span></span>
<span><span class="va">iso</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_isochrone.html">cacs_isochrone</a></span><span class="op">(</span></span>
<span>  sites       <span class="op">=</span> <span class="va">cacs_alabama_sites</span>,</span>
<span>  drive_times <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span><span class="op">)</span>,</span>
<span>  provider    <span class="op">=</span> <span class="st">"osrm"</span>,</span>
<span>  osrm_mode   <span class="op">=</span> <span class="st">"demo"</span></span>
<span><span class="op">)</span></span></code></pre></div>
</div>
<p><code><a href="../reference/cacs_acs_prefetch.html">cacs_acs_prefetch()</a></code> returns an <code>sf</code> tibble of tract-level ACS estimates (<code>GEOID</code>, <code>NAME</code>, <code>variable</code>, <code>estimate</code>, <code>moe</code>, <code>geometry</code>), and <code><a href="../reference/cacs_isochrone.html">cacs_isochrone()</a></code> returns one drive-time polygon per <code>(site_id, drive_time_min)</code> pair. The two bundled fixtures used below are exactly those return shapes, frozen: <code>sample_alabama_subset.rds</code> stands in for the ACS prefetch, and <code>legacy_2025_isochrones.rds</code> stands in for the isochrones. Loading them lets us run the rest of the pipeline with no network at all.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># These are exactly what stages 1 and 2 would have returned, frozen to disk.</span></span>
<span><span class="va">sites</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_sites.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">acs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"sample_alabama_subset.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">iso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_isochrones.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Restrict to our three-site working batch and three drive-time bands.</span></span>
<span><span class="va">analysis_sites</span> <span class="op">&lt;-</span> <span class="va">sites</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">site_id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="va">site_ids</span><span class="op">)</span></span>
<span><span class="va">iso</span> <span class="op">&lt;-</span> <span class="va">iso</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">site_id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="va">site_ids</span>, <span class="va">drive_time_min</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">5L</span>, <span class="fl">10L</span>, <span class="fl">15L</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span></span>
<span>  acs_dim         <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">acs</span><span class="op">)</span>,</span>
<span>  acs_crs         <span class="op">=</span> <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html" class="external-link">st_crs</a></span><span class="op">(</span><span class="va">acs</span><span class="op">)</span><span class="op">$</span><span class="va">epsg</span>,</span>
<span>  acs_variables   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">acs</span><span class="op">$</span><span class="va">variable</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  acs_tracts      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">acs</span><span class="op">$</span><span class="va">GEOID</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  iso_dim         <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">iso</span><span class="op">)</span>,</span>
<span>  iso_crs         <span class="op">=</span> <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html" class="external-link">st_crs</a></span><span class="op">(</span><span class="va">iso</span><span class="op">)</span><span class="op">$</span><span class="va">epsg</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$acs_dim
[1] 12754     6

$acs_crs
[1] 4269

$acs_variables
[1] 14

$acs_tracts
[1] 911

$iso_dim
[1]  9 16

$iso_crs
[1] 4326</code></pre>
</div>
</div>
<p>The ACS fixture carries 14 source variables across the Alabama tracts in EPSG:4269; the isochrone fixture is a set of drive-time polygons in EPSG:4326. Those are the two coordinate systems <code><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight()</a></code> expects on input.</p>
</section><section class="level3"><h3 id="stage-3-spatial-intersection-and-area-weighting">Stage 3: spatial intersection and area weighting<a class="anchor" aria-label="anchor" href="#stage-3-spatial-intersection-and-area-weighting"></a>
</h3>
<p>This is the algorithmic heart of the package. <code><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight()</a></code> overlays each isochrone on the ACS tracts, computes how much of each tract falls inside the catchment, and aggregates the source ACS counts by that overlap. It runs fully offline:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">weighted</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight</a></span><span class="op">(</span></span>
<span>  iso_sf        <span class="op">=</span> <span class="va">iso</span>,</span>
<span>  acs_sf        <span class="op">=</span> <span class="va">acs</span>,</span>
<span>  weight_method <span class="op">=</span> <span class="st">"area"</span>,</span>
<span>  verbose       <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">weighted</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 126  23</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">weighted</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">weight_sum</span>, <span class="va">n_tracts</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="fl">8</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 6
  site_id    drive_time_min variable   estimate weight_sum n_tracts
  &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;      &lt;dbl&gt;    &lt;int&gt;
1 AL_SITE_03              5 B01003_001       NA          1        1
2 AL_SITE_03              5 B11001_001     1625          1        1
3 AL_SITE_03              5 B17001_001     3896          1        1
4 AL_SITE_03              5 B17001_002     1016          1        1
5 AL_SITE_03              5 B19013_001    44119          1        1
6 AL_SITE_03              5 B19056_001     1322          1        1
7 AL_SITE_03              5 B19056_002      133          1        1
8 AL_SITE_03              5 B19301_001    22934          1        1</code></pre>
</div>
</div>
<p>Two columns are worth reading closely. <code>n_tracts</code> is how many tracts the catchment touched — your sample thickness. <code>weight_sum</code> is the sum of the tract area weights that went into the aggregate; each weight is the fraction of a tract’s area lying inside the catchment, <span class="math inline">\text{coverage\_wt}_j = \text{area}(\text{catchment} \cap \text{tract}_j) / \text{area}(\text{tract}_j)</span>. Because catchments slice through tract boundaries, <code>weight_sum</code> is generally not a whole number — a catchment covering most of three tracts and the edge of a fourth might sum to something like 3.4. That is the answer to a reviewer who asks why the effective tract count is not an integer: tracts enter partially, in proportion to how much of their area the drive-time area covers.</p>
<p>The “Estimand families and weights” section of <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code> documents the full weighting scheme. In short, count variables (<code>spatial_total</code>) use this coverage weight directly, while scalar and proxy variables (a median-income proxy, say) use a separate normalized mean weight that sums to one within a cell. The function also attaches an internal <em>carrier</em> table — the coverage-weighted numerator and denominator totals — that the next two stages read.</p>
</section><section class="level3"><h3 id="stage-4-margin-of-error-propagation">Stage 4: margin-of-error propagation<a class="anchor" aria-label="anchor" href="#stage-4-margin-of-error-propagation"></a>
</h3>
<p>ACS estimates ship with published margins of error (MOE), and those must travel through the weighting. <code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code> attaches an MOE to every row, choosing the formula appropriate to each variable’s estimand family. It is pure computation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">with_moe</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe</a></span><span class="op">(</span><span class="va">weighted</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">with_moe</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span>,</span>
<span>         <span class="va">moe_formula_effective</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="fl">8</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 6
  site_id    drive_time_min variable   estimate   moe moe_formula_effective
  &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
1 AL_SITE_03              5 B01003_001       NA    NA weighted_sum
2 AL_SITE_03              5 B11001_001     1625   327 weighted_sum
3 AL_SITE_03              5 B17001_001     3896   599 weighted_sum
4 AL_SITE_03              5 B17001_002     1016   153 weighted_sum
5 AL_SITE_03              5 B19013_001    44119  9333 weighted_mean
6 AL_SITE_03              5 B19056_001     1322   225 weighted_sum
7 AL_SITE_03              5 B19056_002      133    27 weighted_sum
8 AL_SITE_03              5 B19301_001    22934  5685 weighted_mean        </code></pre>
</div>
</div>
<p>A margin of error is the half-width of a 90% confidence interval — you report a value as <code>estimate ± moe</code>, exactly as the Census Bureau reports ACS figures. This stage does not recompute the point estimates; it fills in <code>moe</code> and records, per row, which formula was used (<code>moe_formula_effective</code>) and whether any fallback was needed (<code>moe_fallback</code>, <code>moe_fallback_reason</code>). We do not re-derive those formulas here — the four families and the never-silent fallback rule are documented in <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code> and <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>.</p>
<p>One diagnostic habit: a non-trivial <code>moe_fallback_reason</code> is an audit signal, not an error. It records that a requested formula could not produce a value for a cell (for example a zero denominator or a missing input MOE) so the run stays transparent. In this intentionally clean mini-batch no fallback fires:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">with_moe</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">moe_fallback_reason</span> <span class="op">!=</span> <span class="st">"n/a"</span> <span class="op">|</span> <span class="va">failure_origin</span> <span class="op">!=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section><section class="level3"><h3 id="stage-5-derive-the-curated-rates">Stage 5: derive the curated rates<a class="anchor" aria-label="anchor" href="#stage-5-derive-the-curated-rates"></a>
</h3>
<p>Finally, <code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code> appends the five curated catchment rates as new <code>derived_rate</code> rows beneath the source-variable rows, each as a ratio of area-weighted ACS totals with its own propagated MOE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">final</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/warning.html" class="external-link">suppressWarnings</a></span><span class="op">(</span><span class="fu"><a href="../reference/cacs_derive_rates.html">cacs_derive_rates</a></span><span class="op">(</span><span class="va">with_moe</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">final</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 171  27</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">final</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">estimand_family</span> <span class="op">==</span> <span class="st">"derived_rate"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span>,</span>
<span>         <span class="va">moe_formula_effective</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   site_id    drive_time_min variable      estimate    moe moe_formula_effective
   &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;
 1 AL_SITE_03              5 labor_force_…   0.323  0.0551 general_ratio_conser…
 2 AL_SITE_03              5 poverty_rate    0.261  0.0561 general_ratio_conser…
 3 AL_SITE_03              5 snap_rate       0.441  0.118  general_ratio_conser…
 4 AL_SITE_03              5 ssi_rate        0.101  0.0267 general_ratio_conser…
 5 AL_SITE_03              5 unemp_rate      0.0939 0.0238 general_ratio_conser…
 6 AL_SITE_03             10 labor_force_…   0.323  0.0551 general_ratio_conser…
 7 AL_SITE_03             10 poverty_rate    0.261  0.0561 general_ratio_conser…
 8 AL_SITE_03             10 snap_rate       0.441  0.118  general_ratio_conser…
 9 AL_SITE_03             10 ssi_rate        0.101  0.0267 general_ratio_conser…
10 AL_SITE_03             10 unemp_rate      0.0939 0.0238 general_ratio_conser…</code></pre>
</div>
</div>
<p>Each rate maps to an ACS numerator/denominator pair and to a policy reading:</p>
<table class="table caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Rate</th>
<th>ACS source</th>
<th>Policy reading</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>poverty_rate</code></td>
<td><code>B17001_002 / B17001_001</code></td>
<td>Catchment poverty — a demand-side proxy for Pre-K need</td>
</tr>
<tr class="even">
<td><code>snap_rate</code></td>
<td><code>B22003_002 / B22003_001</code></td>
<td>SNAP receipt — an administrative cross-check on household income stress</td>
</tr>
<tr class="odd">
<td><code>ssi_rate</code></td>
<td><code>B19056_002 / B19056_001</code></td>
<td>Households with Supplemental Security Income — an equity dimension for disability/elderly-caregiver households</td>
</tr>
<tr class="even">
<td><code>unemp_rate</code></td>
<td><code>B23025_005 / B23025_003</code></td>
<td>Unemployment — parental labor-market attachment</td>
</tr>
<tr class="odd">
<td><code>labor_force_participation</code></td>
<td><code>B23025_002 / B23025_001</code></td>
<td>Labor force participation — a supply-side (childcare-demand) proxy</td>
</tr>
</tbody>
</table>
<p>The MOE formula for each rate is selected by <code><a href="../reference/cacs_derive_rates.html">cacs_derive_rates()</a></code>’s <code>formula_dispatch</code> argument. Under the package’s baseline policy, <code>poverty_rate</code> and <code>labor_force_participation</code> are C1-eligible (the <code>proportion_subset</code> form, valid when the numerator is a true subset of the denominator), while <code>snap_rate</code>, <code>ssi_rate</code>, and <code>unemp_rate</code> are routed to C2 (<code>general_ratio_conservative</code>). A C1 rate whose subset variance comes out negative falls back to C2 for that cell, with the override recorded in <code>moe_fallback</code>, <code>moe_fallback_reason</code>, and <code>moe_formula_effective</code>. The full dispatch contract lives in <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code> and <code><a href="../reference/cacs_derive_rates.html">?cacs_derive_rates</a></code>.</p>
</section></section><section class="level2"><h2 id="recompose-into-one-call">Recompose into one call<a class="anchor" aria-label="anchor" href="#recompose-into-one-call"></a>
</h2>
<p>The five stages above are exactly what <code><a href="../reference/cacs_run.html">cacs_run()</a></code> does internally. Supplying both <code>precomputed_isochrones =</code> and <code>acs =</code> tells it to skip the two network stages and use the fixtures we loaded, so this one call reproduces the manual chain offline — no requests, no key:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">result</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_run.html">cacs_run</a></span><span class="op">(</span></span>
<span>  sites                  <span class="op">=</span> <span class="va">analysis_sites</span>,</span>
<span>  state                  <span class="op">=</span> <span class="st">"AL"</span>,</span>
<span>  year                   <span class="op">=</span> <span class="fl">2023</span>,</span>
<span>  drive_times            <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span><span class="op">)</span>,</span>
<span>  variables              <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html" class="external-link">unname</a></span><span class="op">(</span><span class="va">cacs_acs_default_vars</span><span class="op">)</span>,</span>
<span>  provider               <span class="op">=</span> <span class="st">"osrm"</span>,</span>
<span>  precomputed_isochrones <span class="op">=</span> <span class="va">iso</span>,</span>
<span>  acs                    <span class="op">=</span> <span class="va">acs</span>,</span>
<span>  weight_method          <span class="op">=</span> <span class="st">"area"</span>,</span>
<span>  output                 <span class="op">=</span> <span class="st">"long"</span>,</span>
<span>  verbose                <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/class.html" class="external-link">class</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "cacs_run_result" "tbl_df"          "tbl"             "data.frame"     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 171  27</code></pre>
</div>
</div>
<p>The provenance attribute confirms the path taken: both inputs were supplied, so the orchestrator ran the 3-call path (validation, intersection/weighting, MOE propagation, rate derivation, output assembly) with no network.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">result</span>, <span class="st">"cacs_run_provenance"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html" class="external-link">as.data.frame</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">execution_path</span>, <span class="va">provider</span>, <span class="va">state</span>, <span class="va">year</span>,</span>
<span>         <span class="va">weight_method</span>, <span class="va">formula_dispatch</span>, <span class="va">bypass_iso</span>, <span class="va">bypass_acs</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  execution_path provider state year weight_method           formula_dispatch
1         3-call     osrm    AL 2023          area general_ratio_conservative
2         3-call     osrm    AL 2023          area general_ratio_conservative
3         3-call     osrm    AL 2023          area general_ratio_conservative
  bypass_iso bypass_acs
1       TRUE       TRUE
2       TRUE       TRUE
3       TRUE       TRUE</code></pre>
</div>
</div>
<p>And the result is identical to the hand-built chain — not merely close. Comparing the two estimate columns on the same <code>(site_id, drive_time_min, variable)</code> keys:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">manual</span> <span class="op">&lt;-</span> <span class="va">final</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span><span class="op">)</span></span>
<span><span class="va">oneshot</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html" class="external-link">as_tibble</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  same_nrow      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">manual</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">oneshot</span><span class="op">)</span>,</span>
<span>  max_estimate_d <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html" class="external-link">max</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">manual</span><span class="op">$</span><span class="va">estimate</span> <span class="op">-</span> <span class="va">oneshot</span><span class="op">$</span><span class="va">estimate</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>  max_moe_d      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html" class="external-link">max</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">manual</span><span class="op">$</span><span class="va">moe</span> <span class="op">-</span> <span class="va">oneshot</span><span class="op">$</span><span class="va">moe</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     same_nrow max_estimate_d      max_moe_d
             1              0              0 </code></pre>
</div>
</div>
<p>That zero is the point of the first half of this exercise: the readable five-stage decomposition and the single production call are the same computation. In daily work you write the one line; the five stages are what you cite in a methods section. The rest of the article works from <code>result</code>.</p>
</section><section class="level2"><h2 id="reporting-ready-outputs">Reporting-ready outputs<a class="anchor" aria-label="anchor" href="#reporting-ready-outputs"></a>
</h2>
<p>This is the part that matters at hand-off. Everything below is a deliverable an equity researcher can drop into a memo, a dissertation chapter, or a journal submission — and each maps to a concrete reporting need.</p>
<section class="level3"><h3 id="select-the-analyst-facing-columns">Select the analyst-facing columns<a class="anchor" aria-label="anchor" href="#select-the-analyst-facing-columns"></a>
</h3>
<p><code>result</code> is one tidy <em>long</em> table — one row per site, drive-time band, and variable — carrying provenance and audit fields that are useful when you share results and ignorable otherwise. Most daily analysis starts from a handful of columns, so name them once and reuse the selection. Read <code>failure_origin</code> first: <code>"none"</code> is your success flag for that cell.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">result_tbl</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html" class="external-link">as_tibble</a></span><span class="op">(</span><span class="va">result</span>, rate_first <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">report_cols</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"site_id"</span>, <span class="st">"drive_time_min"</span>, <span class="st">"variable"</span>,</span>
<span>  <span class="st">"estimate"</span>, <span class="st">"moe"</span>, <span class="st">"n_tracts"</span>, <span class="st">"failure_origin"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">result_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/all_of.html" class="external-link">all_of</a></span><span class="op">(</span><span class="va">report_cols</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 7
   site_id    drive_time_min variable   estimate   moe n_tracts failure_origin
   &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;    &lt;int&gt; &lt;chr&gt;
 1 AL_SITE_03              5 B01003_001       NA    NA        1 none
 2 AL_SITE_03              5 B11001_001     1625   327        1 none
 3 AL_SITE_03              5 B17001_001     3896   599        1 none
 4 AL_SITE_03              5 B17001_002     1016   153        1 none
 5 AL_SITE_03              5 B19013_001    44119  9333        1 none
 6 AL_SITE_03              5 B19056_001     1322   225        1 none
 7 AL_SITE_03              5 B19056_002      133    27        1 none
 8 AL_SITE_03              5 B19301_001    22934  5685        1 none
 9 AL_SITE_03              5 B22003_001      810   183        1 none
10 AL_SITE_03              5 B22003_002      357    51        1 none
11 AL_SITE_03              5 B23025_001     3386   366        1 none
12 AL_SITE_03              5 B23025_002     1095   144        1 none          </code></pre>
</div>
</div>
<p>This batch is intentionally clean, so every rate succeeds. In a larger live run, when a derived rate comes back <code>NA</code>, <code>failure_origin</code> names the stage that produced the gap — an upstream ACS input, an isochrone failure, an empty intersection, or a missing aggregation carrier — so you can diagnose rather than guess. The <code>estimate</code> for a rate is a proportion: <code>0.173</code> means 17.3%.</p>
</section><section class="level3"><h3 id="the-site-x-drive-time-rate-matrix">The site x drive-time rate matrix<a class="anchor" aria-label="anchor" href="#the-site-x-drive-time-rate-matrix"></a>
</h3>
<p>The most compact deliverable is one row per site and drive time with all five curated rates side by side. Pivoting the long table wide gives exactly the shape of a manuscript table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rate_matrix</span> <span class="op">&lt;-</span> <span class="va">result_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span></span>
<span>    <span class="va">variable</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">cacs_acs_default_rates</span><span class="op">)</span>,</span>
<span>    <span class="va">failure_origin</span> <span class="op">==</span> <span class="st">"none"</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span>, <span class="va">estimate</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html" class="external-link">pivot_wider</a></span><span class="op">(</span>names_from <span class="op">=</span> <span class="va">variable</span>, values_from <span class="op">=</span> <span class="va">estimate</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rate_matrix</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 7
  site_id    drive_time_min poverty_rate snap_rate ssi_rate unemp_rate
  &lt;chr&gt;               &lt;int&gt;        &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
1 AL_SITE_03              5        0.261    0.441    0.101      0.0939
2 AL_SITE_03             10        0.261    0.441    0.101      0.0939
3 AL_SITE_03             15        0.255    0.251    0.0852     0.0664
4 AL_SITE_07              5        0.618    0.0399   0.167      0.0620
5 AL_SITE_07             10        0.602    0.0426   0.165      0.0630
6 AL_SITE_07             15        0.360    0.111    0.124      0.0922
7 AL_SITE_08              5        0.457    0.334    0.0626     0.0331
8 AL_SITE_08             10        0.428    0.315    0.0636     0.0378
9 AL_SITE_08             15        0.182    0.182    0.0772     0.117
# ℹ 1 more variable: labor_force_participation &lt;dbl&gt;</code></pre>
</div>
</div>
<p>This is the analyst’s primary worktable: every site at every catchment band, with the five rates as columns. For a reader-facing version that pairs each rate with its uncertainty, <code><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary()</a></code> reshapes the same numbers into one row per site and drive time, each rate formatted as <code>estimate ± MOE</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span><span class="op">$</span><span class="va">rates_per_site_moe</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 7
  site_id    drive_time_min poverty_rate  snap_rate     ssi_rate      unemp_rate
  &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;         &lt;chr&gt;         &lt;chr&gt;         &lt;chr&gt;
1 AL_SITE_03              5 0.261 ± 0.056 0.441 ± 0.118 0.101 ± 0.027 0.094 ± 0…
2 AL_SITE_03             10 0.261 ± 0.056 0.441 ± 0.118 0.101 ± 0.027 0.094 ± 0…
3 AL_SITE_03             15 0.255 ± 0.035 0.251 ± 0.034 0.085 ± 0.011 0.066 ± 0…
4 AL_SITE_07              5 0.618 ± 0.104 0.040 ± 0.006 0.167 ± 0.037 0.062 ± 0…
5 AL_SITE_07             10 0.602 ± 0.098 0.043 ± 0.006 0.165 ± 0.036 0.063 ± 0…
6 AL_SITE_07             15 0.360 ± 0.047 0.111 ± 0.012 0.124 ± 0.017 0.092 ± 0…
7 AL_SITE_08              5 0.457 ± 0.142 0.334 ± 0.077 0.063 ± 0.017 0.033 ± 0…
8 AL_SITE_08             10 0.428 ± 0.125 0.315 ± 0.069 0.064 ± 0.016 0.038 ± 0…
9 AL_SITE_08             15 0.182 ± 0.030 0.182 ± 0.026 0.077 ± 0.011 0.117 ± 0…
# ℹ 1 more variable: labor_force_participation &lt;chr&gt;</code></pre>
</div>
</div>
<p>If a <code>&lt;NA&gt;</code> cell appears in a larger run, it is not a formatting error: it means the package could not form a stable numerator/denominator pair for that rate in that cell. Keep such cells visible in review tables rather than overwriting them with zero — a missing rate is a diagnostic, not an absence of need.</p>
</section><section class="level3"><h3 id="a-15-minute-priority-table">A 15-minute priority table<a class="anchor" aria-label="anchor" href="#a-15-minute-priority-table"></a>
</h3>
<p>A common policy task is to rank sites by need at the widest catchment. Here we sort the three sites by their 15-minute poverty rate, highest first — the kind of ordering that drives a “where to invest next” conversation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">priority_15</span> <span class="op">&lt;-</span> <span class="va">result_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span></span>
<span>    <span class="va">drive_time_min</span> <span class="op">==</span> <span class="fl">15</span>,</span>
<span>    <span class="va">variable</span> <span class="op">==</span> <span class="st">"poverty_rate"</span>,</span>
<span>    <span class="va">failure_origin</span> <span class="op">==</span> <span class="st">"none"</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html" class="external-link">desc</a></span><span class="op">(</span><span class="va">estimate</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html" class="external-link">transmute</a></span><span class="op">(</span></span>
<span>    rank         <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/row_number.html" class="external-link">row_number</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    <span class="va">site_id</span>,</span>
<span>    poverty_rate <span class="op">=</span> <span class="va">estimate</span>,</span>
<span>    moe_90       <span class="op">=</span> <span class="va">moe</span>,</span>
<span>    <span class="va">n_tracts_num</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">priority_15</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
   rank site_id    poverty_rate moe_90 n_tracts_num
  &lt;int&gt; &lt;chr&gt;             &lt;dbl&gt;  &lt;dbl&gt;        &lt;int&gt;
1     1 AL_SITE_07        0.360 0.0472            3
2     2 AL_SITE_03        0.255 0.0351            3
3     3 AL_SITE_08        0.182 0.0296            3</code></pre>
</div>
</div>
<p>The estimate stays a proportion; multiply by 100 only at the final formatting step so any downstream arithmetic remains stable. Swap <code>poverty_rate</code> for <code>snap_rate</code> or <code>unemp_rate</code> to rank on a different indicator, or change <code>drive_time_min</code> to compare priorities at a tighter band.</p>
</section><section class="level3"><h3 id="a-focal-site-profile">A focal-site profile<a class="anchor" aria-label="anchor" href="#a-focal-site-profile"></a>
</h3>
<p>For a single-site memo the question is different: not “which site ranks highest?” but “how does this one site change as its catchment grows from 5 to 15 minutes?” The profile below shows all five curated rates across the three rings for one focal site, each with its margin of error and the implied confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">focal_site</span> <span class="op">&lt;-</span> <span class="st">"AL_SITE_03"</span></span>
<span></span>
<span><span class="va">result_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span></span>
<span>    <span class="va">site_id</span> <span class="op">==</span> <span class="va">focal_site</span>,</span>
<span>    <span class="va">variable</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">cacs_acs_default_rates</span><span class="op">)</span>,</span>
<span>    <span class="va">failure_origin</span> <span class="op">==</span> <span class="st">"none"</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">drive_time_min</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html" class="external-link">transmute</a></span><span class="op">(</span></span>
<span>    <span class="va">variable</span>,</span>
<span>    <span class="va">drive_time_min</span>,</span>
<span>    <span class="va">estimate</span>,</span>
<span>    moe_90  <span class="op">=</span> <span class="va">moe</span>,</span>
<span>    ci_low  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html" class="external-link">pmax</a></span><span class="op">(</span><span class="va">estimate</span> <span class="op">-</span> <span class="va">moe</span>, <span class="fl">0</span><span class="op">)</span>,</span>
<span>    ci_high <span class="op">=</span> <span class="va">estimate</span> <span class="op">+</span> <span class="va">moe</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 6
   variable                  drive_time_min estimate  moe_90 ci_low ci_high
   &lt;chr&gt;                              &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1 labor_force_participation              5   0.323  0.0551  0.268   0.378
 2 labor_force_participation             10   0.323  0.0551  0.268   0.378
 3 labor_force_participation             15   0.536  0.0739  0.462   0.610
 4 poverty_rate                           5   0.261  0.0561  0.205   0.317
 5 poverty_rate                          10   0.261  0.0561  0.205   0.317
 6 poverty_rate                          15   0.255  0.0351  0.220   0.291
 7 snap_rate                              5   0.441  0.118   0.323   0.559
 8 snap_rate                             10   0.441  0.118   0.323   0.559
 9 snap_rate                             15   0.251  0.0345  0.216   0.285
10 ssi_rate                               5   0.101  0.0267  0.0740  0.127
11 ssi_rate                              10   0.101  0.0267  0.0740  0.127
12 ssi_rate                              15   0.0852 0.0113  0.0740  0.0965
13 unemp_rate                             5   0.0939 0.0238  0.0701  0.118
14 unemp_rate                            10   0.0939 0.0238  0.0701  0.118
15 unemp_rate                            15   0.0664 0.00838 0.0580  0.0748</code></pre>
</div>
</div>
<p>Reporting each rate as <code>estimate ± moe_90</code> (or as the <code>[ci_low, ci_high]</code> interval shown here) is the same convention the Census Bureau uses for ACS figures, so a reviewer can read the catchment numbers exactly as they would read a published table.</p>
</section><section class="level3"><h3 id="an-exportable-report-tibble">An exportable report tibble<a class="anchor" aria-label="anchor" href="#an-exportable-report-tibble"></a>
</h3>
<p>Finally, reduce the object to a clean, CSV-ready table. Keep the MOE, the failure flag, and the effective MOE formula alongside the estimate so a reviewer can trace both uncertainty and any fallback behavior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">export_tbl</span> <span class="op">&lt;-</span> <span class="va">result_tbl</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">cacs_acs_default_rates</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html" class="external-link">transmute</a></span><span class="op">(</span></span>
<span>    <span class="va">site_id</span>,</span>
<span>    <span class="va">drive_time_min</span>,</span>
<span>    <span class="va">variable</span>,</span>
<span>    <span class="va">estimate</span>,</span>
<span>    moe_90                <span class="op">=</span> <span class="va">moe</span>,</span>
<span>    estimate_pct          <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> <span class="va">estimate</span>,</span>
<span>    moe_90_pct            <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> <span class="va">moe</span>,</span>
<span>    <span class="va">failure_origin</span>,</span>
<span>    <span class="va">moe_formula_effective</span>,</span>
<span>    <span class="va">moe_fallback</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="va">export_tbl</span>, <span class="fl">15</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 10
   site_id    drive_time_min variable   estimate  moe_90 estimate_pct moe_90_pct
   &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
 1 AL_SITE_03              5 labor_for…   0.323  0.0551         32.3       5.51
 2 AL_SITE_03              5 poverty_r…   0.261  0.0561         26.1       5.61
 3 AL_SITE_03              5 snap_rate    0.441  0.118          44.1      11.8
 4 AL_SITE_03              5 ssi_rate     0.101  0.0267         10.1       2.67
 5 AL_SITE_03              5 unemp_rate   0.0939 0.0238          9.39      2.38
 6 AL_SITE_03             10 labor_for…   0.323  0.0551         32.3       5.51
 7 AL_SITE_03             10 poverty_r…   0.261  0.0561         26.1       5.61
 8 AL_SITE_03             10 snap_rate    0.441  0.118          44.1      11.8
 9 AL_SITE_03             10 ssi_rate     0.101  0.0267         10.1       2.67
10 AL_SITE_03             10 unemp_rate   0.0939 0.0238          9.39      2.38
11 AL_SITE_03             15 labor_for…   0.536  0.0739         53.6       7.39
12 AL_SITE_03             15 poverty_r…   0.255  0.0351         25.5       3.51
13 AL_SITE_03             15 snap_rate    0.251  0.0345         25.1       3.45
14 AL_SITE_03             15 ssi_rate     0.0852 0.0113          8.52      1.13
15 AL_SITE_03             15 unemp_rate   0.0664 0.00838         6.64      0.838
# ℹ 3 more variables: failure_origin &lt;chr&gt;, moe_formula_effective &lt;chr&gt;,
#   moe_fallback &lt;lgl&gt;</code></pre>
</div>
</div>
<p>You would write this out with, for example, <code>readr::write_csv(export_tbl, "alabama_prek_rates.csv")</code>. Before publishing any narrative claim, filter or flag rows where <code>failure_origin != "none"</code>: a missing rate may still be a useful diagnostic, but it must not be read as zero.</p>
</section></section><section class="level2"><h2 id="reproducibility-and-the-frozen-baseline">Reproducibility and the frozen baseline<a class="anchor" aria-label="anchor" href="#reproducibility-and-the-frozen-baseline"></a>
</h2>
<p>The package ships a frozen regression baseline, <code>legacy_2025_golden_output.rds</code>: the full ten-site, three-band <code><a href="../reference/cacs_run.html">cacs_run()</a></code> result captured once and committed to <code>inst/extdata</code>. Its role is to anchor reproducibility — the test suite recomputes the pipeline and verifies it against this baseline at a tight numerical tolerance, so an accidental change in any stage’s arithmetic is caught before release.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">golden</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_golden_output.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span></span>
<span>  class          <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/class.html" class="external-link">class</a></span><span class="op">(</span><span class="va">golden</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>,</span>
<span>  dim            <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">golden</span><span class="op">)</span>,</span>
<span>  n_sites        <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">golden</span><span class="op">$</span><span class="va">site_id</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  drive_times    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sort.html" class="external-link">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">golden</span><span class="op">$</span><span class="va">drive_time_min</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$class
[1] "cacs_run_result"

$dim
[1] 1080   20

$n_sites
[1] 20

$drive_times
[1]  5 10 15</code></pre>
</div>
</div>
<p>Its provenance records how it was produced — the same <code><a href="../reference/cacs_run.html">cacs_run()</a></code> contract, captured on the 3-call (fixtures-only) path:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">golden</span>, <span class="st">"cacs_run_provenance"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html" class="external-link">as.data.frame</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">execution_path</span>, <span class="va">state</span>, <span class="va">year</span>, <span class="va">weight_method</span>,</span>
<span>         <span class="va">formula_dispatch</span>, <span class="va">output_format</span>, <span class="va">level</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  execution_path state year weight_method           formula_dispatch
1         3-call    AL 2023          area general_ratio_conservative
2         3-call    AL 2023          area general_ratio_conservative
3         3-call    AL 2023          area general_ratio_conservative
  output_format level
1          long   0.9
2          long   0.9
3          long   0.9</code></pre>
</div>
</div>
<p>What the guarantee means for you in practice: if you re-run the package on these bundled inputs and the recomputed estimates match the baseline within tolerance, your install reproduces the reference numbers exactly. That is the user-facing form of the regression check the maintainers run in CI — you can port a 2025-era analysis script onto this API and confirm the numbers did not move. A literal row-by-row comparison is only meaningful when it runs in a clean, offline-stable environment matching the one that produced the golden file (the same package version and spatial-library stack). The three-site batch above is a deliberately small slice for teaching, not the full-roster object the golden file records, so this article shows the baseline’s shape and provenance rather than asserting a numeric diff; the faithful comparison belongs in the test suite, which performs it at the locked tolerance.</p>
</section><section class="level2"><h2 id="a-map">A map<a class="anchor" aria-label="anchor" href="#a-map"></a>
</h2>
<p>With the optional <code>leaflet</code> package installed, you can see one site’s 15-minute catchment over its intersecting tracts. This chunk is gated on the namespace, so it is simply skipped when <code>leaflet</code> is absent, and it calls <code>leaflet::</code> rather than attaching the package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Focal site point and its 15-minute ring (both EPSG:4326).</span></span>
<span><span class="va">focal_pt</span>   <span class="op">&lt;-</span> <span class="va">analysis_sites</span><span class="op">[</span><span class="va">analysis_sites</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">focal_site</span>, <span class="op">]</span></span>
<span><span class="va">focal_ring</span> <span class="op">&lt;-</span> <span class="va">iso</span><span class="op">[</span><span class="va">iso</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">focal_site</span> <span class="op">&amp;</span> <span class="va">iso</span><span class="op">$</span><span class="va">drive_time_min</span> <span class="op">==</span> <span class="fl">15</span>, <span class="op">]</span></span>
<span></span>
<span><span class="co"># Build a tract-level poverty rate from the source ACS counts, then keep only</span></span>
<span><span class="co"># the tracts the 15-minute ring touches. Everything stays offline.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html" class="external-link">suppressMessages</a></span><span class="op">(</span><span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/s2.html" class="external-link">sf_use_s2</a></span><span class="op">(</span><span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pov</span> <span class="op">&lt;-</span> <span class="va">acs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html" class="external-link">st_drop_geometry</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"B17001_001"</span>, <span class="st">"B17001_002"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span>, <span class="va">variable</span>, <span class="va">estimate</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html" class="external-link">pivot_wider</a></span><span class="op">(</span></span>
<span>    id_cols <span class="op">=</span> <span class="va">GEOID</span>, names_from <span class="op">=</span> <span class="va">variable</span>, values_from <span class="op">=</span> <span class="va">estimate</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html" class="external-link">transmute</a></span><span class="op">(</span><span class="va">GEOID</span>, poverty_rate <span class="op">=</span> <span class="va">B17001_002</span> <span class="op">/</span> <span class="va">B17001_001</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tract_geom</span> <span class="op">&lt;-</span> <span class="va">acs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">==</span> <span class="st">"B17001_001"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">pov</span>, by <span class="op">=</span> <span class="st">"GEOID"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html" class="external-link">st_transform</a></span><span class="op">(</span><span class="fl">4326</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hit</span> <span class="op">&lt;-</span> <span class="va">tract_geom</span><span class="op">[</span></span>
<span>  <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/geos_binary_pred.html" class="external-link">st_intersects</a></span><span class="op">(</span><span class="va">tract_geom</span>, <span class="va">focal_ring</span>, sparse <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>,</span>
<span><span class="op">]</span></span>
<span></span>
<span><span class="va">pal</span> <span class="op">&lt;-</span> <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/colorNumeric.html" class="external-link">colorNumeric</a></span><span class="op">(</span><span class="st">"YlOrRd"</span>, domain <span class="op">=</span> <span class="va">hit</span><span class="op">$</span><span class="va">poverty_rate</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/leaflet.html" class="external-link">leaflet</a></span><span class="op">(</span><span class="va">hit</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/addProviderTiles.html" class="external-link">addProviderTiles</a></span><span class="op">(</span><span class="st">"CartoDB.Positron"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/map-layers.html" class="external-link">addPolygons</a></span><span class="op">(</span></span>
<span>    fillColor <span class="op">=</span> <span class="op">~</span><span class="fu">pal</span><span class="op">(</span><span class="va">poverty_rate</span><span class="op">)</span>, fillOpacity <span class="op">=</span> <span class="fl">0.6</span>,</span>
<span>    weight <span class="op">=</span> <span class="fl">0.5</span>, color <span class="op">=</span> <span class="st">"#666666"</span>,</span>
<span>    label <span class="op">=</span> <span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/base/sprintf.html" class="external-link">sprintf</a></span><span class="op">(</span><span class="st">"Tract %s: %.1f%%"</span>, <span class="va">GEOID</span>, <span class="fl">100</span> <span class="op">*</span> <span class="va">poverty_rate</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/map-layers.html" class="external-link">addPolygons</a></span><span class="op">(</span></span>
<span>    data <span class="op">=</span> <span class="va">focal_ring</span>, fill <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>    weight <span class="op">=</span> <span class="fl">2</span>, opacity <span class="op">=</span> <span class="fl">0.8</span>, color <span class="op">=</span> <span class="st">"#c05621"</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/map-layers.html" class="external-link">addCircleMarkers</a></span><span class="op">(</span></span>
<span>    data <span class="op">=</span> <span class="va">focal_pt</span>, radius <span class="op">=</span> <span class="fl">5</span>, color <span class="op">=</span> <span class="st">"#2b6cb0"</span>,</span>
<span>    fillOpacity <span class="op">=</span> <span class="fl">0.9</span>, stroke <span class="op">=</span> <span class="cn">FALSE</span>, popup <span class="op">=</span> <span class="op">~</span><span class="va">site_id</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/addLegend.html" class="external-link">addLegend</a></span><span class="op">(</span></span>
<span>    pal <span class="op">=</span> <span class="va">pal</span>, values <span class="op">=</span> <span class="op">~</span><span class="va">poverty_rate</span>,</span>
<span>    title <span class="op">=</span> <span class="st">"Tract poverty rate"</span>,</span>
<span>    labFormat <span class="op">=</span> <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/addLegend.html" class="external-link">labelFormat</a></span><span class="op">(</span>transform <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fl">100</span> <span class="op">*</span> <span class="va">x</span>, suffix <span class="op">=</span> <span class="st">"%"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="leaflet html-widget html-fill-item" id="htmlwidget-d99bf0ff3fdb92a453fe" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-d99bf0ff3fdb92a453fe">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["CartoDB.Positron",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addPolygons","args":[[[[{"lng":[-87.42,-87.39,-87.39,-87.42,-87.42],"lat":[30.84,30.84,30.87,30.87,30.84]}]],[[{"lng":[-87.3,-87.27,-87.27,-87.3,-87.3],"lat":[30.84,30.84,30.87,30.87,30.84]}]],[[{"lng":[-87.18000000000001,-87.15000000000001,-87.15000000000001,-87.18000000000001,-87.18000000000001],"lat":[30.84,30.84,30.87,30.87,30.84]}]]],null,null,{"interactive":true,"className":"","stroke":true,"color":"#666666","weight":0.5,"opacity":0.5,"fill":true,"fillColor":["#800026","#FD7133","#FFFFCC"],"fillOpacity":0.6,"smoothFactor":1,"noClip":false},null,null,["Tract 01133000101: 29.2%","Tract 01001000201: 26.1%","Tract 01003000201: 22.1%"],{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addPolygons","args":[[[[{"lng":[-87.12842465967452,-87.12940621368926,-87.13081393285955,-87.13264385350243,-87.13489085925751,-87.13754869620942,-87.14060999106557,-87.14406627232813,-87.14790799439186,-87.15212456449228,-87.15670437242193,-87.16163482292572,-87.16690237068083,-87.17249255776008,-87.17839005347285,-87.18457869647199,-87.19104153901043,-87.19776089322693,-87.204718379336,-87.21189497559288,-87.21927106990158,-87.22682651293007,-87.23454067259424,-87.24239248976919,-87.2503605350845,-87.25842306665777,-87.26655808861909,-87.27474341027754,-87.28295670577995,-87.29117557411074,-87.29937759928133,-87.30754041055758,-87.31564174257279,-87.32365949517492,-87.33157179285664,-87.33935704361762,-87.34699399710989,-87.35446180191774,-87.36174006182605,-87.36880889093224,-87.37564896745931,-87.38224158613031,-87.38856870896699,-87.39461301437841,-87.40035794440921,-87.40578775002035,-87.41088753427951,-87.41564329334275,-87.42004195511346,-87.4240714154698,-87.42772057195718,-87.43097935484789,-87.433838755476,-87.43629085176215,-87.43832883084902,-87.43994700877579,-87.44114084712653,-87.44190696659565,-87.44224315742048,-87.44214838664023,-87.4416228021478,-87.44066773351035,-87.43928568954263,-87.43748035262662,-87.43525656977978,-87.43262034048354,-87.42957880129312,-87.42614020725928,-87.42231391020189,-87.41811033388497,-87.41354094615201,-87.40861822809056,-87.40335564030313,-87.39776758637215,-87.39186937361463,-87.38567717123138,-87.37920796596447,-87.37247951538433,-87.36551029893624,-87.35831946688347,-87.35092678729129,-87.34335259120287,-87.33561771616472,-87.32774344826404,-87.31975146284697,-87.31166376409001,-87.30350262360179,-87.29529051823523,-87.28705006729375,-87.278803969316,-87.27057493862668,-87.26238564184042,-87.2542586345069,-87.24621629808418,-87.23828077742664,-87.23047391897147,-87.22281720980574,-87.21533171779251,-87.20803803293127,-87.20095621012277,-87.19410571350437,-87.18750536251601,-87.18117327985075,-87.17512684143821,-87.1693826286009,-87.16395638251777,-87.15886296111981,-87.15411629853594,-87.14972936719796,-87.14571414270509,-87.14208157153972,-87.13884154171669,-87.13600285643922,-87.13357321082539,-87.13155917175909,-87.12996616091061,-87.12879844096183,-87.12805910506171,-87.12775006952882,-87.12787206980727,-87.12842465967452],"lat":[30.84253354777893,30.83552000447882,30.82856004203156,30.82167272366373,30.81487690964079,30.80819120576534,30.80163391261235,30.79522297563863,30.78897593629928,30.78290988430261,30.77704141113,30.77138656494514,30.76596080701059,30.760778969728,30.75585521641195,30.75120300290259,30.74683504111852,30.74276326464415,30.73899879644201,30.73555191877331,30.73243204540528,30.72964769617685,30.72720647398893,30.72511504427818,30.72337911702754,30.72200343135921,30.72099174275098,30.72034681290698,30.72007040231053,30.72016326547692,30.72062514891919,30.72145479183153,30.72264992948874,30.72420729935336,30.72612264987406,30.72839075195367,30.73100541305645,30.73395949391905,30.73724492782193,30.74085274237141,30.74477308373644,30.74899524327761,30.75350768649899,30.75829808424808,30.7633533460831,30.76865965572025,30.77420250846855,30.77996675055502,30.78593662023581,30.79209579058694,30.79842741386004,30.80491416728707,30.81153830021251,30.81828168242647,30.82512585357173,30.83205207349035,30.83904137337661,30.84607460759688,30.85313250603719,30.86019572683659,30.86724490936189,30.8742607272802,30.88122394158307,30.88811545341655,30.89491635657152,30.90160798948877,30.90817198663447,30.91459032910244,30.92084539430264,30.92692000459466,30.93279747473147,30.93846165797761,30.94389699077221,30.94908853580986,30.9540220234159,30.95868389109928,30.96306132116802,30.96714227630055,30.97091553297053,30.97437071262754,30.97749831054523,30.98028972225172,30.9827372674671,30.98483421147726,30.98657478388256,30.98795419466642,30.98896864753738,30.98961535050476,30.9898925236582,30.98979940412751,30.98933624820841,30.9885043306487,30.98730594109537,30.98574437771511,30.98382393800503,30.98154990682151,30.97892854166182,30.97596705524134,30.97267359541758,30.96905722251886,30.96512788414412,30.96089638750665,30.95637436940225,30.95157426388804,30.94650926776634,30.94119330397183,30.93564098296813,30.92986756226396,30.92388890416537,30.91772143188323,30.91138208412264,30.90488826828179,30.89825781239243,30.89150891593906,30.88466009969322,30.87773015470443,30.87073809059047,30.86370308326987,30.85664442228259,30.84958145784412,30.84253354777893]}]]],null,null,{"interactive":true,"className":"","stroke":true,"color":"#c05621","weight":2,"opacity":0.8,"fill":false,"fillColor":"#c05621","fillOpacity":0.2,"smoothFactor":1,"noClip":false},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addCircleMarkers","args":[30.85500008246067,-87.28499999999647,5,null,null,{"interactive":true,"className":"","stroke":false,"color":"#2b6cb0","weight":5,"opacity":0.5,"fill":true,"fillColor":"#2b6cb0","fillOpacity":0.9},null,null,"AL_SITE_03",null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addLegend","args":[{"colors":["#FFFFCC , #FFEDA0 12.4265839600251%, #FED471 26.6376081772857%, #FEA848 40.8486323945463%, #FD7634 55.0596566118068%, #EF3622 69.2706808290674%, #C90923 83.4817050463279%, #8B0026 97.6927292635885%, #800026 "],"labels":["23%","24%","25%","26%","27%","28%","29%"],"na_color":null,"na_label":"NA","opacity":0.5,"position":"topright","type":"numeric","title":"Tract poverty rate","extra":{"p_1":0.1242658396002514,"p_n":0.9769272926358848},"layerId":null,"className":"info legend","group":null}]}],"limits":{"lat":[30.72007040231053,30.9898925236582],"lng":[-87.44224315742048,-87.12775006952882]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>The blue dot is the site, the orange outline is its 15-minute drive-time area, and the shaded tracts are everything that area touches, colored by tract poverty rate. This is the per-tract picture that area weighting collapses into a single catchment estimate. For a deeper map-based walkthrough, see <code><a href="../articles/visual-walkthrough.html">vignette("visual-walkthrough", package = "catchmentACS")</a></code>.</p>
</section><section class="level2"><h2 id="transition-to-a-live-run">Transition to a live run<a class="anchor" aria-label="anchor" href="#transition-to-a-live-run"></a>
</h2>
<p>To move from this offline walkthrough to current Alabama data, drop the two bypass arguments. The same <code><a href="../reference/cacs_run.html">cacs_run()</a></code> call then draws drive-time areas from the selected provider and pulls ACS variables through <code>tidycensus</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># One-time Census key setup:</span></span>
<span><span class="fu">tidycensus</span><span class="fu">::</span><span class="fu"><a href="https://walker-data.com/tidycensus/reference/census_api_key.html" class="external-link">census_api_key</a></span><span class="op">(</span><span class="st">"YOUR_KEY_HERE"</span>, install <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">live_result</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_run.html">cacs_run</a></span><span class="op">(</span></span>
<span>  sites         <span class="op">=</span> <span class="va">cacs_alabama_sites</span>,   <span class="co"># the 10 bundled sites, or your own roster</span></span>
<span>  state         <span class="op">=</span> <span class="st">"AL"</span>,</span>
<span>  year          <span class="op">=</span> <span class="fl">2023</span>,</span>
<span>  drive_times   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span><span class="op">)</span>,</span>
<span>  variables     <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html" class="external-link">unname</a></span><span class="op">(</span><span class="va">cacs_acs_default_vars</span><span class="op">)</span>,</span>
<span>  provider      <span class="op">=</span> <span class="st">"osrm"</span>,</span>
<span>  weight_method <span class="op">=</span> <span class="st">"area"</span>,</span>
<span>  output        <span class="op">=</span> <span class="st">"long"</span>,</span>
<span>  verbose       <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span></code></pre></div>
</div>
<p>A few notes for the live form:</p>
<ul>
<li>
<strong>Census key and ACS years.</strong> This release supports ACS 5-year end years 2009–2024 (2024 is the most recent vintage). A Census key is needed when the ACS request is a live cache miss or <code>force_refresh = TRUE</code>; a warm ACS cache hit, or supplying an explicit <code>acs =</code> object, needs no key.</li>
<li>
<strong>Weighting.</strong> <code>weight_method = "area"</code> is the implemented method in this release. <code>weight_method = "population"</code> is a reserved name that fails loud at the orchestrator boundary before any network or spatial work begins — it is a planned future extension, not an active path.</li>
<li>
<strong>Routing providers.</strong> <code>"osrm"</code> is implemented (the public demo endpoint needs no key but can be rate-limited), <code>"ors"</code> is implemented when the optional <code>openrouteservice</code> package and an API key are present, and <code>"mapbox"</code> and <code>"r5r"</code> are reserved fail-loud provider names.</li>
</ul></section><section class="level2"><h2 id="where-to-next">Where to next<a class="anchor" aria-label="anchor" href="#where-to-next"></a>
</h2>
<ul>
<li>
<strong>The first run, in ten minutes</strong>: <code><a href="../articles/getting-started.html">vignette("getting-started", package = "catchmentACS")</a></code>.</li>
<li>
<strong>The math</strong> behind area weighting and MOE propagation: <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>.</li>
<li>
<strong>Routing providers and credentials</strong> — OSRM (default), ORS (optional, needs a key), and the reserved Mapbox/r5r surfaces, plus the offline bypass: <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>.</li>
<li>
<strong>Map-based inspection of one site</strong>: <code><a href="../articles/visual-walkthrough.html">vignette("visual-walkthrough", package = "catchmentACS")</a></code>.</li>
<li>
<strong>Every <code><a href="../reference/cacs_run.html">cacs_run()</a></code> argument in detail</strong>: <code><a href="../reference/cacs_run.html">?cacs_run</a></code>. The pipeline functions are <code><a href="../reference/cacs_acs_prefetch.html">?cacs_acs_prefetch</a></code>, <code><a href="../reference/cacs_isochrone.html">?cacs_isochrone</a></code>, <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>, <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code>, and <code><a href="../reference/cacs_derive_rates.html">?cacs_derive_rates</a></code>.</li>
</ul>
<p>Bug reports and feature requests: <a href="https://github.com/joonho112/catchmentACS/issues" class="external-link uri">https://github.com/joonho112/catchmentACS/issues</a>.</p>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="https://github.com/joonho112" class="external-link">JoonHo Lee</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
