<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Getting started with catchmentACS • catchmentACS</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="image/svg+xml" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<!-- katex math --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script><script src="../katex-auto.js"></script><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="getting-started_files/libs/quarto-html/popper.min.js"></script><script src="getting-started_files/libs/quarto-html/tippy.umd.min.js"></script><link href="getting-started_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="getting-started_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="getting-started_files/libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="getting-started_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><link href="getting-started_files/libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="getting-started_files/libs/leaflet-1.3.1/leaflet.js"></script><link href="getting-started_files/libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="getting-started_files/libs/proj4-2.6.2/proj4.min.js"></script><script src="getting-started_files/libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script><link href="getting-started_files/libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="getting-started_files/libs/leaflet-binding-2.2.3/leaflet.js"></script><script src="getting-started_files/libs/leaflet-providers-3.0.0/leaflet-providers.js"></script><script src="getting-started_files/libs/leaflet-providers-plugin-2.2.3/leaflet-providers-plugin.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Getting started with catchmentACS">
<meta property="og:image" content="https://joonho112.github.io/catchmentACS/logo.svg">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">catchmentACS</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.5.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-vignettes" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Vignettes</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-vignettes">
<li><h6 class="dropdown-header" data-toc-skip>--- Applied Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/getting-started.html">Getting started</a></li>
    <li><a class="dropdown-item" href="../articles/alabama-tutorial.html">Alabama tutorial</a></li>
    <li><a class="dropdown-item" href="../articles/providers.html">Providers</a></li>
    <li><a class="dropdown-item" href="../articles/visual-walkthrough.html">Visual walkthrough</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Method Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/methodology.html">Methodology</a></li>
    <li><a class="dropdown-item" href="../articles/theory-spatial-aggregation.html">Spatial aggregation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-moe-propagation.html">MOE propagation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-derived-rates.html">Derived rates</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Migration ---</h6></li>
    <li><a class="dropdown-item" href="../articles/porting-v01-to-v03.html">Porting from v0.1 to v0.3</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v03-to-v04.html">Porting from v0.3 to v0.4</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v04-to-v05.html">Porting from v0.4 to v0.5</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/joonho112/catchmentACS/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.svg" class="logo" alt=""><h1>Getting started with catchmentACS</h1>




      <small class="dont-index">Source: <a href="https://github.com/joonho112/catchmentACS/blob/main/vignettes/getting-started.qmd" class="external-link"><code>vignettes/getting-started.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/joonho112/catchmentACS" class="external-link">catchmentACS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/" class="external-link">sf</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Force network-free, deterministic builds: no provider/Census calls, no cache.</span></span>
<span><span class="va">old_options</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span></span>
<span>  catchmentACS.progress <span class="op">=</span> <span class="st">"off"</span>,</span>
<span>  catchmentACS.rate_first_default <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span><span class="va">old_cache</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">getOption</a></span><span class="op">(</span><span class="st">"catchmentACS.cache_enabled"</span>, <span class="cn">NULL</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="va">old_options</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span>catchmentACS.cache_enabled <span class="op">=</span> <span class="va">old_cache</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/cacs_set_cache.html">cacs_set_cache</a></span><span class="op">(</span><span class="cn">FALSE</span>, scope <span class="op">=</span> <span class="st">"session"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>This is your ten-minute first run. It is written for people new to the package, including Pre-K administrators and policy researchers who do not work in R every day. By the end you will have run one function, read the table it returns, and (optionally) drawn one map.</p>
<p>If you are porting an older v0.1 or v0.2 script, start instead with the checklist in <code><a href="../articles/porting-v01-to-v03.html">vignette("porting-v01-to-v03", package = "catchmentACS")</a></code>.</p>
<div>
<blockquote>
<p><strong>About the data in this article</strong></p>
<p>The tables and map here are built entirely from the package’s bundled <code>inst/extdata</code> fixtures (the synthetic <code>legacy_2025_*</code> and <code>sample_alabama_subset</code> objects), so this article renders with <strong>no</strong> Census, OSRM, ORS, or other network calls. These fixtures are <strong>synthetic and illustrative</strong> — included only for examples, tests, and reproducible package checks. They are <strong>not</strong> live Alabama policy estimates and must not be cited as real ACS results. Any real analysis requires a fresh live run (see <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>).</p>
</blockquote>
</div>
<section class="level2"><h2 id="what-catchmentacs-does">What catchmentACS does<a class="anchor" aria-label="anchor" href="#what-catchmentacs-does"></a>
</h2>
<p>You give it a set of program sites and a few drive times (say 5, 10, and 15 minutes). For each site, <code>catchmentACS</code> draws the area you can reach within each drive time, finds the census tracts that fall inside, and reports the American Community Survey (ACS) conditions there — poverty, SNAP, employment, and more — each with a margin of error. In one sentence: <em>it answers “what are neighborhood conditions within a short drive of this site?”</em></p>
<p>The whole pipeline runs in a single call, <code><a href="../reference/cacs_run.html">cacs_run()</a></code>:</p>
<blockquote>
<p><strong>sites + drive times</strong> → drive-time areas → census tracts inside → area-weighted ACS totals and rates (with margins of error) → one tidy table.</p>
</blockquote>
<p>The math behind the area weighting and the margins of error lives in <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>; this article stays at the workflow level.</p>
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="figures/cacs-flow-overview.png"></p>
<figcaption>How catchmentACS turns sites into catchment estimates</figcaption></figure>
</div>
</section><section class="level2"><h2 id="install">Install<a class="anchor" aria-label="anchor" href="#install"></a>
</h2>
<p>Once the package is on CRAN:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html" class="external-link">install.packages</a></span><span class="op">(</span><span class="st">"catchmentACS"</span><span class="op">)</span></span></code></pre></div>
<p>Before then, install from GitHub:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># install.packages("pak")</span></span>
<span><span class="fu">pak</span><span class="fu">::</span><span class="fu"><a href="https://pak.r-lib.org/reference/pak.html" class="external-link">pak</a></span><span class="op">(</span><span class="st">"joonho112/catchmentACS"</span><span class="op">)</span></span></code></pre></div>
<p>A live run that pulls fresh ACS data needs a free Census API key (one-time setup, takes a minute at <a href="https://api.census.gov/data/key_signup.html" class="external-link uri">https://api.census.gov/data/key_signup.html</a>):</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">tidycensus</span><span class="fu">::</span><span class="fu"><a href="https://walker-data.com/tidycensus/reference/census_api_key.html" class="external-link">census_api_key</a></span><span class="op">(</span><span class="st">"YOUR_KEY_HERE"</span>, install <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<p>You do <strong>not</strong> need a key for this article — it uses bundled data — and the default routing provider (OSRM) needs no key either, so you can follow along with nothing installed beyond the package itself.</p>
</section><section class="level2"><h2 id="your-first-run-offline">Your first run (offline)<a class="anchor" aria-label="anchor" href="#your-first-run-offline"></a>
</h2>
<p>The example below is the whole package in one call, and it runs fully offline. It loads three bundled fixtures — sites, precomputed drive-time areas, and an ACS extract — and passes the last two through <code>precomputed_isochrones =</code> and <code>acs =</code>. Those two arguments tell <code><a href="../reference/cacs_run.html">cacs_run()</a></code> to <strong>skip</strong> the routing and Census downloads and use what you hand it, so this makes no network calls and needs no API key. We use one site, <code>AL_SITE_03</code>, with drive times of 5, 10, and 15 minutes. <strong>You can copy and run this as-is.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Load the three bundled example inputs.</span></span>
<span><span class="va">sites</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_sites.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">iso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_isochrones.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">acs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"sample_alabama_subset.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">site_id</span> <span class="op">&lt;-</span> <span class="st">"AL_SITE_03"</span></span>
<span></span>
<span><span class="va">result</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_run.html">cacs_run</a></span><span class="op">(</span></span>
<span>  sites                  <span class="op">=</span> <span class="va">sites</span><span class="op">[</span><span class="va">sites</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">site_id</span>, , drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">]</span>,</span>
<span>  state                  <span class="op">=</span> <span class="st">"AL"</span>,</span>
<span>  year                   <span class="op">=</span> <span class="fl">2023</span>,</span>
<span>  drive_times            <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span><span class="op">)</span>,</span>
<span>  variables              <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html" class="external-link">unname</a></span><span class="op">(</span><span class="va">cacs_acs_default_vars</span><span class="op">)</span>,</span>
<span>  provider               <span class="op">=</span> <span class="st">"osrm"</span>,</span>
<span>  precomputed_isochrones <span class="op">=</span> <span class="va">iso</span><span class="op">[</span><span class="va">iso</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">site_id</span>, , drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">]</span>,</span>
<span>  acs                    <span class="op">=</span> <span class="va">acs</span>,</span>
<span>  weight_method          <span class="op">=</span> <span class="st">"area"</span>,</span>
<span>  output                 <span class="op">=</span> <span class="st">"long"</span>,</span>
<span>  verbose                <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 57 27</code></pre>
</div>
</div>
<p>A quick look at the arguments:</p>
<ul>
<li>
<code>sites</code> — your program locations (here, one synthetic site).</li>
<li>
<code>state</code> / <code>year</code> — the ACS universe: a two-letter state code and the <em>end year</em> of the 5-year ACS (2009–2024 supported; 2024 is the most recent vintage).</li>
<li>
<code>drive_times</code> — the catchment bands in minutes (here, three nested rings).</li>
<li>
<code>variables</code> — which ACS variables to pull; <code>cacs_acs_default_vars</code> is the built-in default set.</li>
<li>
<code>provider</code> — the routing engine for live runs. Here <code>"osrm"</code> only labels the provenance of the precomputed areas; it makes no request.</li>
<li>
<code>precomputed_isochrones</code> / <code>acs</code> — the offline bypass: supply both and no network is touched. Drop both for a real run.</li>
<li>
<code>weight_method</code> — <code>"area"</code> is the supported method in this release.</li>
<li>
<code>output</code> — the shape of the result (<code>"long"</code>, <code>"list_column"</code>, or <code>"both"</code>).</li>
</ul>
<p><strong>What you would run for real.</strong> Once your Census key is set, a live run is the same call without the two bypass arguments — <code>catchmentACS</code> then draws the drive-time areas with OSRM and pulls ACS data for you. That form is shown here but not executed (it would need a network):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Live form: needs a Census key and network access.</span></span>
<span><span class="fu">tidycensus</span><span class="fu">::</span><span class="fu"><a href="https://walker-data.com/tidycensus/reference/census_api_key.html" class="external-link">census_api_key</a></span><span class="op">(</span><span class="st">"YOUR_KEY_HERE"</span>, install <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">result</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_run.html">cacs_run</a></span><span class="op">(</span></span>
<span>  sites       <span class="op">=</span> <span class="va">cacs_alabama_sites</span>,   <span class="co"># 10 bundled Alabama sites, or your own</span></span>
<span>  state       <span class="op">=</span> <span class="st">"AL"</span>,</span>
<span>  year        <span class="op">=</span> <span class="fl">2023</span>,</span>
<span>  drive_times <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span><span class="op">)</span>,</span>
<span>  provider    <span class="op">=</span> <span class="st">"osrm"</span>,</span>
<span>  output      <span class="op">=</span> <span class="st">"long"</span></span>
<span><span class="op">)</span></span></code></pre></div>
</div>
<p>See <code><a href="../reference/cacs_run.html">?cacs_run</a></code> for every argument, and <code><a href="../articles/alabama-tutorial.html">vignette("alabama-tutorial", package = "catchmentACS")</a></code> for the same offline call worked into a reporting-ready table.</p>
</section><section class="level2"><h2 id="reading-your-results">Reading your results<a class="anchor" aria-label="anchor" href="#reading-your-results"></a>
</h2>
<p><code>result</code> is one tidy <em>long</em> table: one row per site, drive-time band, and variable. It carries extra bookkeeping columns that record how, when, and from what data each number was made — useful when you share results, ignorable otherwise. Day to day you read only a handful:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">result</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">cacs_acs_default_rates</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span>, <span class="va">failure_origin</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  variable                  mean_estimate sd_estimate     n
  &lt;chr&gt;                             &lt;dbl&gt;       &lt;dbl&gt; &lt;int&gt;
1 snap_rate                        0.441            0     2
2 labor_force_participation        0.323            0     2
3 poverty_rate                     0.261            0     2
4 ssi_rate                         0.101            0     2
5 unemp_rate                       0.0939           0     2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  site_id    drive_time_min poverty_rate snap_rate ssi_rate unemp_rate
  &lt;chr&gt;               &lt;int&gt;        &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
1 AL_SITE_03              5        0.261     0.441    0.101     0.0939
2 AL_SITE_03             10        0.261     0.441    0.101     0.0939
# ℹ 1 more variable: labor_force_participation &lt;dbl&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   site_id    drive_time_min variable             estimate    moe failure_origin
   &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;                   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;
 1 AL_SITE_03              5 poverty_rate           0.261  0.0561 none
 2 AL_SITE_03              5 snap_rate              0.441  0.118  none
 3 AL_SITE_03              5 ssi_rate               0.101  0.0267 none
 4 AL_SITE_03              5 unemp_rate             0.0939 0.0238 none
 5 AL_SITE_03              5 labor_force_partici…   0.323  0.0551 none
 6 AL_SITE_03             10 poverty_rate           0.261  0.0561 none
 7 AL_SITE_03             10 snap_rate              0.441  0.118  none
 8 AL_SITE_03             10 ssi_rate               0.101  0.0267 none
 9 AL_SITE_03             10 unemp_rate             0.0939 0.0238 none
10 AL_SITE_03             10 labor_force_partici…   0.323  0.0551 none          </code></pre>
</div>
</div>
<table class="table caption-top">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead><tr class="header">
<th>Column</th>
<th>Plain-English meaning</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>site_id</code></td>
<td>Which program site this row describes.</td>
</tr>
<tr class="even">
<td><code>drive_time_min</code></td>
<td>Which catchment band, in minutes (5, 10, or 15).</td>
</tr>
<tr class="odd">
<td><code>variable</code></td>
<td>Which indicator (e.g. <code>poverty_rate</code>, or a raw ACS code).</td>
</tr>
<tr class="even">
<td><code>estimate</code></td>
<td>The value. For a rate, a proportion: <code>0.173</code> means 17.3%.</td>
</tr>
<tr class="odd">
<td><code>moe</code></td>
<td>Margin of error (MOE) at the 90% level — see below.</td>
</tr>
<tr class="even">
<td><code>failure_origin</code></td>
<td>
<code>"none"</code> means the row is good; otherwise where it went wrong.</td>
</tr>
</tbody>
</table>
<p>A <strong>margin of error (MOE)</strong> is the half-width of a 90% confidence interval: you report a value as <code>estimate ± moe</code>, the same way the Census Bureau reports ACS figures. So a <code>poverty_rate</code> of <code>0.173</code> with an <code>moe</code> of <code>0.024</code> says the catchment’s poverty rate is about 17.3% ± 2.4 points. The package carries the ACS published MOEs through every weighting and rate step; the formulas are in <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code> and <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>.</p>
<p>Two habits worth forming early:</p>
<ul>
<li>
<strong>Check <code>failure_origin</code> first.</strong> <code>failure_origin == "none"</code> is your success flag. If an estimate is <code>NA</code>, this column names the stage that produced the gap (an upstream ACS input, an isochrone failure, an empty intersection, and so on) so you can diagnose rather than guess.</li>
<li>
<strong>The five curated rates ride alongside the raw variables.</strong> Every <code>(site, drive_time)</code> cell gets five extra rows — <code>poverty_rate</code>, <code>snap_rate</code>, <code>ssi_rate</code>, <code>unemp_rate</code>, and <code>labor_force_participation</code> — computed from the raw ACS counts. They share the same <code>estimate</code>/<code>moe</code> columns, so you read them exactly like any other variable. These are the headline outputs most users reach for.</li>
</ul>
<p>Here are the five curated rates for the 15-minute catchment around this site:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">result</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span></span>
<span>    <span class="va">variable</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">cacs_acs_default_rates</span><span class="op">)</span>,</span>
<span>    <span class="va">drive_time_min</span> <span class="op">==</span> <span class="fl">15</span>,</span>
<span>    <span class="va">failure_origin</span> <span class="op">==</span> <span class="st">"none"</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">drive_time_min</span>, <span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">moe</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  variable                  mean_estimate sd_estimate     n
  &lt;chr&gt;                             &lt;dbl&gt;       &lt;dbl&gt; &lt;int&gt;
1 labor_force_participation        0.536           NA     1
2 poverty_rate                     0.255           NA     1
3 snap_rate                        0.251           NA     1
4 ssi_rate                         0.0852          NA     1
5 unemp_rate                       0.0664          NA     1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  site_id    drive_time_min poverty_rate snap_rate ssi_rate unemp_rate
  &lt;chr&gt;               &lt;int&gt;        &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
1 AL_SITE_03             15        0.255     0.251   0.0852     0.0664
# ℹ 1 more variable: labor_force_participation &lt;dbl&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  site_id    drive_time_min variable                  estimate     moe
  &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;                        &lt;dbl&gt;   &lt;dbl&gt;
1 AL_SITE_03             15 poverty_rate                0.255  0.0351
2 AL_SITE_03             15 snap_rate                   0.251  0.0345
3 AL_SITE_03             15 ssi_rate                    0.0852 0.0113
4 AL_SITE_03             15 unemp_rate                  0.0664 0.00838
5 AL_SITE_03             15 labor_force_participation   0.536  0.0739 </code></pre>
</div>
</div>
<p>For a friendlier view, <code><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary()</a></code> reshapes the same numbers into one row per site and drive time, with each rate formatted as <code>estimate ± MOE</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span><span class="op">$</span><span class="va">rates_per_site_moe</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  site_id    drive_time_min poverty_rate  snap_rate     ssi_rate      unemp_rate
  &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;         &lt;chr&gt;         &lt;chr&gt;         &lt;chr&gt;
1 AL_SITE_03              5 0.261 ± 0.056 0.441 ± 0.118 0.101 ± 0.027 0.094 ± 0…
2 AL_SITE_03             10 0.261 ± 0.056 0.441 ± 0.118 0.101 ± 0.027 0.094 ± 0…
3 AL_SITE_03             15 0.255 ± 0.035 0.251 ± 0.034 0.085 ± 0.011 0.066 ± 0…
# ℹ 1 more variable: labor_force_participation &lt;chr&gt;</code></pre>
</div>
</div>
<p>Remember these numbers come from synthetic example data; cite real values only from a live run.</p>
</section><section class="level2"><h2 id="an-optional-map">An optional map<a class="anchor" aria-label="anchor" href="#an-optional-map"></a>
</h2>
<p>If the optional <code>leaflet</code> package is installed, you can see the site and its 15-minute drive-time area on a base map. This chunk is gated on the namespace, so it is simply skipped when <code>leaflet</code> is absent — and we call <code>leaflet::</code> rather than attaching the package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one_site_pt</span>  <span class="op">&lt;-</span> <span class="va">sites</span><span class="op">[</span><span class="va">sites</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">site_id</span>, <span class="op">]</span></span>
<span><span class="va">one_site_iso</span> <span class="op">&lt;-</span> <span class="va">iso</span><span class="op">[</span><span class="va">iso</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">site_id</span> <span class="op">&amp;</span> <span class="va">iso</span><span class="op">$</span><span class="va">drive_time_min</span> <span class="op">==</span> <span class="fl">15</span>, <span class="op">]</span></span>
<span></span>
<span><span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/leaflet.html" class="external-link">leaflet</a></span><span class="op">(</span><span class="va">one_site_pt</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/addProviderTiles.html" class="external-link">addProviderTiles</a></span><span class="op">(</span><span class="st">"CartoDB.Positron"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/map-layers.html" class="external-link">addPolygons</a></span><span class="op">(</span></span>
<span>    data <span class="op">=</span> <span class="va">one_site_iso</span>, weight <span class="op">=</span> <span class="fl">2</span>, opacity <span class="op">=</span> <span class="fl">0.6</span>,</span>
<span>    color <span class="op">=</span> <span class="st">"#c05621"</span>, fillOpacity <span class="op">=</span> <span class="fl">0.15</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">leaflet</span><span class="fu">::</span><span class="fu"><a href="https://rstudio.github.io/leaflet/reference/map-layers.html" class="external-link">addCircleMarkers</a></span><span class="op">(</span></span>
<span>    radius <span class="op">=</span> <span class="fl">5</span>, color <span class="op">=</span> <span class="st">"#2b6cb0"</span>,</span>
<span>    fillOpacity <span class="op">=</span> <span class="fl">0.8</span>, stroke <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>    popup <span class="op">=</span> <span class="op">~</span><span class="va">site_id</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="leaflet html-widget html-fill-item" id="htmlwidget-a1da500ca1bbf3d51ef7" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-a1da500ca1bbf3d51ef7">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["CartoDB.Positron",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addPolygons","args":[[[[{"lng":[-87.12842465967452,-87.12940621368926,-87.13081393285955,-87.13264385350243,-87.13489085925751,-87.13754869620942,-87.14060999106557,-87.14406627232813,-87.14790799439186,-87.15212456449228,-87.15670437242193,-87.16163482292572,-87.16690237068083,-87.17249255776008,-87.17839005347285,-87.18457869647199,-87.19104153901043,-87.19776089322693,-87.204718379336,-87.21189497559288,-87.21927106990158,-87.22682651293007,-87.23454067259424,-87.24239248976919,-87.2503605350845,-87.25842306665777,-87.26655808861909,-87.27474341027754,-87.28295670577995,-87.29117557411074,-87.29937759928133,-87.30754041055758,-87.31564174257279,-87.32365949517492,-87.33157179285664,-87.33935704361762,-87.34699399710989,-87.35446180191774,-87.36174006182605,-87.36880889093224,-87.37564896745931,-87.38224158613031,-87.38856870896699,-87.39461301437841,-87.40035794440921,-87.40578775002035,-87.41088753427951,-87.41564329334275,-87.42004195511346,-87.4240714154698,-87.42772057195718,-87.43097935484789,-87.433838755476,-87.43629085176215,-87.43832883084902,-87.43994700877579,-87.44114084712653,-87.44190696659565,-87.44224315742048,-87.44214838664023,-87.4416228021478,-87.44066773351035,-87.43928568954263,-87.43748035262662,-87.43525656977978,-87.43262034048354,-87.42957880129312,-87.42614020725928,-87.42231391020189,-87.41811033388497,-87.41354094615201,-87.40861822809056,-87.40335564030313,-87.39776758637215,-87.39186937361463,-87.38567717123138,-87.37920796596447,-87.37247951538433,-87.36551029893624,-87.35831946688347,-87.35092678729129,-87.34335259120287,-87.33561771616472,-87.32774344826404,-87.31975146284697,-87.31166376409001,-87.30350262360179,-87.29529051823523,-87.28705006729375,-87.278803969316,-87.27057493862668,-87.26238564184042,-87.2542586345069,-87.24621629808418,-87.23828077742664,-87.23047391897147,-87.22281720980574,-87.21533171779251,-87.20803803293127,-87.20095621012277,-87.19410571350437,-87.18750536251601,-87.18117327985075,-87.17512684143821,-87.1693826286009,-87.16395638251777,-87.15886296111981,-87.15411629853594,-87.14972936719796,-87.14571414270509,-87.14208157153972,-87.13884154171669,-87.13600285643922,-87.13357321082539,-87.13155917175909,-87.12996616091061,-87.12879844096183,-87.12805910506171,-87.12775006952882,-87.12787206980727,-87.12842465967452],"lat":[30.84253354777893,30.83552000447882,30.82856004203156,30.82167272366373,30.81487690964079,30.80819120576534,30.80163391261235,30.79522297563863,30.78897593629928,30.78290988430261,30.77704141113,30.77138656494514,30.76596080701059,30.760778969728,30.75585521641195,30.75120300290259,30.74683504111852,30.74276326464415,30.73899879644201,30.73555191877331,30.73243204540528,30.72964769617685,30.72720647398893,30.72511504427818,30.72337911702754,30.72200343135921,30.72099174275098,30.72034681290698,30.72007040231053,30.72016326547692,30.72062514891919,30.72145479183153,30.72264992948874,30.72420729935336,30.72612264987406,30.72839075195367,30.73100541305645,30.73395949391905,30.73724492782193,30.74085274237141,30.74477308373644,30.74899524327761,30.75350768649899,30.75829808424808,30.7633533460831,30.76865965572025,30.77420250846855,30.77996675055502,30.78593662023581,30.79209579058694,30.79842741386004,30.80491416728707,30.81153830021251,30.81828168242647,30.82512585357173,30.83205207349035,30.83904137337661,30.84607460759688,30.85313250603719,30.86019572683659,30.86724490936189,30.8742607272802,30.88122394158307,30.88811545341655,30.89491635657152,30.90160798948877,30.90817198663447,30.91459032910244,30.92084539430264,30.92692000459466,30.93279747473147,30.93846165797761,30.94389699077221,30.94908853580986,30.9540220234159,30.95868389109928,30.96306132116802,30.96714227630055,30.97091553297053,30.97437071262754,30.97749831054523,30.98028972225172,30.9827372674671,30.98483421147726,30.98657478388256,30.98795419466642,30.98896864753738,30.98961535050476,30.9898925236582,30.98979940412751,30.98933624820841,30.9885043306487,30.98730594109537,30.98574437771511,30.98382393800503,30.98154990682151,30.97892854166182,30.97596705524134,30.97267359541758,30.96905722251886,30.96512788414412,30.96089638750665,30.95637436940225,30.95157426388804,30.94650926776634,30.94119330397183,30.93564098296813,30.92986756226396,30.92388890416537,30.91772143188323,30.91138208412264,30.90488826828179,30.89825781239243,30.89150891593906,30.88466009969322,30.87773015470443,30.87073809059047,30.86370308326987,30.85664442228259,30.84958145784412,30.84253354777893]}]]],null,null,{"interactive":true,"className":"","stroke":true,"color":"#c05621","weight":2,"opacity":0.6,"fill":true,"fillColor":"#c05621","fillOpacity":0.15,"smoothFactor":1,"noClip":false},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addCircleMarkers","args":[30.85500008246067,-87.28499999999647,5,null,null,{"interactive":true,"className":"","stroke":false,"color":"#2b6cb0","weight":5,"opacity":0.5,"fill":true,"fillColor":"#2b6cb0","fillOpacity":0.8},null,null,"AL_SITE_03",null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[30.72007040231053,30.9898925236582],"lng":[-87.44224315742048,-87.12775006952882]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>The blue dot is the site; the orange shape is everything within a 15-minute drive. Change the <code>site_id</code> value near the top of “Your first run” to explore a different site.</p>
</section><section class="level2"><h2 id="where-to-next">Where to next<a class="anchor" aria-label="anchor" href="#where-to-next"></a>
</h2>
<p>You have your first estimate. From here:</p>
<ul>
<li>
<strong>A full reporting workflow</strong> on real Alabama sites — comparing sites, building export tables: <code><a href="../articles/alabama-tutorial.html">vignette("alabama-tutorial", package = "catchmentACS")</a></code>.</li>
<li>
<strong>Routing providers and credentials</strong> — OSRM (default), ORS (optional, needs a key), and the reserved Mapbox/r5r surfaces: <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>.</li>
<li>
<strong>The math behind area weighting and MOE propagation</strong>: <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>.</li>
<li>
<strong>Every <code><a href="../reference/cacs_run.html">cacs_run()</a></code> argument in detail</strong>: <code><a href="../reference/cacs_run.html">?cacs_run</a></code>.</li>
</ul>
<p>Bug reports and feature requests: <a href="https://github.com/joonho112/catchmentACS/issues" class="external-link uri">https://github.com/joonho112/catchmentACS/issues</a>.</p>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="https://github.com/joonho112" class="external-link">JoonHo Lee</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
