<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Spatial aggregation: area-weighted estimation • catchmentACS</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="image/svg+xml" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<!-- katex math --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script><script src="../katex-auto.js"></script><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="theory-spatial-aggregation_files/libs/quarto-html/popper.min.js"></script><script src="theory-spatial-aggregation_files/libs/quarto-html/tippy.umd.min.js"></script><link href="theory-spatial-aggregation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="theory-spatial-aggregation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Spatial aggregation: area-weighted estimation">
<meta property="og:image" content="https://joonho112.github.io/catchmentACS/logo.svg">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">catchmentACS</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.5.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-vignettes" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Vignettes</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-vignettes">
<li><h6 class="dropdown-header" data-toc-skip>--- Applied Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/getting-started.html">Getting started</a></li>
    <li><a class="dropdown-item" href="../articles/alabama-tutorial.html">Alabama tutorial</a></li>
    <li><a class="dropdown-item" href="../articles/providers.html">Providers</a></li>
    <li><a class="dropdown-item" href="../articles/visual-walkthrough.html">Visual walkthrough</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Method Track ---</h6></li>
    <li><a class="dropdown-item" href="../articles/methodology.html">Methodology</a></li>
    <li><a class="dropdown-item" href="../articles/theory-spatial-aggregation.html">Spatial aggregation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-moe-propagation.html">MOE propagation</a></li>
    <li><a class="dropdown-item" href="../articles/theory-derived-rates.html">Derived rates</a></li>
    <li><h6 class="dropdown-header" data-toc-skip>--- Migration ---</h6></li>
    <li><a class="dropdown-item" href="../articles/porting-v01-to-v03.html">Porting from v0.1 to v0.3</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v03-to-v04.html">Porting from v0.3 to v0.4</a></li>
    <li><a class="dropdown-item" href="../articles/porting-v04-to-v05.html">Porting from v0.4 to v0.5</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/joonho112/catchmentACS/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.svg" class="logo" alt=""><h1>Spatial aggregation: area-weighted estimation</h1>




      <small class="dont-index">Source: <a href="https://github.com/joonho112/catchmentACS/blob/main/vignettes/theory-spatial-aggregation.qmd" class="external-link"><code>vignettes/theory-spatial-aggregation.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/joonho112/catchmentACS" class="external-link">catchmentACS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/" class="external-link">sf</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Force network-free, deterministic builds: no provider/Census calls, no cache.</span></span>
<span><span class="va">old_options</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span></span>
<span>  catchmentACS.progress <span class="op">=</span> <span class="st">"off"</span>,</span>
<span>  catchmentACS.rate_first_default <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span><span class="va">old_cache</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">getOption</a></span><span class="op">(</span><span class="st">"catchmentACS.cache_enabled"</span>, <span class="cn">NULL</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="va">old_options</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/on.exit.html" class="external-link">on.exit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span>catchmentACS.cache_enabled <span class="op">=</span> <span class="va">old_cache</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="../reference/cacs_set_cache.html">cacs_set_cache</a></span><span class="op">(</span><span class="cn">FALSE</span>, scope <span class="op">=</span> <span class="st">"session"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>This article is a <strong>method-track</strong> companion to <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>. The overview frames the whole pipeline as one estimator and <em>states</em> that a count and an average are aggregated by two different weights; this article <em>derives</em> that result and then does something the overview cannot — it <strong>reproduces the package’s arithmetic by hand</strong>, on a bundled fixture, so a methodologist can confirm that the formulas on this page are the formulas the code runs. It is written for a reader who wants the areal-interpolation model on the page: the uniform-within-tract assumption stated precisely, the coverage weight and the normalized mean weight built from first principles, the six estimand families laid out with the exact aggregation formula and the weight each one uses, and a numerical check that earns trust in the implementation. The reference page <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code> is the implementation anchor; this article supplies the mathematics behind its “Estimand families and weights” section.</p>
<p>We reuse the notation fixed in the overview without redefining its motivation: the isochrone <span class="math inline">I_s</span>, the tract <span class="math inline">T_j</span>, the intersection <span class="math inline">I_s \cap T_j</span>, the equal-area measure <span class="math inline">\lvert\,\cdot\,\rvert</span>, a count estimate <span class="math inline">Y_j</span>, a scalar estimate <span class="math inline">X_j</span>, and a rate’s numerator and denominator counts <span class="math inline">A_j, B_j</span>. The two weights <span class="math inline">w^{cov}_{sj}</span> and <span class="math inline">w^{mean}_{sj}</span> and the three estimator forms <span class="math inline">\widehat{Y}_s</span>, <span class="math inline">\widehat{\bar X}_s</span>, <span class="math inline">\widehat{R}_s</span> are restated where they are derived. The margin-of-error algebra is <strong>not</strong> developed here — it is the subject of <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code>.</p>
<div>
<blockquote>
<p><strong>About the data in this article</strong></p>
<p>The single numerical check below is built entirely from the package’s bundled <code>inst/extdata</code> fixtures — the synthetic <code>legacy_2025_isochrones</code>, <code>legacy_2025_sites</code>, and <code>sample_alabama_subset</code> objects — so this article renders with <strong>no</strong> Census, OSRM, ORS, or other network calls. These fixtures preserve the production calling contract (sites, drive-time polygons, tract-level ACS variables) but are <strong>synthetic and illustrative</strong>: they are included only for examples, tests, and reproducible package checks. They are <strong>not</strong> live Alabama policy estimates and must not be cited as real ACS results. Any real analysis requires a fresh live run (see <code><a href="../articles/providers.html">vignette("providers", package = "catchmentACS")</a></code>).</p>
</blockquote>
</div>
<section class="level2"><h2 id="the-areal-interpolation-model">The areal-interpolation model<a class="anchor" aria-label="anchor" href="#the-areal-interpolation-model"></a>
</h2>
<p>The estimand is a neighborhood characteristic of the population that lives inside a drive-time catchment <span class="math inline">I_s</span>: the count of people in poverty within a 10-minute drive of a site, the per-capita income of that catchment, its SNAP rate. The ACS publishes its estimates on census tracts <span class="math inline">T_j</span>, whose boundaries were drawn for enumeration, not for travel time. A drive-time area slices straight through tract edges, capturing some tracts whole and others only in part — a sliver of one, half of another, the whole of a third. Areal interpolation is the model that re-expresses a tract-level published value as a catchment-level value across that misalignment.</p>
<p>The model rests on a single assumption.</p>
<blockquote>
<p><strong>Uniform-within-tract assumption.</strong> The characteristic of interest is spread <em>uniformly</em> over the area of each tract <span class="math inline">T_j</span>. A catchment covering 40% of a tract’s area contains 40% of whatever the tract counts.</p>
</blockquote>
<p>Stated as a density, let <span class="math inline">\rho_j</span> be the quantity of the characteristic per unit area in tract <span class="math inline">T_j</span>. Uniformity means <span class="math inline">\rho_j</span> is constant across <span class="math inline">T_j</span>, so the amount of the characteristic contained in any sub-region <span class="math inline">S \subseteq T_j</span> is proportional to that sub-region’s area,</p>
<p><span class="math display">
\text{amount in } S = \rho_j \, \lvert S \rvert
= \big(\text{tract amount}\big)\cdot\frac{\lvert S \rvert}{\lvert T_j \rvert}.
</span></p>
<p>Taking <span class="math inline">S = I_s \cap T_j</span> gives the amount of the characteristic the catchment captures from tract <span class="math inline">j</span>: the tract’s published amount, scaled by the fraction of the tract’s area inside the catchment. That fraction is the coverage weight of the next section, and the whole estimator is built from this one identity.</p>
<p>The assumption’s reach depends on the <em>type</em> of variable, and the distinction is the hinge of everything that follows.</p>
<ul>
<li>An <strong>extensive</strong> (count) variable, <span class="math inline">Y_j</span> — persons, households, persons in poverty — is an <em>amount</em> that lives in the tract. Under uniformity it splits in proportion to area: half the tract’s area carries half its people. The model is <em>exact for area</em> and <em>approximate for the count</em>, the approximation being only as good as the uniformity of the underlying density.</li>
<li>An <strong>intensive</strong> (scalar) variable, <span class="math inline">X_j</span> — a median, a per-capita figure, a rate expressed as a level — is a <em>per-unit</em> quantity, not an amount. It does not accumulate over area: half a tract does not hold “half a dollar of per-capita income.” Splitting an intensive value by area is meaningless. What the model can do for an intensive variable is treat its tract value as the local level of a field and form an area-weighted <em>average</em> of the tract values the catchment overlaps — a blend, not a sum.</li>
</ul>
<p>This is exactly why one weight cannot serve both. <strong>Extensive variables are summed with a weight that allocates a fraction of each tract amount; intensive variables are averaged with a weight that is a share and sums to one.</strong> The package encodes this split as a variable’s <em>estimand family</em>; the two weights are the two ways the same intersection area enters an aggregate.</p>
<p><strong>When the assumption fails.</strong> It is most strained where population is concentrated on a small part of a large tract. Suppose 80% of a tract’s <em>area</em> is uninhabited woodland and its residents are packed into the remaining 20%. A catchment that clips only the woodland edge gets a coverage weight near <span class="math inline">0.8</span>, and area weighting then credits the catchment with ~80% of the tract’s population — when the truth is closer to 0%. The error is largest where land use is most heterogeneous within a tract: the urban–rural fringe, coastlines, large rural tracts straddling a town and its hinterland. The reserved <code>weight_method = "population"</code> mode is designed to relax exactly this assumption by substituting an ancillary population surface for area as the allocation basis (a <em>dasymetric</em> refinement); in the current release area is the only basis, and the assumption is stated plainly rather than hidden. Everything below concerns the implemented area path, whose honest caveat is this paragraph.</p>
</section><section class="level2"><h2 id="coverage-weight-versus-normalized-mean-weight">Coverage weight versus normalized mean weight<a class="anchor" aria-label="anchor" href="#coverage-weight-versus-normalized-mean-weight"></a>
</h2>
<p>Both weights are built from the same ingredient, the intersection area <span class="math inline">\lvert I_s \cap T_j \rvert</span>. They differ only in what they divide it by, and that single difference is the difference between a total and an average.</p>
<p><strong>The coverage weight.</strong> From the areal-interpolation identity, the share of tract <span class="math inline">j</span>’s amount that the catchment captures is the fraction of the tract’s area inside the catchment,</p>
<p><span class="math display">
w^{cov}_{sj} = \frac{\lvert I_s \cap T_j \rvert}{\lvert T_j \rvert}
\;\in\; [0, 1].
</span></p>
<p>It is bounded by one tract at a time: <span class="math inline">w^{cov}_{sj} = 1</span> when <span class="math inline">T_j \subseteq I_s</span> (the tract is wholly inside the catchment) and <span class="math inline">w^{cov}_{sj} = 0</span> when the two are disjoint. Crucially, the coverage weights of the tracts a catchment touches do <strong>not</strong> sum to one. Summing over <span class="math inline">j</span>,</p>
<p><span class="math display">
\sum_j w^{cov}_{sj}
= \sum_j \frac{\lvert I_s \cap T_j \rvert}{\lvert T_j \rvert}
\;\neq\; 1
</span></p>
<p>in general, because each term divides by a <em>different</em> tract area <span class="math inline">\lvert T_j
\rvert</span>. Its value is interpretable: it is the <em>effective number of tract-equivalents</em> the catchment covers. A catchment that wholly contained two tracts and half of a third would have <span class="math inline">\sum_j w^{cov}_{sj} = 2.5</span>; three tracts each half-covered would sum to about <span class="math inline">1.5</span>. Because the catchment area <span class="math inline">\lvert I_s \rvert</span> equals <span class="math inline">\sum_j \lvert I_s \cap T_j \rvert</span> when <span class="math inline">I_s</span> lies entirely within the tract layer, the coverage sum is the catchment’s area re-expressed in units of “average tract,” not a probability that must normalize. The package surfaces this sum directly as the <code>weight_sum</code> column, and a value near a small integer means the catchment captured roughly that many whole tracts.</p>
<p><strong>The normalized mean weight.</strong> An intensive variable needs a <em>share</em>: each tract should contribute to the catchment average in proportion to how much of the catchment it accounts for, with the contributions summing to one. Dividing the intersection area by the <em>total</em> intersection area over the catchment gives</p>
<p><span class="math display">
w^{mean}_{sj}
= \frac{\lvert I_s \cap T_j \rvert}{\sum_k \lvert I_s \cap T_k \rvert},
</span></p>
<p>and this is normalized by construction,</p>
<p><span class="math display">
\sum_j w^{mean}_{sj}
= \frac{\sum_j \lvert I_s \cap T_j \rvert}{\sum_k \lvert I_s \cap T_k \rvert}
= 1,
</span></p>
<p>because the numerator summed over <span class="math inline">j</span> is exactly the denominator. The sum-to-one property is structural, not coincidental. The two weights are proportional within a catchment — <span class="math inline">w^{mean}_{sj} \propto w^{cov}_{sj}\, \lvert T_j \rvert</span> — but they are renormalized against different denominators, and that is what separates a quantity that <em>scales with the catchment</em> from one that <em>stays on the per-unit scale of the variable</em>.</p>
<p><strong>Why the families split this way.</strong> Put the two estimators side by side.</p>
<ul>
<li>
<p>A <strong>count</strong> is a sum of amounts, so it is aggregated with the coverage weight:</p>
<p><span class="math display">
\widehat{Y}_s = \sum_j w^{cov}_{sj}\, Y_j .
</span></p>
<p>If the catchment captures more area it captures more people, and <span class="math inline">\widehat{Y}_s</span> grows accordingly. Using a normalized weight here would force the answer to a per-tract average and destroy the dependence on catchment size — a silent error.</p>
</li>
<li>
<p>A <strong>scalar</strong> is a per-unit level, so it is aggregated with the normalized mean weight as a convex combination of the tract values:</p>
<p><span class="math display">
\widehat{\bar X}_s = \sum_j w^{mean}_{sj}\, X_j ,
\qquad \sum_j w^{mean}_{sj} = 1 .
</span></p>
<p>Because the weights sum to one and are non-negative, <span class="math inline">\widehat{\bar X}_s</span> lies between <span class="math inline">\min_j X_j</span> and <span class="math inline">\max_j X_j</span>: a catchment average per-capita income cannot exceed every tract’s per-capita income. Using the coverage weight here would let an intensive value accumulate past any tract’s level — again a silent error, not a runtime failure.</p>
</li>
<li>
<p>A <strong>derived rate</strong> is a ratio of two extensive quantities. Each of the numerator and denominator is aggregated as its own coverage-weighted total, and the ratio is formed last:</p>
<p><span class="math display">
\widehat{R}_s
= \frac{\sum_j w^{cov}_{sj}\, A_j}{\sum_j w^{cov}_{sj}\, B_j} .
</span></p>
<p>The rate inherits the coverage path because both of its parts are counts; it is not a weighted average of tract rates, which would weight a tiny-denominator tract the same as a large one.</p>
</li>
</ul>
<p><strong>Neither misuse raises a warning.</strong> Apply the coverage weight to an intensive variable and you sum quantities that should average, producing a dollar figure inflated past any tract’s value — an income no one earns. Apply the mean weight to a count and you average quantities that should accumulate, producing a per-tract-ish number disconnected from how many people the catchment actually contains. The arithmetic runs; it just estimates the wrong thing. This is the silent estimand error the family classifier exists to prevent, and the reason the package refuses to apply one universal weight to every variable.</p>
<p>The numerical check at the end of this article exhibits both sums on real fixture geometry: <span class="math inline">\sum_j w^{cov}_{sj}</span> coming out to a non-integer, and <span class="math inline">\sum_j w^{mean}_{sj}</span> coming out to exactly one.</p>
</section><section class="level2"><h2 id="the-six-estimand-families">The six estimand families<a class="anchor" aria-label="anchor" href="#the-six-estimand-families"></a>
</h2>
<p>A variable’s <em>estimand family</em> is the rule that selects its weight and its aggregation formula. The package classifies every requested ACS variable into one of six families up front, then dispatches the matching arithmetic, so applying the wrong weight to a variable cannot happen quietly. The table gives the point estimate and the weight for each; the margin-of-error column is deliberately omitted, as the MOE formulas are derived in the companion article.</p>
<table class="table caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead><tr class="header">
<th>Estimand family</th>
<th>Representative variable</th>
<th>Point-estimate aggregation</th>
<th>Weight</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>spatial_total</code></td>
<td>total population; persons in poverty (<code>B17001_002</code>)</td>
<td><span class="math inline">\widehat{Y}_s = \sum_j w^{cov}_{sj} Y_j</span></td>
<td>coverage <span class="math inline">w^{cov}_{sj}</span>
</td>
</tr>
<tr class="even">
<td><code>derived_rate</code></td>
<td>poverty rate; SNAP rate</td>
<td><span class="math inline">\widehat{R}_s = \dfrac{\sum_j w^{cov}_{sj} A_j}{\sum_j w^{cov}_{sj} B_j}</span></td>
<td>coverage, numerator and denominator separately</td>
</tr>
<tr class="odd">
<td><code>area_weighted_scalar_proxy</code></td>
<td>per-capita income (<code>B19301_001</code>)</td>
<td><span class="math inline">\widehat{\bar X}_s = \sum_j w^{mean}_{sj} X_j</span></td>
<td>normalized mean <span class="math inline">w^{mean}_{sj}</span>
</td>
</tr>
<tr class="even">
<td>
<code>population_weighted_scalar_proxy</code> <em>(reserved)</em>
</td>
<td>scalar proxy under population weighting</td>
<td><span class="math inline">\widehat{\bar X}_s = \sum_j w^{mean}_{sj} X_j</span></td>
<td>population-normalized mean</td>
</tr>
<tr class="odd">
<td><code>median_proxy</code></td>
<td>tract median household income (<code>B19013_001</code>)</td>
<td>weighted blend of tract medians, <strong>not</strong> the true catchment median</td>
<td>normalized mean <span class="math inline">w^{mean}_{sj}</span>
</td>
</tr>
<tr class="even">
<td><code>metadata_only</code></td>
<td>provenance fields</td>
<td>no numeric aggregation</td>
<td>none</td>
</tr>
</tbody>
</table>
<p>A few families need a word beyond the table.</p>
<p><strong><code>spatial_total</code> and <code>derived_rate</code></strong> are the two coverage-weighted families. The total is the direct application of <span class="math inline">\widehat{Y}_s = \sum_j w^{cov}_{sj} Y_j</span>. The rate preserves the coverage-weighted numerator total <span class="math inline">\sum_j w^{cov}_{sj} A_j</span> and denominator total <span class="math inline">\sum_j w^{cov}_{sj} B_j</span> as separate carriers and divides them last, so it is a ratio of catchment totals rather than an average of tract ratios.</p>
<p><strong><code>area_weighted_scalar_proxy</code></strong> is the active intensive family in this release: a convex combination of tract values under the normalized mean weight, on the same per-unit scale as the inputs. Its point estimate is, by definition, <span class="math inline">\widehat{\bar X}_s = \sum_j w^{mean}_{sj}\, X_j</span>. The exact per-cell normalization the package applies when a single requested variable is missing in some intersecting tracts is the implementation’s responsibility, documented in <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>; the definitional blend above always lands between the contributing tracts’ minimum and maximum.</p>
<p><strong><code>population_weighted_scalar_proxy</code></strong> is a <em>reserved</em> family. It would replace the area-based mean weight with a population-based one, allocating by an ancillary population surface instead of by area to relax the uniform-within-tract assumption where population is concentrated. Conceptually this is dasymetric refinement: a finer ancillary layer (block-group population) is used to redistribute the coarser tract quantity, so the allocation follows people rather than land. In the current release this family is inert — <code>weight_method = "population"</code> stops with a clear error at the orchestrator boundary — and the population weight is not yet propagated through to estimates.</p>
<p><strong><code>median_proxy</code></strong> carries an explicit caveat. A median is not additive and not averageable: the median of a pooled population is generally <em>not</em> any weighted average of the sub-populations’ medians, which would require the underlying income distribution the ACS does not publish at the tract level. The package reports a mean-weighted blend of the tract medians under <span class="math inline">w^{mean}_{sj}</span> as a <strong>proxy</strong>, a convenient summary on the right scale, and labels it as such throughout. It is <em>not</em> the true median household income of the catchment population. The proxy is honest about being a proxy.</p>
<p><strong><code>metadata_only</code></strong> variables are provenance fields that carry through without any numeric aggregation.</p>
<p>The classifier and the per-family dispatch are documented in the “Estimand families and weights” section of <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>; this section is the derivation behind that documentation.</p>
</section><section class="level2"><h2 id="why-epsg5070">Why EPSG:5070<a class="anchor" aria-label="anchor" href="#why-epsg5070"></a>
</h2>
<p>Both weights are ratios in which the intersection area appears. A ratio of areas is only meaningful if numerator and denominator are measured in the <em>same</em> metric, and only <em>unbiased</em> across the catchment if that metric preserves area everywhere — so that “fraction of the tract” behaves like a fraction wherever the tract falls on the map. That is precisely the property of an <strong>equal-area</strong> projection, and it is why the choice of coordinate reference system is part of the estimator’s correctness, not a display detail.</p>
<p>On a geographic CRS (longitude/latitude), area is either dimensionless (degrees-squared, which is not an area) or, with great-circle integration, an ellipsoidal figure that is not equal-area. Web Mercator inflates area away from the equator dramatically. None preserves the proportionality the weights rely on, so the same physical hectare would be measured as more land in one part of the map than another, and <span class="math inline">w^{cov}_{sj}</span> would silently over- or under-credit tracts by where they sit, not by how much the catchment covers them. The package therefore transforms validated inputs <strong>once</strong>, before measuring any area, to <strong>EPSG:5070 (NAD83 / CONUS Albers Equal Area)</strong>, an Albers equal-area projection whose standard parallels are placed so that areal distortion across the contiguous United States is held to a fraction of a percent — and across the Southeast, between the standard parallels, it is effectively nil. With areas measured on EPSG:5070, a square meter of intersection contributes the same weight in north and south, <span class="math inline">\lvert T_j \rvert</span> and <span class="math inline">\lvert I_s \cap T_j \rvert</span> are evaluated in the same <span class="math inline">\text{m}^2</span>, and the coverage and mean weights mean what their formulas say. The choice also follows entrenched domain practice: equal-area CONUS Albers is the de facto standard for tract-level area work, which keeps these results comparable to neighboring analyses.</p>
<p>This is also the reason the current release is scoped to the <strong>contiguous United States plus DC</strong>: EPSG:5070 is the authoritative equal-area default there, where Albers distortion is negligible. Regions outside that footprint — Alaska, Hawaii, Puerto Rico — would need a different equal-area CRS and are deferred to a future release. The single up-front transform happens before the per-site loop, and no re-projection occurs inside it, so every area in a run is comparable on the same equal-area metric.</p>
</section><section class="level2"><h2 id="computation">Computation<a class="anchor" aria-label="anchor" href="#computation"></a>
</h2>
<p>The mathematics above is per-tract, but a run involves many sites and many tracts, and the implementation strategy is a deliberate choice rather than an incidental one. The package evaluates the estimator with a <strong>per-site loop</strong>: each site (and drive-time band) is processed in a closed body that subsets only <em>that</em> isochrone, prefilters candidate tracts with a spatial index, cuts the exact intersection geometry against only those candidates, measures intersection area and divides by the pre-computed tract area to get <span class="math inline">w^{cov}_{sj}</span>, builds both weight columns, and aggregates by family — before moving to the next. The alternative — one large vectorized spatial join over the full site-by-tract cross-product — is rejected for two reasons that matter at scale.</p>
<ul>
<li>
<strong>Memory predictability.</strong> A single join would hold every intersection polygon in memory at once, so peak memory grows with the total number of intersections across all sites. The per-site loop’s working set is one catchment and its handful of overlapping tracts, so peak memory is independent of the number of sites and the largest study areas stay tractable.</li>
<li>
<strong>Debugging and error isolation.</strong> Spatial intersection is sensitive to invalid geometry, and in a single join one bad polygon can abort the whole batch with a stack trace that does not say which input was at fault. In the loop, a failure is attributable to a specific site, and a site whose geometry cannot be repaired is marked with a missing result while the rest of the batch proceeds.</li>
</ul>
<p>Two robustness concerns are handled at the level of the individual site.</p>
<p><strong>Geometry repair.</strong> Tract polygons and provider isochrones often arrive with self-intersections, slivers, or holes that make an exact intersection throw a topology error. The package applies a tiered repair before intersecting: a quick validity check passes clean geometry through untouched; otherwise a standard make-valid step fixes the large majority of cases; and a last-resort zero-width buffer handles the remainder. Geometry that survives all three tiers still invalid is treated as a failure for that site rather than silently producing a wrong area.</p>
<p><strong>Edge cases.</strong> A handful of geometric situations are handled explicitly, each isolated to the site where it occurs.</p>
<ul>
<li>
<em>Empty intersection.</em> A catchment that overlaps no tract — outside ACS coverage, or a missing isochrone — yields a result row marked as covering zero tracts, so the caller can detect it rather than mistake it for a real estimate of zero.</li>
<li>
<em>Sliver fragments.</em> A tract clipped along a coastline or river can intersect in a fragment so thin that its weight is floating-point noise. A small <code>min_weight</code> threshold drops these negligible fragments before they enter an aggregate, so they cannot perturb a total.</li>
<li>
<em>Self-intersections.</em> These are the geometry-repair case above, resolved by the tiered repair and, failing that, by isolating the site.</li>
</ul>
<p>The conceptual point is that the loop turns batch-level fragility into site-level diagnosability, and the equal-area weights are computed identically inside it. The full parameter contract, the default <code>min_weight</code>, the audit attribute used below, and the per-row provenance live in <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>.</p>
</section><section class="level2"><h2 id="numerical-verification-the-formulas-match-the-package">Numerical verification: the formulas match the package<a class="anchor" aria-label="anchor" href="#numerical-verification-the-formulas-match-the-package"></a>
</h2>
<p>This is the section that earns a methodologist’s trust. We take <strong>one</strong> site and <strong>one</strong> ring from the fixtures, pull the per-tract audit the package exposes, and <strong>recompute the coverage weights and a spatial-total aggregation entirely by hand</strong> from the audit’s two area columns. Then we show the by-hand figures equal the package’s reported figures to machine precision. If the formulas on this page were not the formulas the code runs, this check would fail.</p>
<p>We deliberately pick a catchment whose coverage is <em>partial and uneven</em> — not a trivial fully-enclosed case — so the area-fraction formula is genuinely exercised and the coverage and mean weights are genuinely different. The synthetic site <code>AL_SITE_17</code> at a 10-minute drive time intersects three tracts: one it fully contains and two it clips at the edge.</p>
<p>First, intersect and keep the per-tract audit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># These fixtures are exactly the shapes pipeline stages 1-2 would have returned,</span></span>
<span><span class="co"># frozen for offline reproducibility.</span></span>
<span><span class="va">sites</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_sites.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">iso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"legacy_2025_isochrones.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">acs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html" class="external-link">readRDS</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span></span>
<span>  <span class="st">"extdata"</span>, <span class="st">"sample_alabama_subset.rds"</span>, package <span class="op">=</span> <span class="st">"catchmentACS"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">site_id</span>    <span class="op">&lt;-</span> <span class="st">"AL_SITE_17"</span></span>
<span><span class="va">drive_time</span> <span class="op">&lt;-</span> <span class="fl">10L</span></span>
<span></span>
<span><span class="va">iso_one</span> <span class="op">&lt;-</span> <span class="va">iso</span><span class="op">[</span></span>
<span>  <span class="va">iso</span><span class="op">$</span><span class="va">site_id</span> <span class="op">==</span> <span class="va">site_id</span> <span class="op">&amp;</span> <span class="va">iso</span><span class="op">$</span><span class="va">drive_time_min</span> <span class="op">==</span> <span class="va">drive_time</span>, ,</span>
<span>  drop <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">]</span></span>
<span></span>
<span><span class="va">weighted</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cacs_intersect_weight.html">cacs_intersect_weight</a></span><span class="op">(</span></span>
<span>  iso_sf           <span class="op">=</span> <span class="va">iso_one</span>,</span>
<span>  acs_sf           <span class="op">=</span> <span class="va">acs</span>,</span>
<span>  weight_method    <span class="op">=</span> <span class="st">"area"</span>,</span>
<span>  keep_tract_audit <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  verbose          <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span></code></pre></div>
</div>
<p>The audit attribute holds, for each tract the catchment touched, the intersection area <code>int_area_m2</code> and the full tract area <code>tract_area_m2</code> — the two ingredients of <span class="math inline">w^{cov}_{sj}</span> — both measured on EPSG:5070:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">audit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="va">weighted</span>, <span class="st">"cacs_tract_audit"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span>, <span class="va">int_area_m2</span>, <span class="va">tract_area_m2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html" class="external-link">desc</a></span><span class="op">(</span><span class="va">int_area_m2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">audit</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  GEOID       int_area_m2 tract_area_m2
  &lt;chr&gt;             &lt;dbl&gt;         &lt;dbl&gt;
1 01125001001    9233961.      9233961.
2 01127001001    1038977.      9233961.
3 01123001001    1038971.      9233961.</code></pre>
</div>
</div>
<section class="level3"><h3 id="step-1-recompute-both-weights-by-hand">Step 1 — recompute both weights by hand<a class="anchor" aria-label="anchor" href="#step-1-recompute-both-weights-by-hand"></a>
</h3>
<p>From those two columns we form the coverage weight (each tract’s own denominator) and the normalized mean weight (the common catchment denominator), straight from the formulas above:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hand</span> <span class="op">&lt;-</span> <span class="va">audit</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span></span>
<span>    w_cov  <span class="op">=</span> <span class="va">int_area_m2</span> <span class="op">/</span> <span class="va">tract_area_m2</span>,        <span class="co"># |I_s n T_j| / |T_j|</span></span>
<span>    w_mean <span class="op">=</span> <span class="va">int_area_m2</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">int_area_m2</span><span class="op">)</span>      <span class="co"># |I_s n T_j| / sum_k |I_s n T_k|</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">hand</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span>, <span class="va">w_cov</span>, <span class="va">w_mean</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  GEOID       w_cov w_mean
  &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
1 01125001001 1.000 0.816
2 01127001001 0.113 0.0918
3 01123001001 0.113 0.0918</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  sum_w_cov  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">hand</span><span class="op">$</span><span class="va">w_cov</span><span class="op">)</span>,    <span class="co"># NOT 1: each term has its own denominator</span></span>
<span>  sum_w_mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">hand</span><span class="op">$</span><span class="va">w_mean</span><span class="op">)</span>    <span class="co"># exactly 1 by construction</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sum_w_cov sum_w_mean
  1.225033   1.000000 </code></pre>
</div>
</div>
<p>The three coverage weights are <code>1.000</code>, <code>0.1125</code>, and <code>0.1125</code>: one tract fully enclosed, two clipped to about a ninth of their area. Their sum, about <code>1.225</code>, is the effective number of whole tracts the catchment covers — emphatically not one, exactly as the derivation said. The mean weights, by contrast, sum to exactly <code>1</code>. That structural contrast is the entire difference between a <em>total</em> and an <em>average</em>, here in fixture numbers.</p>
</section><section class="level3"><h3 id="step-2-recompute-a-spatial-total-by-hand">Step 2 — recompute a spatial total by hand<a class="anchor" aria-label="anchor" href="#step-2-recompute-a-spatial-total-by-hand"></a>
</h3>
<p>Now a count. <em>Persons in poverty</em> (<code>B17001_002</code>) is a <code>spatial_total</code>, so the package reports <span class="math inline">\widehat{Y}_s = \sum_j w^{cov}_{sj}\, Y_j</span>. We pull the three tracts’ published counts and form that sum by hand:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">counts</span> <span class="op">&lt;-</span> <span class="va">acs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">sf</span><span class="fu">::</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html" class="external-link">st_drop_geometry</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">GEOID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="va">hand</span><span class="op">$</span><span class="va">GEOID</span>, <span class="va">variable</span> <span class="op">==</span> <span class="st">"B17001_002"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span>, Y <span class="op">=</span> <span class="va">estimate</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hand_total</span> <span class="op">&lt;-</span> <span class="va">hand</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">GEOID</span>, <span class="va">w_cov</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">counts</span>, by <span class="op">=</span> <span class="st">"GEOID"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hand_total</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  GEOID       w_cov     Y
  &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;
1 01125001001 1.000  1020
2 01127001001 0.113  1104
3 01123001001 0.113   828</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hand_Y_hat</span>       <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">hand_total</span><span class="op">$</span><span class="va">w_cov</span> <span class="op">*</span> <span class="va">hand_total</span><span class="op">$</span><span class="va">Y</span><span class="op">)</span>   <span class="co"># sum_j w_cov * Y_j</span></span>
<span><span class="va">hand_weight_sum</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">hand_total</span><span class="op">$</span><span class="va">w_cov</span><span class="op">)</span>                  <span class="co"># sum_j w_cov</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span>hand_Y_hat <span class="op">=</span> <span class="va">hand_Y_hat</span>, hand_weight_sum <span class="op">=</span> <span class="va">hand_weight_sum</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     hand_Y_hat hand_weight_sum
    1237.382230        1.225033 </code></pre>
</div>
</div>
</section><section class="level3"><h3 id="step-3-compare-against-the-package">Step 3 — compare against the package<a class="anchor" aria-label="anchor" href="#step-3-compare-against-the-package"></a>
</h3>
<p>The package’s own row for the same variable reports the estimate and the weight sum it computed internally:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pkg_row</span> <span class="op">&lt;-</span> <span class="va">weighted</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">==</span> <span class="st">"B17001_002"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">estimate</span>, <span class="va">weight_sum</span>, <span class="va">n_tracts</span>,</span>
<span>         <span class="va">estimand_family</span>, <span class="va">weight_basis</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pkg_row</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  variable   estimate weight_sum n_tracts estimand_family weight_basis
  &lt;chr&gt;         &lt;dbl&gt;      &lt;dbl&gt;    &lt;int&gt; &lt;chr&gt;           &lt;chr&gt;
1 B17001_002    1237.       1.23        3 spatial_total   coverage    </code></pre>
</div>
</div>
<p><code>estimand_family</code> is <code>spatial_total</code> and <code>weight_basis</code> is <code>coverage</code>, confirming the package routed this count through the coverage path. Now the equality check — by-hand against package, on both the estimate and the weight sum:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  estimate_match      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">hand_Y_hat</span>,      <span class="va">pkg_row</span><span class="op">$</span><span class="va">estimate</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  weight_sum_match    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="va">hand_weight_sum</span>, <span class="va">pkg_row</span><span class="op">$</span><span class="va">weight_sum</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  estimate_abs_diff   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">hand_Y_hat</span>      <span class="op">-</span> <span class="va">pkg_row</span><span class="op">$</span><span class="va">estimate</span><span class="op">)</span>,</span>
<span>  weight_sum_abs_diff <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">abs</a></span><span class="op">(</span><span class="va">hand_weight_sum</span> <span class="op">-</span> <span class="va">pkg_row</span><span class="op">$</span><span class="va">weight_sum</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     estimate_match    weight_sum_match   estimate_abs_diff weight_sum_abs_diff
                  1                   1                   0                   0 </code></pre>
</div>
</div>
<p>Both match. The hand-computed spatial total — about <code>1237</code> persons in poverty — equals the package’s <code>estimate</code>, and the hand-computed <span class="math inline">\sum_j w^{cov}_{sj}</span> equals the package’s <code>weight_sum</code>, with absolute differences at the floating-point floor (on the order of <span class="math inline">10^{-12}</span> and <span class="math inline">10^{-15}</span>). The <code>weight_sum</code> column the package reports <em>is</em> the not-equal-to-one coverage sum from Step 1, and the <code>estimate</code> <em>is</em> the coverage-weighted count we built from the audit. The formulas in this article and the arithmetic in the code are the same arithmetic.</p>
<p>The mean weight’s defining property is equally direct to confirm from the same audit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># w_mean sums to exactly one within this (site, drive_time) cell.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Logic.html" class="external-link">isTRUE</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/all.equal.html" class="external-link">all.equal</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">hand</span><span class="op">$</span><span class="va">w_mean</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section><section class="level3"><h3 id="the-intensive-path-by-definition">The intensive path, by definition<a class="anchor" aria-label="anchor" href="#the-intensive-path-by-definition"></a>
</h3>
<p>A <code>spatial_total</code> count and an <code>area_weighted_scalar_proxy</code> scalar reuse this <em>identical</em> intersection geometry; only the denominator of the weight differs — <span class="math inline">\lvert T_j \rvert</span> for the total just verified, <span class="math inline">\sum_k \lvert I_s \cap T_k
\rvert</span> for the mean. By definition the scalar proxy is the mean-weighted blend</p>
<p><span class="math display">
\widehat{\bar X}_s = \sum_j w^{mean}_{sj}\, X_j ,
</span></p>
<p>a convex combination that lands strictly between <span class="math inline">\min_j X_j</span> and <span class="math inline">\max_j X_j</span>. Because the mean weights just summed to one, this is the structural guarantee that a catchment “average per-capita income” cannot exceed any tract’s per-capita income — the exact opposite of what summing an intensive level with the coverage weight would do, which inflates the figure past every tract’s value into a number no one earns. That is the silent estimand error the family split exists to enforce, and it is why the package routes <code>B19301_001</code> through the mean path and <code>B17001_002</code> through the coverage path automatically.</p>
<p>The package’s reported proxy <code>estimate</code> for a scalar is on this per-unit scale by construction. Its exact per-cell normalization — in particular how it handles a requested variable that is missing in some intersecting tracts — is a bookkeeping detail that is the package’s responsibility, documented in the “Estimand families and weights” section of <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>. We therefore frame the proxy here at the level of its definition rather than printing a specific proxy estimate number, so this self-contained check stays anchored on the <strong>coverage-weighted <code>spatial_total</code></strong> path it verifies exactly, and on the <span class="math inline">\sum_j w^{mean}_{sj} = 1</span> identity, both confirmed above to machine precision.</p>
<p>To summarize the check: the coverage weight, its non-unit sum, the package’s <code>weight_sum</code>, and the coverage-weighted <code>spatial_total</code> all coincide with the hand computation to the floating-point floor; the mean weights sum to exactly one; and the scalar proxy is the definitional mean-weighted blend on the per-unit scale, between each tract’s minimum and maximum.</p>
</section></section><section class="level2"><h2 id="where-this-sits">Where this sits<a class="anchor" aria-label="anchor" href="#where-this-sits"></a>
</h2>
<p>This article derived and verified the spatial half of the estimator. Its two companions cover the uncertainty half, and the methodology overview ties all three together; each reuses the notation fixed in the overview.</p>
<ul>
<li>
<strong>The estimator overview</strong>, with the shared notation, the six-family table, and the count-vs-average worked example: <code><a href="../articles/methodology.html">vignette("methodology", package = "catchmentACS")</a></code>. This article is the derivation behind its weight and family sections.</li>
<li>
<strong>MOE propagation</strong> — the published tract MOEs are carried through these same weights by <code><a href="../reference/cacs_propagate_moe.html">cacs_propagate_moe()</a></code>; the four formula families, the <span class="math inline">M = 1.645\,SE</span> conversion, the ratio-variance forms, and the independence assumptions are derived in <code><a href="../articles/theory-moe-propagation.html">vignette("theory-moe-propagation", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_propagate_moe.html">?cacs_propagate_moe</a></code>.</li>
<li>
<strong>Derived rates</strong> — the coverage-weighted numerator and denominator totals built here are divided into the curated catchment rates in <code><a href="../articles/theory-derived-rates.html">vignette("theory-derived-rates", package = "catchmentACS")</a></code> and <code><a href="../reference/cacs_derive_rates.html">?cacs_derive_rates</a></code>.</li>
<li>
<strong>Function reference</strong> — the locked signature, the per-site loop, the edge cases, the tract audit attribute used above, the <code>min_weight</code> sliver filter, the per-row provenance, and the “Estimand families and weights” section: <code><a href="../reference/cacs_intersect_weight.html">?cacs_intersect_weight</a></code>.</li>
</ul>
<p>For the applied, run-it path that produces reporting tables from these same fixtures, see <code><a href="../articles/getting-started.html">vignette("getting-started", package = "catchmentACS")</a></code> and <code><a href="../articles/alabama-tutorial.html">vignette("alabama-tutorial", package = "catchmentACS")</a></code>.</p>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="https://github.com/joonho112" class="external-link">JoonHo Lee</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
